### ISSUE TITLE
libsecret error: (escape-sequence)

### ISSUE THREAD

**Issue by j3bx** [KRTirtho/spotube#583] opened 2023-07-18 02:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Uppon starting on Arch linux (everything latest) the app throws the following error:
```dart
** (spotube:6332): WARNING **: 21:16:50.618: libsecret_error: (escape sequences)
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected extension byte (at offset 1)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351)
#2      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:503)
#3      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:478)
#4      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
#5      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
<asynchronous suspension>
#6      PersistedStateNotifier.initializeBoxes (package:spotube/utils/persisted_state_notifier.dart:57)
<asynchronous suspension>
#7      main (package:spotube/main.dart:123)
<asynchronous suspension>
```
It seems it fails at converting some characters into UTF-8

### Expected Behavior

Successfully convert the characters and start 

### Steps to reproduce

Open the app on linux

### Operating System

Arch linux latest version

### Spotube version

latest

### Installation source

GitHub Releases (Binary), Arch User Repository (AUR), Flathub (Flatpak)

**Comment by KRTirtho** [comment] 2023-07-21 03:03
Duplicate of https://github.com/KRTirtho/spotube/issues/553

**Closed** 2023-07-21 03:04 UTC
Labels: bug, duplicate
