### ISSUE TITLE
when clicked on artist -> error occurs- type 'double' is not a subtype of 'int?' in typecast 

### ISSUE THREAD

**Issue by AbhinayPoloju** [KRTirtho/spotube#1138] opened 2024-01-24 12:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

type 'double' is not a subtype of 'int?' in typecast 

### Expected Behavior

Loading of artists playlist

### Steps to reproduce

1. I opened App
2. Then I browed through Album
3. Then I clicked on Artist Link 
4. Then error occurred
5. type 'double' is not a subtype of 'int?' in typecast 

### Operating System

Windows

### Spotube version

3.4.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Self grab

- [X] I'm ready to work on this issue!

**Comment by the-dijkstra** [comment] 2024-01-24 14:05
![image](https://github.com/KRTirtho/spotube/assets/9967336/96b1608f-95de-4718-884f-ad8c17e2e376)

**Comment by ProgmRuanSilva** [comment] 2024-01-24 16:49
me too

**Comment by ProgmRuanSilva** [comment] 2024-01-24 16:51
my last log of is this:

============================== CATCHER 2 LOG ==============================
------- DEVICE INFO -------
name: Archcraft
version: null
id: archcraft
idLike: [arch]
versionCodename: null
versionId: rolling
prettyName: Archcraft
buildId: rolling
variant: null
variantId: null
machineId: 301aa10cb7c440e2b51c8a759dbf7ecd
------- APP INFO -------
environment: release
version: 3.4.0
appName: spotube
buildNumber: 27
packageName: spotube
---------- ERROR ----------
PathNotFoundException: Cannot retrieve length of file, path = 'url' (OS Error: No such file or directory, errno = 2)
------- STACK TRACE -------
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.length.<anonymous closure> (dart:io/file_impl.dart:389)
<asynchronous suspension>
#2      FileImage._loadAsync (package:flutter/src/painting/image_provider.dart:1481)
<asynchronous suspension>
#3      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:969)
<asynchronous suspension>
------- CUSTOM INFO -------

**Comment by ProgmRuanSilva** [comment] 2024-01-24 16:51
My last log is this:

============================== CATCHER 2 LOG ==============================
------- DEVICE INFO -------
name: Archcraft
version: null
id: archcraft
idLike: [arch]
versionCodename: null
versionId: rolling
prettyName: Archcraft
buildId: rolling
variant: null
variantId: null
machined: 
------- APP INFO -------
environment: release
version: 3.4.0
appName: spotube
buildNumber: 27
packageName: spotube
---------- ERROR ----------
PathNotFoundException: Cannot retrieve length of file, path = 'url' (OS Error: No such file or directory, errno = 2)
------- STACK TRACE -------
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.length.<anonymous closure> (dart:io/file_impl.dart:389)
<asynchronous suspension>
#2      FileImage._loadAsync (package:flutter/src/painting/image_provider.dart:1481)
<asynchronous suspension>
#3      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:969)
<asynchronous suspension>
------- CUSTOM INFO -------

**Comment by guysoft** [comment] 2024-01-24 19:40
I get this both on android and linux client

**Comment by olamarvel** [comment] 2024-01-24 20:51
Same issue

**Comment by Razor7100** [comment] 2024-01-25 01:02
I also get this issue. 
win11 client

**Comment by BlorisL** [comment] 2024-01-25 09:41
Duplicate of #1018

**Comment by wasd52030** [comment] 2024-01-26 02:28
same issue on android 13

**Closed** 2024-01-27 06:23 UTC
Labels: bug
