### ISSUE TITLE
Alternative track source should be persistent and used for downloads

### ISSUE THREAD

**Issue by Abdallah-Ragab** [KRTirtho/spotube#1233] opened 2024-02-14 06:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Alternative track source should be persistent

When the app uses the wrong song/cover from YouTube and the user chooses the correct one it should be saved and persistent for better user experience. User should not have to choose an alternative source for their favorite song every time they listen to it which is a lot :)
At least saved/liked songs and the saved playlists tracks should be persistent as they are Accessed often to avoid taking a lot of storage.

### Alternative track source should be used for downloads too

Also when a source is chosen it is not used for downloading which is a bummer. If the user doesn't want to listen to a weird crappy cover they certainly don't want to download it. So the alternative source should apply to downloads too. 
Thanks 

### Suggested solution

The link to the alternative track source should be saved as a meta data and used for downloads and streaming

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-02-24 16:12
Duplicate of #840

**Closed by KRTirtho** 2024-02-24 16:12 UTC
Labels: duplicate, enhancement
