### ISSUE TITLE
Add an option to auto-save m4a streams

### ISSUE THREAD

**Issue by owosoup** [KRTirtho/spotube#1658] opened 2024-06-23 10:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I stream music with the m4a container, because it's more reliable. It would be nice to see an option to toggle that would simply save these .m4a files automatically instead of putting them in the cache or whatever.

### Suggested solution

Use the download function of the app if enabled, instead of streaming. Since you can already download with spotube, seems like it wouldn't be too hard to implement.

### Useful resources

I guess you could just shift code around? If so then use the source code

### Additional information

Take ur time :)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-07-09 12:55
> Since you can already download with spotube, seems like it wouldn't be too hard to implement.

Yeah I wish 😭

**Comment by KRTirtho** [comment] 2024-07-09 12:56
Duplicate of #709

**Closed by KRTirtho** 2024-07-09 12:56 UTC
Labels: enhancement

**Comment by Porrumentzio** [comment] 2024-10-19 13:14
I was to open another issue but I'll rather explain my point here:

I would add an option in settings so that every track that is played more than two times is automatically downloaded and then, when "streaming" it, actually play the downloaded one. Just in order not to be using the internet, because of ecology and personal economy.
