### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by JErfurt** [KRTirtho/spotube#655] opened 2023-08-25 16:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Original Spotify have a proxy settings. I need to use proxy with Spotify.

### Suggested solution

Add Proxy

### Additional information

More people will be able to use your application.

**Comment by KRTirtho** [comment] 2023-08-25 16:50
Duplicate of https://github.com/KRTirtho/spotube/issues/88

**Comment by KRTirtho** [comment] 2023-08-25 16:51
> Is there an existing issue for this?
>   [x] I have searched the existing issues

Can you tell me what's the point of even having this check?

**Closed by KRTirtho** 2023-08-25 16:51 UTC
Labels: enhancement
