### ISSUE TITLE
Feature for lyrics

### ISSUE THREAD

**Issue by Sahil-Rajoria** [KRTirtho/spotube#1967] opened 2024-10-06 08:32 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Pain

I don't like when the app chooses lyrics source by its own. Example - I was listening to a new song "Millionaire by honey singh" & the app chosen lyrics of "Billionaire song by honey singh" from lrclib because lyrics are not available in spotify.

### Suggested solution

You could add a feature to choose lyrics source (whether spotify/musixmatch/lrclib/kugou/other) manually. Also a feature to choose lyrics manually of the song from the selected lyrics source like ViMusic/RiMusic app.

### Useful resources

RiMusic or ViMusic.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-10-10 15:52
>  Also a feature to choose lyrics manually of the song from the selected lyrics source like ViMusic/RiMusic app.

I literally can't actually

**Comment by KRTirtho** [comment] 2024-10-10 15:52
Duplicate of #1662

**Closed** 2024-10-10 15:57 UTC
Labels: duplicate, enhancement
