### ISSUE TITLE
Write the title here

### ISSUE THREAD

**Issue by AzazelHD** [KRTirtho/spotube#1242] opened 2024-02-20 00:02 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Pain

Could you allow us to import songs from our own library? I am on mobile, android, and I mean to add the already downloaded songs (to add as library a folder we select and its audio files). But i guess on other platforms it should behave the same way

### Suggested solution

Could you allow us to import songs from our own library? I am on mobile, android, and I mean to add the already downloaded songs (to add as library a folder we select and its audio files). But i guess on other platforms it should behave the same way

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-02-24 16:06
Duplicate of #595

**Closed by KRTirtho** 2024-02-24 16:06 UTC
Labels: enhancement
