### ISSUE TITLE
[Bug] Can not click Submit button on Windows client

### ISSUE THREAD

**Issue by Icarus-Xu** [KRTirtho/spotube#334] opened 2022-11-30 05:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I pasted sp_dc and sp_key field, then clicked submit button but no response
my account has premium access.

![image](https://user-images.githubusercontent.com/11155311/204716058-c439798a-b2d6-4569-b099-4fa784be3669.png)

### Expected Behavior

login correctly

### Operating System

Windows

### Operating System Version

Windows 11

### Installation Source

Github Release (Binary)

**Comment by KRTirtho** [comment] 2022-11-30 10:27
Duplicate of #333

**Comment by Icarus-Xu** [comment] 2023-01-02 10:12
problem persist on v2.6.0

**Closed** 2023-01-05 04:17 UTC
Labels: bug, duplicate, good first issue
