### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by TheLesbianCollector** [KRTirtho/spotube#589] opened 2023-07-19 08:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whenever I launch the app, I only see black window.
The icon doesn't even show up in my panel.

### Expected Behavior

First time using the app, but pretty sure this shouldn't only appear as black window.

### Steps to reproduce

1. Installed from Arch AUR using YAY
2. Launch the app
3. Black window, totally black with generic window icon in the panel

### Operating System

ArchCraft XFCE

### Spotube version

v3.0

### Installation source

Arch User Repository (AUR)

### Additional information

I only made this Github account for this report.

**Comment by TheLesbianCollector** [comment] 2023-07-19 08:07
here is the screenshot:

![Screenshot_2023-07-19_16-06-11](https://github.com/KRTirtho/spotube/assets/139956740/cc9d4279-b6f2-4e71-829d-f99b8ba5da96)

**Comment by RaptaG** [comment] 2023-07-19 09:01
please run `spotube` inside a terminal and give us the output

**Comment by TheLesbianCollector** [comment] 2023-07-19 21:37
Thanks, I really appreciate the quick response. 
Here is the output:

   ~ spotube
package:media_kit_libs_linux registered.
flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.

** (spotube:10821): WARNING **: 05:34:45.782: libsecret_error: R\xcdXy\xd2\u007f
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Missing extension byte (at offset 2)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351)
#2      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:503)
#3      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:478)
#4      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
#5      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
<asynchronous suspension>
#6      PersistedStateNotifier.initializeBoxes (package:spotube/utils/persisted_state_notifier.dart:57)
<asynchronous suspension>
#7      main (package:spotube/main.dart:123)
<asynchronous suspension>
![Screenshot_2023-07-20_05-36-05](https://github.com/KRTirtho/spotube/assets/139956740/1293b0ba-4587-4bfd-a689-eb4dd332749f)

**Comment by KRTirtho** [comment] 2023-07-21 03:03
Duplicate of https://github.com/KRTirtho/spotube/issues/553

**Closed by KRTirtho** 2023-07-21 03:03 UTC
Labels: bug

**Comment by KRTirtho** [comment] 2023-07-21 03:07
Duplicate of https://github.com/KRTirtho/spotube/issues/553
