### ISSUE TITLE
"Error Authentication Failure" everytime I open the App

### ISSUE THREAD

**Issue by Sahil2315** [KRTirtho/spotube#1867] opened 2024-09-10 07:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As soon as I open the app (on a different date when compared to the last time i opened the app) the UI bugs and it shows me Error Authentication Failure DioException[connection error] .... I have to clear sign out and then sign in again to spotify to start listening to music, every time I open the app. 

### Expected Behavior

The App should just work using the Spotify Login token that it stored the last time I logged in.

### Steps to reproduce

1. Open the App the next day
2. Error Pop up will Appear
3. All the Playlists and Songs Disappear
4. Search will no longer work
5. Can't Listen to music at all

### Operating System

Android

### Spotube version

v3.8.0

### Installation source

Play Store (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by kernaltrap8** [comment] 2024-09-11 19:52
They probably aren't re-authenticating with Spotify, so the token expires. I have this issue as well. Perhaps I can try fixing it myself if a contributor doesn't comment.

**Comment by Kempje1** [comment] 2024-09-12 12:51
Was a spotify sided bug

**Comment by Sahil-Rajoria** [comment] 2024-09-12 21:22
@kernaltrap8 Please i beg you to fix this error. I want stability in app. Everytime it shows this error and i end up clearing data and reconnect app to spotify again & again. Also because of this i cant able to listen offline.

**Comment by Sahil2315** [comment] 2024-09-13 05:23
> Was a spotify sided bug

was? so that's supposed to mean that it is fixed now..... am I right here?...... is it fixed now?

**Comment by kernaltrap8** [comment] 2024-09-13 16:05
> > Was a spotify sided bug
> 
> was?.... so that's supposed to mean that it is fixed now..... am I right here?...... is it fixed now?

i thought so, but it doesn't appear to be.

**Comment by Kempje1** [comment] 2024-09-13 16:27
> > > Was a spotify sided bug
> > 
> > was?.... so that's supposed to mean that it is fixed now..... am I right here?...... is it fixed now?
> 
> i thought so, but it doesn't appear to be.

For me it's fixed and yes the authentication failure I got was at the time spotify had a bug just recognized into spotify

**Comment by KRTirtho** [comment] 2024-09-15 04:32
Duplicate of #1866

**Closed by KRTirtho** 2024-09-15 04:32 UTC
Labels: bug, can't-reproduce

**Comment by Porrumentzio** [comment] 2024-09-20 06:03
I face a similar problem but get apparently another error:
![Screenshot_20240920-070159_Spotube](https://github.com/user-attachments/assets/0f21c6bb-a965-4f55-812e-3288960969ed)

Should I create another issue?

**Comment by 881997** [comment] 2025-02-11 01:42
me too
It will not happen after the first open the app if you reboot the phone
