### ISSUE TITLE
Text encoding format

### ISSUE THREAD

**Issue by oliver-xie666** [KRTirtho/spotube#1505] opened 2024-05-15 03:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the chinese Text encoding format is mistake

![98232e42435d26c83b1b634e811b86d](https://github.com/KRTirtho/spotube/assets/75602879/379ecfec-3011-4018-b143-f8e8239186b5)
![9bc353a138b12b0deb6a28befaf96c0](https://github.com/KRTirtho/spotube/assets/75602879/7389e210-01af-4965-8bc4-c1527bf39555)

 

### Expected Behavior

could you fix it

### Steps to reproduce

open the app
the home page

### Operating System

Android

### Spotube version

v3.6.0

### Installation source

Play Store (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by sheiun** [comment] 2024-05-27 08:46
Same issue on "MacOS M2"

**Comment by KRTirtho** [comment] 2024-06-01 05:44
Duplicate of #1463

**Closed by KRTirtho** 2024-06-01 05:44 UTC
Labels: bug, duplicate
