### ISSUE TITLE
Store alternative YouTube source resources in cache (windows)

### ISSUE THREAD

**Issue by equationslayer12** [KRTirtho/spotube#1195] opened 2024-02-03 13:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

By using the alternative track source option (circled in red below), I expect it to store the new source to play each time I play the track.
I shouldn't alternate the source every time I listen to a specific song.

![image](https://github.com/KRTirtho/spotube/assets/80574033/b1220ffd-f96e-4ec5-89b6-1742d1395002)

### Suggested solution

Instead of alternating the source every time I listen to a specific song, It should remember my preference and play my previously chosen source.
Once I alternate the source, it should store it in the cache, and the next time I load the song it would play it.

### Additional information

I've implemented this enhancement, and using it now eases the use of Spotube.

### Self grab

- [X] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-02-04 04:24
Duplicate of https://github.com/KRTirtho/spotube/issues/840

**Closed by KRTirtho** 2024-02-04 04:24 UTC
Labels: enhancement
