### ISSUE TITLE
Sync download with playlist

### ISSUE THREAD

**Issue by holiq** [KRTirtho/spotube#1181] opened 2024-01-30 22:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

If I download a music and I play it from Tracks it's not usage data, but if I play it from playlist it's usage data wich one  it has been downloaded 

### Suggested solution

I want it can be sync, if the music has been downloaded and play it on playlist or else it will not use the data anymore, and the music has been downloaded the button download should be hidden or disabled 

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by JustMarkov** [comment] 2024-02-01 10:17
It seems to be a duplicate of #722

**Closed** 2024-12-08 14:03 UTC
Labels: enhancement
