### ISSUE TITLE
does not support Miracast (Chromecast)

### ISSUE THREAD

**Issue by pdmbis** [KRTirtho/spotube#2109] opened 2024-12-05 11:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I can't use Google home devices (nest one, nest mini, etc.)

### Suggested solution

Is it possible to incorporate this protocol?

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-12-08 13:25
duplicate of #153

**Closed by KRTirtho** 2024-12-08 13:25 UTC
Labels: enhancement
