### ISSUE TITLE
Freezes and Just shows black window

### ISSUE THREAD

**Issue by qxb3** [KRTirtho/spotube#592] opened 2023-07-21 02:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i run spotube in the terminal or as an application it seems just to freeze? and just shows a black window

Error Log:

```
(spotube:6980): Gtk-WARNING **: 02:05:08.021: Locale not supported by C library. Using the fallback 'C' locale.

** (spotube:6980): CRITICAL **: 02:05:08.140: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (spotube:6980): CRITICAL **: 02:05:08.142: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (spotube:6980): CRITICAL **: 02:05:08.143: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (spotube:6980): CRITICAL **: 02:05:08.144: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (spotube:6980): CRITICAL **: 02:05:08.144: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
package:media_kit_libs_linux registered.
flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.

** (spotube:6980): WARNING **: 02:05:08.517: libsecret_error: \xa2\xe1\xe3?\u007f
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Unexpected extension byte (at offset 0)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1747)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351)
#2      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:503)
#3      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:478)
#4      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
#5      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310)
<asynchronous suspension>
#6      PersistedStateNotifier.initializeBoxes (package:spotube/utils/persisted_state_notifier.dart:57)
<asynchronous suspension>
#7      main (package:spotube/main.dart:123)
<asynchronous suspension>
```

### Expected Behavior

Opens

### Steps to reproduce

$ yay -S spotube-bin
$ spotube

### Operating System

Arch Linux / KDE Plasma

### Spotube version

v3.0.0

### Installation source

Arch User Repository (AUR)

**Comment by KRTirtho** [comment] 2023-07-21 03:04
Duplicate of https://github.com/KRTirtho/spotube/issues/553

**Closed by KRTirtho** 2023-07-21 03:04 UTC
Labels: bug, duplicate
