### ISSUE TITLE
error logging in via spotify

### ISSUE THREAD

**Issue by MrPrezAtambaev** [KRTirtho/spotube#1866] opened 2024-09-10 05:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="411" alt="Снимок экрана 2024-09-10 в 11 09 15" src="https://github.com/user-attachments/assets/204436f4-48c2-483e-bcff-d25cc3e5f407">

OS: MacOS 14.6
Spotube version: 3.8.0

### Steps to reproduce

I opened the app and such an error came out, tried to re-download via spotify, but still the same error

### Operating System

Mac OS

### Spotube version

3.8.0

### Installation source

Website (spotube.krtirtho.dev), GitHub Releases (Binary), GitHub Actions (Nightly Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by MrPrezAtambaev** [comment] 2024-09-10 05:28
after a while, he logged into his spotify account himself

**Comment by TheBlackReverand** [comment] 2024-09-11 17:41
In link with #1867 I think

**Comment by MrPrezAtambaev** [comment] 2024-09-11 17:49
> ### Is there an existing issue for this?
> 
> 
> 
> - [X] I have searched the existing issues
> 
> 
> 
> ### Current Behavior
> 
> 
> 
> <img width="411" alt="Снимок экрана 2024-09-10 в 11 09 15" src="https://github.com/user-attachments/assets/204436f4-48c2-483e-bcff-d25cc3e5f407">
> 
> 
> 
> 
> 
> OS: MacOS 14.6
> 
> Spotube version: 3.8.0
> 
> 
> 
> ### Steps to reproduce
> 
> 
> 
> I opened the app and such an error came out, tried to re-download via spotify, but still the same error
> 
> 
> 
> ### Operating System
> 
> 
> 
> Mac OS
> 
> 
> 
> ### Spotube version
> 
> 
> 
> 3.8.0
> 
> 
> 
> ### Installation source
> 
> 
> 
> Website (spotube.krtirtho.dev), GitHub Releases (Binary), GitHub Actions (Nightly Binary)
> 
> 
> 
> ### Additional information
> 
> 
> 
> _No response_
> 
> 
> 
> ### Self grab
> 
> 
> 
> - [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-09-15 04:45
Sigh...

**Comment by KRTirtho** [comment] 2024-09-15 04:46
Duplicate of #1858

**Closed by KRTirtho** 2024-09-15 04:46 UTC
Labels: bug, can't-reproduce
