### ISSUE TITLE
Now my VPN must be in TUN mode, otherwise it can't proxy Spotube. As a result, no songs can be played on my mobile device.

### ISSUE THREAD

**Issue by Eff0rtly** [KRTirtho/spotube#1982] opened 2024-10-09 14:27 UTC
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

Now my VPN must be in TUN mode, otherwise it can't proxy Spotube. As a result, no songs can be played on my mobile device.

### Expected Behavior

fix it

### Steps to reproduce

Now my VPN must be in TUN mode, otherwise it can't proxy Spotube. As a result, no songs can be played on my mobile device.

### Logs

terable.dart:354)
#6      WhereIterator.moveNext (dart:_internal/iterable.dart:450)
#7      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202)
#8      new _GrowableList.of (dart:core-patch/growable_array.dart:152)
#9      new List.of (dart:core-patch/array_patch.dart:39)
#10     Iterable.toList (dart:core/iterable.dart:498)
#11     transformSectionItemJsonMap (package:spotube/models/spotify/home_feed.dart:229)
#12     transformHomeFeedJsonMap.<anonymous closure> (package:spotube/models/spotify/home_feed.dart:241)
#13     MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#14     ListIterator.moveNext (dart:_internal/iterable.dart:354)
#15     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#16     new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#17     new List.of (dart:core-patch/array_patch.dart:39)
#18     ListIterable.toList (dart:_internal/iterable.dart:224)
#19     transformHomeFeedJsonMap (package:spotube/models/spotify/home_feed.dart:244)
#20     CustomSpotifyEndpoints.getHomeFeed (package:spotube/services/custom_spotify_endpoints/spotify_endpoints.dart:164)
<asynchronous suspension>
#21     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-10-09 22:22:44.591012]---------------------
type 'Null' is not a subtype of type 'String' in type cast
#0      SyncedLyricsNotifier.getLRCLibLyrics (package:spotube/provider/spotify/lyrics/synced.dart:109)
<asynchronous suspension>
#1      SyncedLyricsNotifier.build (package:spotube/provider/spotify/lyrics/synced.dart:150)
<asynchronous suspension>
#2      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-10-09 22:22:54.843213]---------------------
DioException [connection error]: The connection errored: 信号灯超时时间已到
 This indicates an error which most likely cannot be solved by the library.
Error: SocketException: 信号灯超时时间已到
 (OS Error: 信号灯超时时间已到
, errno = 121), address = rr5---sn-i3b7knzl.googlevideo.com, port = 53588
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:509)
<asynchronous suspension>
#1      ServerPlaybackRoutes.getStreamTrackId (package:spotube/provider/server/routes/playback.dart:34)
<asynchronous suspension>
#2      RouterEntry.invoke.<anonymous closure> (package:shelf_router/src/router_entry.dart:109)
<asynchronous suspension>
#3      RouterEntry.invoke (package:shelf_router/src/router_entry.dart:104)
<asynchronous suspension>
#4      Router.call (package:shelf_router/src/router.dart:184)
<asynchronous suspension>
#5      handleRequest (package:shelf/shelf_io.dart:138)
<asynchronous suspension>

----------------------------------------
[2024-10-09 22:22:54.843213]---------------------
Failed to open http://localhost:13450/stream/3ZZnixeMe3H3r77Uvtr6AH.
#0      new AudioPlayerInterface.<anonymous closure> (package:spotube/services/audio_player/audio_player.dart:93)
#1      _rootRunUnary (dart:async/zone.dart:1407)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#5      _DelayedData.perform (dart:async/stream_impl.dart:541)
#6      _PendingEvents.handleNext (dart:async/stream_impl.dart:646)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617)
#8      _rootRun (dart:async/zone.dart:1391)
#9      _CustomZone.run (dart:async/zone.dart:1301)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#12     _rootRun (dart:async/zone.dart:1399)
#13     _CustomZone.run (dart:async/zone.dart:1301)
#14     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

----------------------------------------
---------
[2024-10-09 22:24:52.480416]---------------------
[TrackNotFoundError] Counting Stars - OneRepublic
#0      JioSaavnSourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sources/jiosaavn.dart:60)
<asynchronous suspension>
#1      SourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sourced_track.dart:139)
<asynchronous suspension>
#2      sourcedTrackProvider.<anonymous closure> (package:spotube/provider/server/sourced_track.dart:25)
<asynchronous suspension>
#3      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-10-09 22:24:52.486866]---------------------
Failed to open http://localhost:13450/stream/2tpWsVSb9UEmDRxAl1zhX1.
#0      new AudioPlayerInterface.<anonymous closure> (package:spotube/services/audio_player/audio_player.dart:93)
#1      _rootRunUnary (dart:async/zone.dart:1407)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#5      _DelayedData.perform (dart:async/stream_impl.dart:541)
#6      _PendingEvents.handleNext (dart:async/stream_impl.dart:646)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617)
#8      _rootRun (dart:async/zone.dart:1391)
#9      _CustomZone.run (dart:async/zone.dart:1301)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#12     _rootRun (dart:async/zone.dart:1399)
#13     _CustomZone.run (dart:async/zone.dart:1301)
#14     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

----------------------------------------
---------

### Operating System

win10 

### Spotube version

3.8.3

### Installation source

Website (spotube.krtirtho.dev)

### Additional information

no

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-10-10 15:46
Duplicate of #88

**Closed by KRTirtho** 2024-10-10 15:46 UTC
Labels: bug
