### ISSUE TITLE
Suggestions in search

### ISSUE THREAD

**Issue by 13Ibrahim** [KRTirtho/spotube#1842] opened 2024-09-02 19:43 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Pain

Search tab looks too empty.I mostly use search tab not for search. It mostly meant for searching trending songs and suggestions
![Screenshot_20240903-003908](https://github.com/user-attachments/assets/85a4127e-cd0d-44e6-8ca6-d719b06a583f)

### Suggested solution

We can add songs suggestions and trending song there. 

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-12-01 12:03
Duplicate of #93

**Closed by KRTirtho** 2024-12-01 12:03 UTC
Labels: enhancement
