### ISSUE TITLE
Not Being Able To Login Into Spotube

### ISSUE THREAD

**Issue by Shrivatsa7** [KRTirtho/spotube#1478] opened 2024-05-05 15:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot 2024-05-05 210901](https://github.com/KRTirtho/spotube/assets/165672067/7d886348-58b5-4a4b-8274-6faa6593ac18)

### Expected Behavior

.

### Steps to reproduce

.

### Operating System

Windows

### Spotube version

v3.6.0

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by rjfahad** [comment] 2024-05-06 03:50
same problem..

**Comment by KRTirtho** [comment] 2024-05-06 12:43
Duplicate of #905

**Closed by KRTirtho** 2024-05-06 12:43 UTC
Labels: bug
