### ISSUE TITLE
No playback, nothing works

### ISSUE THREAD

**Issue by ThechCorsair** [KRTirtho/spotube#1511] opened 2024-05-16 17:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Version 3.5 simply stopped working

### Expected Behavior

LIsten to music

### Steps to reproduce

!. open app
2. try to play anything

### Operating System

LMDE 6

### Spotube version

3.5.0

### Installation source

Flathub (Flatpak)

### Additional information

I am logged to Spotify correctly, but no playback, it seems all stuck. Uninstalled and reinstalled a lot of times. Is there a way to recover the previous version ?

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-06-02 13:29
Duplicate of #1492

**Comment by KRTirtho** [comment] 2024-06-02 13:29
The reason behind the original issue and your issue is same thus duplicate

**Closed by KRTirtho** 2024-06-02 13:29 UTC
Labels: bug
