### ISSUE TITLE
Spotube is always downloading the first source.

### ISSUE THREAD

**Issue by LunasShade** [KRTirtho/spotube#1701] opened 2024-07-09 14:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you change the source of a song and then press download, it always downloads the first one on the list and not the one that you choose.

### Expected Behavior

Download the Song that was chosen

### Steps to reproduce

 1. open the app
 2. find a song which has the wrong audio source
 3. change the source to the one you want
 4. click download

### Operating System

Android, Linux

### Spotube version

v3.7.1

### Installation source

Play Store (Android), F-Droid (Android), Arch User Repository (AUR)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-07-09 14:46
Duplicate of #1223 

Please stop issue bombing. And check if there's already an issue ticket open for your particular issue.

**Closed by KRTirtho** 2024-07-09 14:46 UTC
Labels: bug
