### ISSUE TITLE
Wrong song played (displays one song but playing some other song)

### ISSUE THREAD

**Issue by Enigma-0** [KRTirtho/spotube#981] opened 2023-12-31 15:09 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When I play song softly (by Karan ajulia and Ikky), it shows that it as playing and the lyrics are also correct, but it plays some other song. I tried all sources, but the issue is not resolved.

### Expected Behavior

It should play the correct song.
![Screenshot_20231231-203305-872](https://github.com/KRTirtho/spotube/assets/68284081/ba3b49e0-684a-4a9b-a3f7-215ac22ea80f)
![Screenshot_20231231-203322-947](https://github.com/KRTirtho/spotube/assets/68284081/f35bead5-7467-4313-8baa-71accde0c611)

### Steps to reproduce

1. Open the app
2. Search for song "softly"
3. Play the first one which is "softly by Karan ajulia & Ikky"
4. It plays some other song with the name softly but plays some other song, lyrics are of the right song.
![Screenshot_20231231-203751-660](https://github.com/KRTirtho/spotube/assets/68284081/d6c6c5d2-aee5-4a98-9f2e-79882fbdf23a)

### Operating System

Android

### Spotube version

V3.4.0

### Installation source

GitHub Releases (Binary), Play Store (Android)

### Additional information

I have faced this problem with this one song, don't know if there are some other songs too.

**Comment by KRTirtho** [comment] 2024-01-03 08:03
You can use the JioSaavn audio source from "Settings" > "Audio Source". It has better support for South Asian tracks.

Also track mismatch can happen. There's no 100% guarantee. You can change the source from the player.

**Comment by KRTirtho** [comment] 2024-01-03 08:04
Duplicate of #883

**Closed** 2024-01-03 08:04 UTC
Labels: bug, duplicate
