### ISSUE TITLE
Persist alternative source 

### ISSUE THREAD

**Issue by DqrknessItself** [KRTirtho/spotube#1752] opened 2024-08-01 22:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

If an incorrect track is used for a song and I must manually choose the correct one via 'alternate sources' every time, it is frustrating.

### Suggested solution

Create a feature or system that allows us to choose a preferred source track and also have it download the selected alternate source during playback. 

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-08-02 09:36
This has been fixed but not yet releases. Try out the [nightly version](https://spotube.krtirtho.dev/downloads/nightly).

**Comment by KRTirtho** [comment] 2024-08-02 09:36
Duplicate of #1223

**Closed by KRTirtho** 2024-08-02 09:36 UTC
Labels: enhancement
