### ISSUE TITLE
Next song won't play

### ISSUE THREAD

**Issue by BlorisL** [KRTirtho/spotube#1154] opened 2024-01-26 08:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I'm driving my car I've my telephone connected via bluetooth and I'm playing some songs with Spotube.
The first song starts corrrectly, but the next one won't play...it seems like the player is stucking loading it. It happens every time with differents songs.
I'm forced to close the app and open it again, but it's unusuable during the driving.
Maybe it is releated to #580 .

### Expected Behavior

The next song has to be played without interruptions.

### Steps to reproduce

1) Open the app connected via bluetooth to the car
2) Play a song
3) Wait for the song to end
4) The next song won't be played

### Operating System

Android

### Spotube version

3.4.0

### Installation source

Play Store (Android)

### Additional information

------- CUSTOM INFO -------
======================================================================
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-01-26 08:43:43.457330

------- DEVICE INFO -------
id: UP1A.231005.007
board: kalama
bootloader: S911BXXS3BWL3
brand: samsung
device: dm1q
display: UP1A.231005.007.S911BXXS3BWL3
fingerprint: samsung/dm1qxeea/dm1q:14/UP1A.231005.007/S911BXXS3BWL3:user/release-keys
hardware: qcom
host: 21DK7918
isPhysicalDevice: true
manufacturer: samsung
model: SM-S911B
product: dm1qxeea
tags: release-keys
type: user
versionBaseOs: samsung/dm1qxeea/dm1q:14/UP1A.231005.007/S911BXXU3BWJM:user/release-keys
versionCodename: REL
versionIncremental: S911BXXS3BWL3
versionPreviewSdk: 0
versionRelease: 14
versionSdk: 34
versionSecurityPatch: 2024-01-01

------- APP INFO -------
environment: release
version: 3.4.0
appName: Spotube
buildNumber: 27
packageName: oss.krtirtho.spotube

---------- ERROR ----------
[MediaKitError] 
Failed to recognize file format.

------- STACK TRACE -------
null
------- CUSTOM INFO -------
======================================================================
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-01-26 08:43:43.457479

------- DEVICE INFO -------
id: UP1A.231005.007
board: kalama
bootloader: S911BXXS3BWL3
brand: samsung
device: dm1q
display: UP1A.231005.007.S911BXXS3BWL3
fingerprint: samsung/dm1qxeea/dm1q:14/UP1A.231005.007/S911BXXS3BWL3:user/release-keys
hardware: qcom
host: 21DK7918
isPhysicalDevice: true
manufacturer: samsung
model: SM-S911B
product: dm1qxeea
tags: release-keys
type: user
versionBaseOs: samsung/dm1qxeea/dm1q:14/UP1A.231005.007/S911BXXU3BWJM:user/release-keys
versionCodename: REL
versionIncremental: S911BXXS3BWL3
versionPreviewSdk: 0
versionRelease: 14
versionSdk: 34
versionSecurityPatch: 2024-01-01

------- APP INFO -------
environment: release
version: 3.4.0
appName: Spotube
buildNumber: 27
packageName: oss.krtirtho.spotube

---------- ERROR ----------
Failed to recognize file format.

------- STACK TRACE -------
#0      new AudioPlayerInterface.<anonymous closure> (package:spotube/services/audio_player/audio_player.dart:28)
#1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
#2      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#3      _DelayedData.perform (dart:async/stream_impl.dart:515)
#4      _PendingEvents.handleNext (dart:async/stream_impl.dart:620)
#5      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591)
#6      _microtaskLoop (dart:async/schedule_microtask.dart:40)
#7      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

------- CUSTOM INFO -------
======================================================================
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-01-26 08:47:59.828512

Loris, [26/01/2024 09:52]
------- DEVICE INFO -------
id: UP1A.231005.007
board: kalama
bootloader: S911BXXS3BWL3
brand: samsung
device: dm1q
display: UP1A.231005.007.S911BXXS3BWL3
fingerprint: samsung/dm1qxeea/dm1q:14/UP1A.231005.007/S911BXXS3BWL3:user/release-keys
hardware: qcom
host: 21DK7918
isPhysicalDevice: true
manufacturer: samsung
model: SM-S911B
product: dm1qxeea
tags: release-keys
type: user
versionBaseOs: samsung/dm1qxeea/dm1q:14/UP1A.231005.007/S911BXXU3BWJM:user/release-keys
versionCodename: REL
versionIncremental: S911BXXS3BWL3
versionPreviewSdk: 0
versionRelease: 14
versionSdk: 34
versionSecurityPatch: 2024-01-01

------- APP INFO -------
environment: release
version: 3.4.0
appName: Spotube
buildNumber: 27
packageName: oss.krtirtho.spotube

---------- ERROR ----------
PathNotFoundException: Cannot retrieve length of file, path = 'url' (OS Error: No such file or directory, errno = 2)

------- STACK TRACE -------
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.length.<anonymous closure> (dart:io/file_impl.dart:389)
<asynchronous suspension>
#2      FileImage._loadAsync (package:flutter/src/painting/image_provider.dart:1481)
<asynchronous suspension>
#3      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:969)
<asynchronous suspension>

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-02-18 17:10
Duplicate of #1234

(Under special circumstances)

**Closed by KRTirtho** 2024-02-18 17:10 UTC
Labels: bug, duplicate
