### ISSUE TITLE
Spotube 3.7.1 doesn't launch after update/installation

### ISSUE THREAD

**Issue by CSeriestechhero** [KRTirtho/spotube#1724] opened 2024-07-21 05:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After installing or updating Spotube (ver3.7.1), the application briefly starts, grabs my system's location, and terminates without displaying any window. I have to downgrade to 3.7.0 to use this program. 

### Expected Behavior

After installing or updating to Spotube, the application should start up fully and display the application window.

### Steps to reproduce

1. Download the stable Spotube release from GitHub releases or the Spotube webpage.
2. Run the installer (with and without administrator privileges)
3. Finalize the installation
4. Launch the Spotube executable (via start menu or directly through Program Files directory)

### Operating System

Windows 10 IoT Enterprise LTSC, Version: 21H2, OS build: 19044.3324

### Spotube version

v3.7.1

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev), GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by whutgao** [comment] 2024-07-21 06:05
me too

**Comment by leninalbertolp** [comment] 2024-07-22 13:32
Same problem here

**Comment by kanlukasz** [comment] 2024-08-06 08:15
I can confirm. It doesn't work, as described above

**Comment by karniv00l** [comment] 2024-08-06 08:18
try this: https://github.com/KRTirtho/spotube/issues/1590#issuecomment-2159705347

**Comment by KRTirtho** [comment] 2024-08-12 03:10
Duplicate of #1578

**Closed by KRTirtho** 2024-08-12 03:10 UTC
Labels: bug, Windows
