### ISSUE TITLE
Almost unusable with long playlists

### ISSUE THREAD

**Issue by rramirezg22** [KRTirtho/spotube#762] opened 2023-09-29 17:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Playlists with lots of tracks take forever to load or simply do not load. 

### Expected Behavior

Well, playlists with less than 100 tracks seems to have no problem

### Steps to reproduce

Play any playlist with lot of tracks

### Operating System

Tested in Windows and Android

### Spotube version

3.1.2

### Installation source

GitHub Releases (Binary)

### Additional information

Great idea and great app. But is almost unusable with long playlists. Any plans to solve or mitigate this problem ? 
Some folks talk about pagination, could be useful for the first load, maybe also local cache and refresh data in the background.

Similar report: https://github.com/KRTirtho/spotube/issues/670

**Comment by KRTirtho** [comment] 2023-09-30 12:31
Duplicate of #670

**Closed by KRTirtho** 2023-09-30 12:31 UTC
Labels: bug
