### ISSUE TITLE
Song Mismatch 

### ISSUE THREAD

**Issue by SubhamMahato** [KRTirtho/spotube#2145] opened 2024-12-16 00:31 UTC
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

EMIN feat. JONY - КАМИН
when i search the above song it plays https://youtu.be/xsoS0XOxVJ0

### Expected Behavior

But instead it is supposed to play https://youtu.be/nOeJuoFs6sM

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

Android 

### Installation source

Play Store (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Cwpute** [comment] 2024-12-16 20:02
see issue #835

**Comment by KRTirtho** [comment] 2024-12-24 03:23
Duplicate of #883

**Closed by KRTirtho** 2024-12-24 03:23 UTC
Labels: bug
