### ISSUE TITLE
Play songs with Android Auto

### ISSUE THREAD

**Issue by Vidhyarth** [KRTirtho/spotube#1232] opened 2024-02-13 15:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I want to play songs in wireless android auto using this app.

### Suggested solution

I want to play songs in wireless android auto using this app.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by olivier2** [comment] 2024-02-13 22:50
This sounds like fun and according to [this](https://medium.com/@rusoni09/android-auto-integration-in-flutter-91de1e33c6f8), not too complicated since spotube already uses audio_service. I'll look into it!

**Comment by olivier2** [comment] 2024-02-14 00:30
Hey @Vidhyarth , can you tell me more about what you tried and what happened?

I used the app with Google Desktop Head Unit (DHU) for testing Android Auto (AA) compatible apps. Here are the 3 scenarios I tested and the results (all of this while connected by cable, not wirelessly):

1. Connect to AA, then launch Spotube from AA/DHU app screen : App stays stuck on splash screen
2. Connect to AA, then launch Spotube from phone : App stays stuck on splash screen
3. Launch Spotube from phone, then connect to AA : Works! I can play audio (see screenshot)

**Can you confirm scenario 3 works for you using a cable?**

![android auto spotube](https://github.com/KRTirtho/spotube/assets/1408881/e5247df9-2d46-4852-8071-8e28e8182f6d)

**Comment by Vidhyarth** [comment] 2024-02-14 06:57
Hi,

For "Launch Spotube from phone, then connect to AA : Works! I can play
audio (see screenshot)" yes, I am also able to play the songs. However, I
cannot operate like I am unable to change the song to the next or previous
song using AA.

Also, If I operate it from Mobile then it got stuck and I need to reopen
the app and use it again.


Thanks and Regards,
Vidhyarth Vora
(091)9974599592

**Comment by skruglov2023** [comment] 2024-02-15 05:28
> Also, If I operate it from Mobile then it got stuck and I need to reopen the app and use it again.

I wanted to mention, I noticed this as well driving today. (Or, well, while still in the parking lot). Had to disconnect from AA, open Spotube and play a song, and then when I reconnected to AA had to also pause spotify--Spotube doesn't override other sources?)
I was however able to switch between songs/play/pause from the AA display.

**Comment by KRTirtho** [comment] 2024-02-17 16:25
Duplicate of #623

**Closed** 2024-02-17 16:26 UTC
Labels: duplicate, enhancement

**Comment by emskia-bgp** [comment] 2024-02-17 22:30
> > Also, If I operate it from Mobile then it got stuck and I need to reopen the app and use it again.
> 
> I wanted to mention, I noticed this as well driving today. (Or, well, while still in the parking lot). Had to disconnect from AA, open Spotube and play a song, and then when I reconnected to AA had to also pause spotify--Spotube doesn't override other sources?) I was however able to switch between songs/play/pause from the AA display.

 This even doesn't work on my car. The icon is missing from AA, and I cannot add it. Android 14 with AA 11.1.640234-release

**Comment by guegrer** [comment] 2024-04-14 21:41
@emskia-bgp same issue here i dont see the app on my AA car
if i can help you AA 11.5.6641024-release latest spottube apk...

**Comment by Zaphood22** [comment] 2024-08-23 16:07
I really would appreciate an Android Auto solution, because for me the car is the place to hear music! 
I'm on Android 14, a Samsung Galaxy with One UI 6.1, Spotube 3.8,0 Build 33, AA 12.5.643034. 
If I play a song in Spotube and plug the phone in, sometimes the song goes on, sometimes not. If it works, there are no controls for it, the AA screen seems to be unaffected and displays his start screen (tiles).

**Comment by papinewman** [comment] 2024-11-15 19:08
Tengo descargado Spotube en mi movil Samsung S24 Ultra y funciona sin problema pero aun teniendo habilitado laos ajustes de desarrollador en mi android auto no aparece en la aplicación en el coche. Podrian ayudarme?

**Comment by TDGalea** [comment] 2025-03-07 13:03
I would absolutely love if SpotTube on AAuto could happen. Spotify recently has completely borked for myself and many others, showing literally every single track in existence as "unplayable", so SpotTube is now seeing more use from me.

Sadly I'm not sure if we will ever see this happen though; from what I've found, I think apps need direct approval from Lord Googleton, and something that arguably steals users from both Spotify and YT Music at the same time...

Eek.

**Comment by Zaphood22** [comment] 2025-04-02 14:33
I don't think the Godfather has to approve, since there are other music
apps like for example Simpmusic (Github site here
<https://github.com/maxrave-dev/SimpMusic>), that draws his music from YT
as well, that have it. You have to switch on the developer mode of Android
Auto for this, that's all. But only Spotube has this unique approach of
using the algorithm from Spotify and the music from YT!. So I think it's
rather a general technical problem. But it would be worth the effort!
