### ISSUE TITLE
New version not being installed

### ISSUE THREAD

**Issue by AarushiswinnerYo** [KRTirtho/spotube#1717] opened 2024-07-16 07:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I launch spotube, it says new 3.7.1 version has been launched.
But when I install with the official spotube installer and launch spotube, it still says the same update notice
![image](https://github.com/user-attachments/assets/36341a7c-cf49-49a0-89a4-b177c2002836)
and it still says the version number as 3.7.0
![image](https://github.com/user-attachments/assets/7ab2fb49-8599-4716-8046-0579a5c8fa46)

### Expected Behavior

The expected behaviour should be that it should be on the upto date version

### Steps to reproduce

1. Open the app
2. The update window comes up
3. I clicked on "Download Now"
4. I download the windows installer
5. I run the installer
6. Allow all permissions to the installer
7. The installer installs the program and launches spotube and closes
8. The update notice still remains there

### Operating System

Windows 10

### Spotube version

v3.7.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Halbour** [comment] 2024-07-19 08:53
Happening to me too.

**Comment by Alanjaow** [comment] 2024-07-21 16:43
I just tried uninstalling and installing from the 3.7.1 installer, and it still shows the same message. Doing the same thing with the nightly version resulted in no update message, but a version number of 1.0.0 in the settings (I would presume that's normal).

**Comment by FlameGrowl-wq** [comment] 2024-07-21 19:41
same

**Comment by abyssalx** [comment] 2024-07-25 07:21
I'm experiencing the same issue. WinGet even reports that there's an update. However, even after upgrading via WinGet, while Spotube reports itself as version 3.7.0, WinGet reports the installed version as 3.7.1+32, with update to version 3.7.1 available.

**Comment by Fennecai** [comment] 2024-07-26 17:35
same here.

i think the problem is that wherever all the update links point to, has the wrong version. they need to change the file at that address to be the correct one.

**Comment by Wendiga** [comment] 2024-07-27 00:22
Same... tried web, repo, and winget

**Comment by thane-k** [comment] 2024-08-09 10:56
this happens to me; except i think there is a phantom part of the program somewhere installed that persists for one reason or another.

i uninstalled the app from windows settings, and reinstalled from a second download, both from the website (and later from this github release file).
not only does it not update to 3.7.1, but it seems as though nothing changed at all. all downloads, search history, even most recently played song, are all untouched.

so my theory is that this data most likely is staying somewhere on the system, and for one reason/s or another, ignores all attempts i've (and a few others) made, which maybe means the new version can't replace a program that is already installed.

windows 10, installed from firefox developer's edition, happy to provide any other techni-details if anyone with the relevant skills can look into this

**Comment by KRTirtho** [comment] 2024-08-11 14:31
This has been fixed in 3.8.0

**Closed by KRTirtho** 2024-08-11 14:31 UTC
Labels: bug
