### ISSUE TITLE
Performance issue: Too high CPU usage

### ISSUE THREAD

**Issue by systemoperator** [KRTirtho/spotube#507] opened 2023-05-07 17:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When starting Spotube without playing music, it permanently consumes 80 to 86% CPU.
When playing music, it permanently consumes 80 to 107% CPU.

### Expected Behavior

Much less CPU usage.

### Steps to reproduce

1. open app.
2. optionally, play music.

### Operating System

Linux Debian 11, 64-bit, Mate desktop

### Spotube version

2.7.1

### Installation source

Flathub (Flatpak)

**Comment by karniv00l** [comment] 2023-05-08 12:06
Just my 2 cents - it clearly re-renders when it shouldn't, there's almost nothing in the UI and still it uses substantial amount of CPU and GPU

<img width="1597" alt="Screenshot 2023-05-08 at 14 04 45" src="https://user-images.githubusercontent.com/3144291/236819265-d3a95d7c-759e-45a2-b42d-e608b5e8b3fe.png">

**Comment by megamorf** [comment] 2023-06-23 13:53
I can confirm this is also affecting me - M1 MacBook Pro. Energy consumption of the program far exceeds everything else on the system (2nd column = energy demand):
![image](https://github.com/KRTirtho/spotube/assets/1732128/90e71f57-261a-41ed-96a7-e335928506e6)

**Comment by KRTirtho** [comment] 2023-06-23 15:41
That's been fixed already. Check out the nightly release?

**Comment by karniv00l** [comment] 2023-07-03 07:32
@KRTirtho still an issue

I've removed all the widgets in the [player_controls.dart](https://github.com/KRTirtho/spotube/blob/master/lib/components/player/player_controls.dart) and narrowed it down to this line: https://github.com/KRTirtho/spotube/blob/master/lib/components/player/player_controls.dart#L51

but, that's without anything rendered, so there's still an issue with the current widget tree

**Comment by RaptaG** [comment] 2023-07-03 10:54
Using 3.0.0 from Flathub on Fedora Kinoite 38, I cannot reproduce such a high CPU usage

**Comment by KRTirtho** [comment] 2023-07-04 04:28
Even `RepaintBoundary` doesn't fix it :thinking: 
But `bufferingStream` is not even a real stream. It's there for compatibility reasons only
https://github.com/KRTirtho/spotube/blob/master/lib/services/audio_player/audio_players_streams_mixin.dart#L92-L104

**Comment by dimitris-personal** [comment] 2023-07-12 15:43
I can reproduce here, Fedora 38/GNOME/Wayland/flathub.

Without any song playing:

![Screenshot from 2023-07-12 08-41-42](https://github.com/KRTirtho/spotube/assets/109622940/f1f671ad-560c-4565-a1cc-1843db8a98e8)

**Comment by Playit3110** [comment] 2023-07-30 20:41
Under Win10 with Spotube v3.0.0 it is the same
![grafik](https://github.com/KRTirtho/spotube/assets/38607319/a0ee3c67-5e62-4e4b-915b-d1d560152933)

I think its some memory leak as well. Dont know if you keep all data after playing a song or if it is removed from ram and maybe stored in storage, but this is ridiculous.

**Comment by karniv00l** [comment] 2023-08-01 08:36
Possible fix in #606

**Comment by KRTirtho** [comment] 2023-08-02 11:16
I think we safely say it's fixed now. Thanks to @karniv00l :rocket:

**Comment by KRTirtho** [comment] 2023-08-05 02:34
The fix is now available on v3.0.1
Please check if it works

**Closed** 2023-08-26 07:09 UTC
Labels: bug
