### ISSUE TITLE
Spotube doesn't always use the right version of the song from Youtube

### ISSUE THREAD

**Issue by Ocean-OS** [KRTirtho/spotube#1132] opened 2024-01-23 17:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Oftentimes, I select a song and when it plays, it plays a live version or a cover of the song. For example, listening to "Dirty Harry" by the Gorillaz on the Windows app plays a live concert version, instead of the album version.

### Suggested solution

My solution is a feature that allows listeners to add and vote for requests to set a YouTube URL to always be chosen to play for the song. So, if the song you selected is not the one that plays, you can press a button that lists any requests to change the URL that Spotube fetches from for the song, and you would be able to make new requests, and vote for any available requests. If the amount of votes reaches a certain percentage of people that listen to the song, then the new URL is set to always be used when the song is selected. 

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-01-23 17:54
Duplicate of #883

**Comment by KRTirtho** [comment] 2024-01-23 17:55
@Ocean-OS That's an awesome idea but to keep the conversation in the same place please submit your idea in the original issue thread. Thanks ❤️

**Closed by KRTirtho** 2024-01-23 17:54 UTC
Labels: enhancement
