### ISSUE TITLE
Autheentication Failure

### ISSUE THREAD

**Issue by feketefh** [KRTirtho/spotube#1872] opened 2024-09-12 05:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i start the app it sais this:

**Error Authentication Failure**
type 'string' is not subtype ot the 'int'  of 'index'

### Expected Behavior

When i start he app it just not showing any errors

### Steps to reproduce

1. Just open the app

### Operating System

Android

### Spotube version

3.8.0

### Installation source

F-Droid (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by MrPrezAtambaev** [comment] 2024-09-12 05:35
In link with https://github.com/KRTirtho/spotube/issues/1867 I think

**Comment by KRTirtho** [comment] 2024-09-15 04:01
Duplicate of #1867

**Closed** 2024-09-15 04:01 UTC
Labels: bug
