### ISSUE TITLE
[Feature] Install with brew

### ISSUE THREAD

**Issue by louisabraham** [KRTirtho/spotube#409] opened 2023-02-10 14:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

Unable to categorize

### Credits

me

### Pain

installing and updating on macOS

### Suggested Solution

propose installation through https://brew.sh/

**Comment by KRTirtho** [comment] 2023-02-10 15:58
Duplicate of https://github.com/KRTirtho/spotube/issues/120

**Closed by KRTirtho** 2023-02-10 15:58 UTC
Labels: enhancement, good first issue
