### ISSUE TITLE
Cannot download the whole playlist

### ISSUE THREAD

**Issue by shiquda** [KRTirtho/spotube#1970] opened 2024-10-06 14:36 UTC
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

When I click the "More actions" of a playlist, the download button is unclickable. However, a single song can be downloaded. These both happened on Windows 11 and Android. 

![PixPin_2024-10-06_22-26-55](https://github.com/user-attachments/assets/07c3e240-ad28-4f8c-9cf7-1dca9c828d06)

### Expected Behavior

The playlist should be downloadable.

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

Windows 11 & Android 14

### Spotube version

v3.8.2

### Installation source

GitHub Releases (Binary), Play Store (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-10-13 05:22
Duplicate of #1456

**Closed** 2024-10-13 05:22 UTC
Labels: bug, duplicate

**Comment by KRTirtho** [comment] 2024-10-13 05:24
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues

![image](https://github.com/user-attachments/assets/161637ef-7f9b-4f9e-a26a-1764ca23ea0d)

**Comment by KRTirtho** [comment] 2024-10-13 05:25
Btw, after full playlist loads, you've to select all the tracks, then the download button will appear

**Comment by shiquda** [comment] 2024-10-13 05:30
> Btw, after full playlist loads, you've to select all the tracks, then the download button will be enabled/tappable

Sorry, I don't see that select button.

**Comment by Jayjetlee** [comment] 2025-03-28 03:54
Any idea how to fix ?
