### ISSUE TITLE
Problem: conflicting requests   - nothing provides libmpv.so.1()(64bit) needed by spotube-3.5.0+29-29.x86_64 from @commandline

### ISSUE THREAD

**Issue by rznkolds** [KRTirtho/spotube#1371] opened 2024-04-02 17:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to install the spotube rpm package but gnome store states error in title

### Expected Behavior

It needs to be installed in a healthy way.

### Steps to reproduce

1.

I download this file from github releases section:

spotube-linux-x86_64.rpm

2.

I run the file on the sudo dnf install command with rpm.

3. 

I get the error below:

Error:
  Problem: conflicting requests
   - nothing provides libmpv.so.1()(64bit) needed by spotube-3.5.0+29-29.x86_64 from @commandline

### Operating System

Linux

### Spotube version

v3.5.0

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-04-04 16:33
Duplicate of #929

**Closed by KRTirtho** 2024-04-04 16:33 UTC
Labels: bug, duplicate

**Comment by universish** [comment] 2024-10-07 15:42
@rznkolds Is your operating system fedora 40? Is your processor architecture aarch64 or x86_64?

**Comment by rznkolds** [comment] 2024-10-07 17:47
> @rznkolds Is your operating system fedora 40? Is your processor architecture aarch64 or x86_64?

Fedpora 40 and x86_64

**Comment by universish** [comment] 2024-10-10 18:44
@KRTirtho , the error is not related to aarch64, is not #929  .
error is related to x86_64. Do not close the topic.
#1580 #1931
