### ISSUE TITLE
Wrong song being played when selected from the search queue

### ISSUE THREAD

**Issue by peimansh** [KRTirtho/spotube#1175] opened 2024-01-29 13:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I search for a song e.g. "Ba tamoome yek deli" from the artist "Shadmehr Aghili" and the search results show the correct song with correct title and artist. The duration of the song is 4:32 . But when I click on it to be played, another song from the same artist is played and different duration. So it shows the correct title and correct artist, but a different song is played.
![Screenshot 2024-01-29 135632](https://github.com/KRTirtho/spotube/assets/32059257/0bf5e948-f9d1-4423-b52d-943e927185fe)

### Expected Behavior

To play the correct song as it is shown in the search results.

### Steps to reproduce

1. Open the app
2. Search for the song "Ba tamoome yek deli"
3. Click on the first song in the results list: "Ba tamoome yek deli" from artist "Shadmehr Aghili" , Duration "4:32"
4. A different wrong song but from the same artist gets played, which in my case has a duration of "6:35"

### Operating System

Windows

### Spotube version

v3.4.1

### Installation source

GitHub Releases (Binary)

### Additional information

I've attached the screenshot which is very self-describing :)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by olivier2** [comment] 2024-01-30 02:44
Hi @peimansh, just started looking into the code to understand the inner working of Spotube! Looks like there's a general misunderstanding of how the app works.

Spotube finds and display data using the Spotify api, but when you press play, it tries to find the track on youtube. In your case, the youtube track that is found is this : https://www.youtube.com/watch?v=wOJfPgTgKwU

More info can be found in these (and many more issues): #963  #883

**Comment by ksaadDE** [comment] 2024-02-05 02:07
> but when you press play, it tries to find the track on youtube
and we users can change it by clicking in the lower right corner and changing the selected YT video stream.

Yup, that experience is a little annoying. Especially if you go in the search and try to find a song that is on YouTube but not on Spotify and vice versa. (Another issue that is related to it) 

So it's not a bug it's a feature guys :DD

**Comment by peimansh** [comment] 2024-02-05 12:21
I think this is a marketing thing !
How to present a "bug" to the customer so that it seems like a "feature" 😄

**Comment by UnoNYC** [comment] 2024-02-12 16:34
Hi, I have a very similar issue. Except Spotify has the actual song in question and it plays normally but in spotube, it plays the audio from a long unrelated video..

For example, if you were to search for "The Last Concorde - Stars" in Spotify, you would get the song from this video.

https://www.youtube.com/watch?v=pHJ0l_pHpV8

And in Spotify, it would play the song above.

But in Spotube, although you get the artist and album listing for the song, if you were to play it, then you would get the audio from this video.

https://www.youtube.com/watch?v=FnxX5a08x38

I have tried the option for alternative sources and got the song, but it will still play the audio above the next time I use the app. It never remembers my choice and I can't even blacklist the hour long video or the other unrelated ones.

The song and album in question exists on Spotify though.

https://open.spotify.com/track/7eQ4iJIDagsb2OPLakmIeF

This happens on both Windows and Android.

**Comment by KRTirtho** [comment] 2024-04-11 08:53
Duplicate of #883

**Closed by KRTirtho** 2024-04-11 08:53 UTC
Labels: bug
