### ISSUE TITLE
Save different youtube search locally to phone, so that it plays that instead on playback

### ISSUE THREAD

**Issue by Sowden** [KRTirtho/spotube#1862] opened 2024-09-08 00:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

If a song comes up and the automatic search finds the music video (that starts different than from the track), I can do a search to find a different youtube link of the song and play it.  But on a playback, the song loads the music video again.

### Suggested solution

Could there be a way to list the researched song, save it locally to the phone, and have it play that next time it comes up on a playlist?

### Useful resources

Maybe have a XML file locally that saves the link attached to the song info.  Not sure, but that's an idea

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-09-15 04:24
Duplicate of #1223

**Comment by KRTirtho** [comment] 2024-09-15 04:25
It's been implemented long time ago and had some bugs which has been fixed in the last version

**Comment by Sowden** [comment] 2024-09-16 04:43
Oh holy cow.  I just updated the Android app and it works.  Thank you so much!

**Closed** 2024-12-08 14:11 UTC
Labels: duplicate, enhancement
