### ISSUE TITLE
Playing random songs instead of the actual song information it is displaying

### ISSUE THREAD

**Issue by mubareksd** [KRTirtho/spotube#1587] opened 2024-06-07 16:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Instead of playing the song that the information is says is playing, but it plays Indian music instead of the actual song.

### Expected Behavior

Play the actual song that it says is being played

### Steps to reproduce

1. I opened the app
2. I choose a playlist and press play
3. After about 3 songs it starts playing some random Indian music instead of the actual song the information says is playing

### Operating System

Android

### Spotube version

V3.7.1

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by s-b-repo** [comment] 2024-06-07 23:12
this happens cause of youtube a song i know got deleted by creator but is reuploaded

**Comment by s-b-repo** [comment] 2024-06-07 23:12
using metadata for finding song on youtube might help

**Comment by KRTirtho** [comment] 2024-07-09 14:18
Duplicate of #883

**Closed by KRTirtho** 2024-07-09 14:18 UTC
Labels: bug
