### ISSUE TITLE
Unable to open spotube 3.71 on my windows 11

### ISSUE THREAD

**Issue by Rahulguggilam2003** [KRTirtho/spotube#1663] opened 2024-06-24 06:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No window has been opened when i click on the app

### Expected Behavior

The app should open when i click on it

### Steps to reproduce

1. click on the app
2. no window has been poped up

### Operating System

windows

### Spotube version

3.7.1

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by csamolot** [comment] 2024-06-24 20:03
Same here. It opened once last week and now it doesn't open at all. Tried uninstalling and reinstalling it

**Comment by vathesen** [comment] 2024-06-25 12:18
A mi tampoco me abre la aplicación. Creí que era un error al actualizar. Desinstale varias veces borrando todos los archivos de registros. Instale nuevamente la versión 3.71 y no hace nada, solo toma la ubicación. Volveré a versiones anteriores. Aunque se que la 3.70 tenia problemas con el tamaño de la ventana. Uso Windows 10. 

The application doesn't open for me either. I thought it was an error when updating. Uninstall multiple times deleting all log files. Install version 3.71 again and it does nothing, just grabs the location. I'll go back to previous versions. Although I know that 3.70 had problems with the window size. I use Windows 10.

**Comment by vathesen** [comment] 2024-06-25 12:58
> @vathesen you can use version 3.6 in any platform it doesn't have any issues I think so

I just installed version 3.70 and it works perfectly at the moment.

**Comment by slamp** [comment] 2024-06-25 20:34
On my system, the version 3.7.1 (Spotube-windows-x86_64-setup.exe) is blocked as 'Potentially unwanted app'
Detected: PAU:Win32/Packunwan

**Comment by coder0107git** [comment] 2024-06-28 21:56
Duplicate of #1620

**Comment by the-vicious** [comment] 2024-07-11 10:29
3.50 version worked for me

**Closed** 2024-07-11 14:59 UTC
Labels: bug, duplicate
