### ISSUE TITLE
GUI freezes upon selecting "Add to playlist" from right-click menu

### ISSUE THREAD

**Issue by tangje99** [KRTirtho/spotube#820] opened 2023-10-18 08:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When viewing an album/playlist, right-clicking a song, and selecting "Add to playlist" from the menu, the Spotube GUI will freeze completely. 

Queue will continue playing in the background. However, the GUI ceases to respond to any input, and I have to force-quit and restart the application. This issue does not occur for other menu items.

### Expected Behavior

I expected that selecting "Add to playlist" would pull up the dialog to select which playlist to add the selected song to. If an error occurred, I would expect an error message to display, as this functionality exists elsewhere as well. I understand that having a helpful error message is not always the top development priority, however. 

### Steps to reproduce

Go to a playlist or album. Right click a song. Click "Add to playlist." The GUI will freeze with "Add to playlist" highlighted and the right-click menu still present. GUI will not respond to any further input.

### Operating System

macOS (MacBook Pro, Catalina v 10.15.7)

### Spotube version

v3.2.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Additional information

Kingkor Roy Tirtho was able to reproduce the error. 

The error logs have been copied below: 

(Below error message is given before the Catcher 2 Log section)
`PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)`

(Below messages are given in the Catcher 2 Log section)
```
------- APP INFO -------
environment: release
version: 3.2.0
appName: spotube
buildNumber: 25
packageName: oss.krtirtho.spotube
```

This error also seems to crop up frequently in the logs regarding this issue: 
```
---------- ERROR ----------
[MediaKitError] 
Option af: dynaudnor
```

**Comment by ZenKyma** [comment] 2023-10-19 12:19
Reproduced for linux flatpak version 3.2.0 in search view. Gui ceases to repond and window is not even closable on ubuntu 23.04.

**Comment by M-Jigar** [comment] 2023-10-23 04:40
Similar bug on Windows 11, GUI freeze with a crazy spike in ram usage, almost 10GB.

![image](https://github.com/KRTirtho/spotube/assets/98579634/6b523d55-6570-405c-825d-c8894a2d52b6)

**Comment by m4nges** [comment] 2023-10-24 08:52
Deactivating "Synchronise album colour" solved the problem for me.

**Comment by ethical-haquer** [comment] 2023-10-26 02:27
I'm able to reproduce this on Android 13, Spotube v3.2.0.

**Comment by hackerb9** [comment] 2023-10-31 16:43
I can confirm this bug for Android 14 (GrapheneOS on Pixel 6 Pro). 

When Spotube hangs, the only way to restart it is to first Force Stop the app. (From launcher, long press Spotube icon, select App Info, choose Force Stop).

![Image](https://github.com/KRTirtho/spotube/assets/10174223/948d9da9-38cc-4b96-9c71-56c0469cc49b)

**Comment by Phaelkyn** [comment] 2023-11-07 16:15
I also can replicate this behavior on Manjaro Linux. In addition, my entire OS becomes frozen and requires a full reboot. 
``============================== CATCHER 2 LOG ==============================
Crash occurred on 2023-11-02 15:01:03.697577

------- DEVICE INFO -------
name: Manjaro Linux
version: null
id: manjaro
idLike: [arch]
versionCodename: Uranos
versionId: 23.0.4
prettyName: Manjaro Linux
buildId: rolling
variant: null
variantId: null
machineId: ee181aff6a2047f2a244024b5f7bxxxx

------- APP INFO -------
environment: release
version: 3.2.0
appName: spotube
buildNumber: 25
packageName: spotube

---------- ERROR ----------
Bad state: No element

------- STACK TRACE -------
#0      List.first (dart:core-patch/growable_array.dart:343)
#1      ProxyPlaylistNotifier.load (package:spotube/provider/proxy_playlist/proxy_playlist_provider.dart:307)
#2      AlbumCard.build.<anonymous closure> (package:spotube/components/album/album_card.dart:70)
#3      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311)
#7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:244)
#8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:630)
#9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98)
#10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143)
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625)
#12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141)
#13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127)
#14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488)
#15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468)
#16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:333)
#17     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413)
#18     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376)
#19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323)
#20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292)
#21     _invoke1 (dart:ui/hooks.dart:186)
#22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:424)
#23     _dispatchPointerDataPacket (dart:ui/hooks.dart:119)

------- CUSTOM INFO -------
======================================================================
[2023-11-02 16:52:17.758787]
PostgrestException(message: duplicate key value violates unique constraint "tracks_youtube_id_spotify_id_idx", code: 23505, details: Conflict, hint: null)
null``

**Comment by KRTirtho** [comment] 2023-11-07 16:18
Duplicate of https://github.com/KRTirtho/spotube/issues/820

**Closed by KRTirtho** 2023-11-07 16:18 UTC
Labels: bug, duplicate
