### ISSUE TITLE
Android Auto

### ISSUE THREAD

**Issue by theguyom** [KRTirtho/spotube#1030] opened 2024-01-06 13:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Hi,
Could you add the support of Android Auto to the Android version?

### Suggested solution

Support of Android Auto : https://developer.android.com/training/cars/media/auto?hl=en

**Comment by KRTirtho** [comment] 2024-01-08 04:52
Duplicate of #623

**Closed by KRTirtho** 2024-01-08 04:52 UTC
Labels: enhancement
