### ISSUE TITLE
Find other versions of same song

### ISSUE THREAD

**Issue by Annie-G** [KRTirtho/spotube#1374] opened 2024-04-04 10:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I'm just a simple user of the app with no further understanding how it works, but I hope someone can help me: Some songs have extremely poor sound quality, some turn out to be poor recordings from live shows. While I definitely know there are other, good quality versions of that song available on spotify and YouTube, I can't find other versions of the song with the Spotube search. No matter which audio source I choose, I only find the same version of the song with the same poor quality. 

### Suggested solution

Allow searching other versions of the same song so one can kick the poor quality from s playlist and replace it with a proper version. 

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by OpenCode** [comment] 2024-04-04 13:43
![2024-04-04_15-42](https://github.com/KRTirtho/spotube/assets/265697/2d78f101-26fa-41cc-a83d-c0d766911d7a)

When you're listening a song, there is an icon that you can select to choose an alternative source for the song

**Comment by Annie-G** [comment] 2024-04-04 15:21
Hi! I can't find that icon in the Android App. Can you help me find it? I just started the poor quality song from my playlist and there is a menu with several options, but it doesn't include changing the audio source.

**Comment by OpenCode** [comment] 2024-04-04 15:26
> Hi! I can't find that icon in the Android App. Can you help me find it? I just started the poor quality song from my playlist and there is a menu with several options, but it doesn't include changing the audio source.

I don't know i it's possible to change source in the mobile app. I don't use it. But you can check if in you configuration you have the "Audio Quality" setted on "High" and you can try to change the "Streaming Musical Codec" to "M4a"

**Comment by Annie-G** [comment] 2024-04-04 15:35
I already had audio quality on high (and most songs are high quality, there are just a few where someone must have uploaded crap to YouTube). I have now changed the Streaming Music Codec to "MP4", even though the app says the other one is recommended for streaming music. But the song is still played in the same version that has crackling, little gaps from CD scratches and random changes in volume.
I use the Android app only, I have no need for a music player on my laptop, so I can only work with what the Android app can do.

**Comment by Annie-G** [comment] 2024-04-04 16:12
I found the function for picking an alternative source for a current track. It exists in the Android app. When I tap it, I am shown an option for an alternative audio source for this song. However, when I tap that alternative source, there is absolutely no reaction. Nothing happens. So I guess now this is becoming a bug issue.
![Screenshot_2024-04-04-18-10-59-42_1c96baa6fc3a4338d23fd334c3c04599](https://github.com/KRTirtho/spotube/assets/70524783/d9d94f95-1ddb-4ed4-9cff-4705e2babd8e)

**Comment by Annie-G** [comment] 2024-04-04 16:29
Now I get it: "energeticmonkey" is the only source available for this song. That's why nothing happens when I tap it. Too bad "engeticmonkey" sucks real bad at sound quality. 
I don't understand why, when I go to YouTube, where "energeticmonkey" is providing poor quality Skunk Anansie songs, I can easily find numerous other sources for that song. How come those can't be accessed as a source for that track on Spotube?

**Comment by KRTirtho** [comment] 2024-04-04 16:39
You can use the search button to find more sources for that particular track

**Comment by Annie-G** [comment] 2024-04-04 16:43
I've tried that and it seems there are none to be found in Spotube. Which is frustrating because YouTube has about 10 versions of that track if I search directly there.

**Comment by KRTirtho** [comment] 2024-04-04 16:44
<img width="1143" alt="image" src="https://github.com/KRTirtho/spotube/assets/61944859/01d1a9fe-f9f8-48a2-a651-c9c52af9b00f">

<img width="1143" alt="image" src="https://github.com/KRTirtho/spotube/assets/61944859/986a7af3-4e30-43c2-833a-8d64202dc7a4">

**Comment by KRTirtho** [comment] 2024-04-04 16:49
You can also use "Settings" >> "Audio Source" and select "JioSaavn" which has a higher bitrate (320kbps mp4) than youtube music. But it has less songs so..

**Comment by Annie-G** [comment] 2024-04-04 16:51
OMG thank you! I didn't see that tiny search icon in the corner and now I got results! Thanks, now I can replace the source. I suppose if the whole album is bad sound quality, I'll have to do this to each song individually, right? Or is there an option for me to generally prefer that other source over everything provided by "electricmonkey"?

**Comment by KRTirtho** [comment] 2024-04-04 16:53
If you select `JioSaavn`  from Settings it'll be applied for every song. But the _"Alternative Track Source"_ is for individual tracks.

**Comment by KRTirtho** [comment] 2024-04-04 16:55
Btw your situation is similar to the issue #883 
Follow that thread for improvments. But I doubt if this will ever be fixed unless we directly get the audio from Spotify (which is not possible now)

**Comment by KRTirtho** [comment] 2024-04-04 16:55
Duplicate of #883

**Closed** 2024-04-04 16:55 UTC
Labels: duplicate, enhancement

**Comment by Annie-G** [comment] 2024-04-04 16:58
> If you select `JioSaavn` from Settings it'll be applied for every song. But the _"Alternative Track Source"_ is for individual tracks.

Funny, I tried that and then I still heard the exact same version of the song I heard with YouTube as audio source. I found that surprising, but it literally had exactly the same crackling sounds and gaps.
