### ISSUE TITLE
Youtube audio source picks the wrong songs from piped

### ISSUE THREAD

**Issue by Zyanbob** [KRTirtho/spotube#1134] opened 2024-01-24 01:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i listen to You do you by zayde wolf on spotube i hear the line "well it's a good thing mystery is my middle name" a line that isn't in the original song. i go to check the source and where it say youtube the source is PIPED.VIDEO and the song is actually an amv of BARRY ALLEN AND RALPH DIPBY TALKING OVER THE SONG!! When i the pokemon theme xy from natewantstobattle i get a cover verison of the original theme from amalee with natewantstobattle in it instead of the x and y version WHICH IS ALSO ON PIPED EVEN THOSE THE DEFAULT IS YOUTUBE!       

### Expected Behavior

you do you to play this:https://www.youtube.com/watch?v=YcJ1HdyJ_Ew and pokemon theme to play this: https://www.youtube.com/watch?v=p7YT2VnGcJE

### Steps to reproduce

1.search you do you or pokemon theme nate 2. click on the details button 

### Operating System

Android 

### Spotube version

v3.4.0

### Installation source

Play Store (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-01-24 04:26
Duplicate of #883

**Closed by KRTirtho** 2024-01-24 04:26 UTC
Labels: bug
