### ISSUE TITLE
Wrong audio played on my spotify track

### ISSUE THREAD

**Issue by acantepie** [KRTirtho/spotube#1095] opened 2024-01-22 00:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After logged on my spotify account, the first two tracks of my playlist have right information but the audio played is not the right one

Url of playlist : https://open.spotify.com/playlist/7EtiSLKUiHY7vmJ7SikOaj?si=828fb5d0322b437e

Track one : 
> Title : The Leftlovers Piano Theme
> Artist : Geek music
> Album : The Leflovers Piano Theme
> Time : 3:07

Audio played : a piano mario theme song ...

Track two : 
> Title : Leftlovers
> Artist : Dennis Lloyd
> Album : Leflovers 
> Time : 3:12

Audio played : a live of metal concert ...

Wtf ..

### Expected Behavior

The right audio is played 

### Steps to reproduce

1. Log with a spotify account which has previously added this playlist : https://open.spotify.com/playlist/7EtiSLKUiHY7vmJ7SikOaj?si=828fb5d0322b437e
2. Play the first 2 tracks of playlist (haven't test all track of my library)

### Operating System

Windows 11

### Spotube version

idk. The last one

### Installation source

GitHub Releases (Binary)

### Additional information

Installed from url provided by this repo (binary).

**Comment by KRTirtho** [comment] 2024-01-22 03:03
This is generally a limitation of Spotube as it can't match 100% all the time. See #883 , #737 etc

**Comment by KRTirtho** [comment] 2024-01-22 03:04
Duplicate of #883

**Closed by KRTirtho** 2024-01-22 03:04 UTC
Labels: bug, duplicate

**Comment by acantepie** [comment] 2024-01-22 09:11
> This is generally a limitation of Spotube as it can't match 100% all the time. See #883 , #737 etc
Hi,
This is wierd, i have developed a software to donwload music of spotify using youtube api music (search with fuziness).
You can take a look at my repo : https://github.com/acantepie/opusify?tab=readme-ov-file

I think there is something wrong with your search algorithm

**Comment by KRTirtho** [comment] 2024-01-22 10:00
Judging your porject it seems to be using youtube-dl which is a huge project written in python and since python is an interpreted language, their huge algorithm can't be linked with flutter (dart) through FFI. 

It's doable but not practical as we've to ship the embedded python interpreter with Spotube. The best solution is probably porting that library. But that'll take a huge amount of work, and I don't see anyone (including me) put that much work.

I welcome who can port youtube-dl to dart in Dart. Although, Spotube only requires the search and match part. Which might be not as big as I'm guessing

**Comment by acantepie** [comment] 2024-01-22 18:04
Hi, the search is only handled by this python script i made : https://github.com/acantepie/opusify/blob/main/src/youtube-dl/YoutubeSearch.py. This script uses this library https://ytmusicapi.readthedocs.io/en/stable to find the best match and retrieve a youtubeId

Unfortunalty there is no official api for yt music but mb there is a port of this library on Dart 👍
