### ISSUE TITLE
Cache songs instead of downloading externally.

### ISSUE THREAD

**Issue by devanarayanan44** [KRTirtho/spotube#709] opened 2023-09-10 14:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

If I download a song and play it from the artist page or from a playlist, it plays online. I can't view the lyrics of downloaded tracks. 
I can't go to the album or artist from the downloaded tracks.

### Suggested solution

Cache the songs (like inner tune) and add a separate option for downloading externally.

**Comment by KRTirtho** [comment] 2023-09-10 15:22
Does caching music really make sense?
Most of the users doesn't listen to the same song twice in a day (or even weeks) without special reason. So if we cache songs (save them on the storage) we also must need to set a custom cache limit after which old songs will get removed
So if songs are getting added constantly & old ones are getting removed to make space then is there any point of caching here?
We're doing nothing but wasting space in glorified way. Which official Spotify app does a lot btw (over 2-3GB occupied cache space)

> Btw caching song is a really tough thing to implement & time consuming (implementation for each platform)

**Comment by ZenKyma** [comment] 2023-09-11 09:55
I assume the idea is to have a button to make tracks available offline (apart from download) for listening through spotube and enjoying the lyrics, by caching the respective content.
The problem of a cache limit would be eliminated if the user has to manage his cached content himself, e.g. through the respective button, a more advanced option would be a 'cached-content' interface.

Actually this was the behaviour I also expected when first seeing the download option.

**Comment by devanarayanan44** [comment] 2023-09-11 11:17
> I assume the idea is to have a button to make tracks available offline



> I assume the idea is to have a button to make tracks available offline (apart from download) for listening through spotube

Exactly.

**Comment by siggi1984** [comment] 2023-09-13 08:54
> Does caching music really make sense? Most of the users doesn't listen to the same song twice in a day (or even weeks) without special reason. So if we cache songs (save them on the storage) we also must need to set a custom cache limit after which old songs will get removed So if songs are getting added constantly & old ones are getting removed to make space then is there any point of caching here? We're doing nothing but wasting space in glorified way. Which official Spotify app does a lot btw (over 2-3GB occupied cache space)
> 
> > Btw caching song is a really tough thing to implement & time consuming (implementation for each platform)

A song cache function would be very useful and helpful. I would be very happy about such a function.

**Comment by AozoraDev** [comment] 2023-09-15 18:25
Caching is probably useful, since i'm always listening to my Liked Tracks....
I mean... i know i can use mass download but it's kind of  pain in the ass imo.

**Comment by OmG3r** [comment] 2023-10-19 13:37
an alternative/enhancement is to simply offer a setting to download all songs you listen to by default, songs will be available in the download specified

**Comment by KRTirtho** [comment] 2024-07-09 12:57
It's actually somewhat possible now since spotube now uses a custom streaming proxy inside the app, so we could cache the stream in file. It might occupy more storage.

**Comment by siggi1984** [comment] 2024-07-10 04:50
> It's actually somewhat possible now since spotube now uses a custom streaming proxy inside the app, so we could cache the stream in file. It might occupy more storage.

Does that mean that the songs you listen to are saved and can be played offline the next time you play them? That would be great and would save mobile data for those who don't have that much.

**Comment by KRTirtho** [comment] 2024-08-13 16:52
Duplicate of #709 

Can't believe there's been a parent issue all this time

**Closed** 2024-08-13 16:52 UTC
Labels: duplicate, enhancement
