### ISSUE TITLE
Windows defender reports Wacatac.B!ml

### ISSUE THREAD

**Issue by Donnervogel** [KRTirtho/spotube#1897] opened 2024-09-18 21:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

windows defender detects the smtc_windows.dll as the Wacatac.B!ml Trojan.

### Expected Behavior

not beeing detected as a virus

### Steps to reproduce

1. I installed the app and let the installer launch the app after install
2. Windows defender pops up

### Operating System

Windows

### Spotube version

v3.8.1

### Installation source

Website (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-09-19 14:43
Duplicate of #1894

**Closed by KRTirtho** 2024-09-19 14:43 UTC
Labels: bug
