### ISSUE TITLE
The song lyrics do not display correctly when I open Ukrainian songs

### ISSUE THREAD

**Issue by Vitalii-code** [KRTirtho/spotube#1534] opened 2024-05-26 20:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The song lyrics do not display correctly when I open Ukrainian songs

### Expected Behavior

The lyrics of Ukrainian songs should be displayed correctly

### Steps to reproduce

1. I opened this song [link](https://open.spotify.com/track/2rJDC0Kvchi51ZRs2TLokP?si=42dfb26e525b45ad) in spotube
2. Press the Lyrics button
3. Random symbols on screen

### Operating System

Android 14

### Spotube version

nightly build number: 278

### Installation source

GitHub Actions (Nightly Binary)

### Additional information

![Screenshot_20240526-211919](https://github.com/KRTirtho/spotube/assets/58048618/d4924078-235d-4e1f-a4eb-86ac590fd333)

### Self grab

- [X] I'm ready to work on this issue!

**Comment by singhh9596** [comment] 2024-05-31 05:33
+1. Facing the same issue while playing hindi songs.

**Comment by Vitalii-code** [comment] 2024-05-31 08:39
I will try to fix the bug, but I can't even compile the app for now.

**Comment by KRTirtho** [comment] 2024-06-01 05:45
Duplicate of #1463

**Closed by KRTirtho** 2024-06-01 05:45 UTC
Labels: bug
