### ISSUE TITLE
There is a song links problem in Spotube

### ISSUE THREAD

**Issue by Francisco1asir** [KRTirtho/spotube#1754] opened 2024-08-02 09:41 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Hi there! Is simple, when i reproducing some songs (expecially the song "Moscow Mule - Bad Bunny") Spotube dont reproduce the original song however reproduce a english cover of the song, i know i can change the song link but is not permanent, when i play it later it's still bad, the app show that the artist is "Bad Bunny" but the artist is wrong too, i try to change the youtube link and creating new page or something here - https://song.link/i/1622045625 - but dont work, also i tried download the song from youtube and putting it in my mobile local storage and i can hear the original song but there is another problem because the songs that you download cant be introduce in song lists, i will love that this problem can be fixed or something, updating the links, allow to the users update the links or when you change the youtube link  i would like the link be change forever in my account. I think could be more easy allow the downloaded songs can be introduced in song list.

Thank you :D

### Expected Behavior

I hope that the song links can be update forever or something

### Steps to reproduce

1.- Open the app
2.- Select the song "Moscow Mule - Bad Bunny"
3.- Change the song link in the app
4.- Reproduce another song and reproduce Moscow Mule again and see the link is not change forever
5.- Cry :c

### Operating System

Android

### Spotube version

v3.7.1

### Installation source

Play Store (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by MMachado05** [comment] 2024-08-02 20:07
I was about to write a bug report for something similar; Spotube should likely "prioritize" whatever user-set source is provided in perpetuity, so that playing a new song doesn't suddenly return the original song to its incorrect source.

**Comment by BloodFeral** [comment] 2024-08-05 11:52
same error buddy, this is so annoying i usually use spotube when i drive and here a song that is not the correct song and i dont like it, like @Francisco1asir say should exist a permanent change when you change the link song ._.

**Comment by KRTirtho** [comment] 2024-08-11 14:19
Duplicate of #1223

**Closed** 2024-08-11 14:21 UTC
Labels: bug, duplicate
