### ISSUE TITLE
Doesn't play the song I have chosen 

### ISSUE THREAD

**Issue by aydogduonur** [KRTirtho/spotube#1895] opened 2024-09-18 13:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The application doesn't play the song I wanted it to play. It was working correctly in the previous version of the app, v3.8.0, but seems like the issue is back at it again. 

### Expected Behavior

App should have played the song I have chosen. 

### Steps to reproduce

1. I opened the app. 
2. I clicked on a song that I already knew how the song is like. 
3. It played a very absurd song that I think no person ever knew before. 

### Operating System

Android 13

### Spotube version

v3.8.1

### Installation source

Website (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-09-19 14:54
Duplicate of #883

**Closed by KRTirtho** 2024-09-19 14:54 UTC
Labels: bug

**Comment by aydogduonur** [comment] 2024-09-22 10:33
And did you solve the issue already? If you did so, it should have played the fucking correct song, my dude.
