### ISSUE TITLE
non-standard resolution

### ISSUE THREAD

**Issue by evilenx** [KRTirtho/spotube#1566] opened 2024-06-04 19:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![report spotube](https://github.com/KRTirtho/spotube/assets/111256110/38fc883e-367c-4030-a90a-c8b60f2d6922)

### Expected Behavior

I can't move the spotube, I can resize it, but it's hard to move the entire window.

### Steps to reproduce

1. I open the application
2. does not resize the resolution correctly. 
3. to fix it, I have to kill the process several times.

### Operating System

Windows

### Spotube version

v3.7.0

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by DerangedWifi** [comment] 2024-06-04 19:52
I'm having the same issue.

**Comment by Kim-Vallee** [comment] 2024-06-05 07:29
Same issue here, latest version to date, windows 11 downloaded on the website the .exe version.

**Comment by KRTirtho** [comment] 2024-06-05 12:04
Duplicate of #1553

**Closed by KRTirtho** 2024-06-05 12:04 UTC
Labels: bug
