### ISSUE TITLE
After download from jiosaavn file dont play.

### ISSUE THREAD

**Issue by AamiRobin** [KRTirtho/spotube#1477] opened 2024-05-05 00:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Audio Source = Jiosaavn

After the download is complete, it displays all the information about the song on the file, including the size. However, the song cannot be played from another player or even from Spotube. its look like the file is corrupted or something.

### Expected Behavior

The file should be playable across different devices or players. Currently, it only works when I set the audio source to YouTube.

### Steps to reproduce

1. Set the audio source to JioSaavn.
2. Download a song and attempt to play it using a different player.

### Operating System

Windows

### Spotube version

v3.6.0

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-05-05 03:06
Duplicate of #1133

**Closed by KRTirtho** 2024-05-05 03:06 UTC
Labels: bug
