### ISSUE TITLE
Can't login with cookie at first time i download...

### ISSUE THREAD

**Issue by AlexYangCong** [KRTirtho/spotube#943] opened 2023-12-10 18:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

as the title,Can't login with cookie at first time i download...,login out and delete cookie was same problem. error information with some stupid(sorry but i from China and i can't even guese.. what mean about those Chinese in EN）translate。
![image](https://github.com/KRTirtho/spotube/assets/49122848/fa6bb752-3df9-47b7-b233-7b194ef6b0eb)

### Expected Behavior

work normal i guese？

### Steps to reproduce

open it  
open website
login（maybe cause i use google account login？）
copy cookie
login
magic！error like this
![image](https://github.com/KRTirtho/spotube/assets/49122848/99e75214-77ad-467d-91a9-8abe5f79debd)

### Operating System

Win11  Enterprise Edition  23H2 Insider build 25597

### Spotube version

latested one

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Additional information

quite confused LOL

**Comment by KRTirtho** [comment] 2023-12-10 19:34
Duplicate of https://github.com/KRTirtho/spotube/issues/905

**Closed** 2023-12-10 19:36 UTC
Labels: bug, duplicate

**Comment by AlexYangCong** [comment] 2023-12-11 15:28
Nah ,i'have try nightly Ver. latested ,not work for me .i guess not same problem? those Chinese means (The semaphore timeout period has expired) in english,so my error log not similar with#905's Brazil and India friends?

**Comment by AlexYangCong** [comment] 2023-12-11 19:10
hmmmm，through my investigation,it's seem to be some bug with flutter?and idk how to solve it. but i can open the (https://open.spotify.com/get_access_token?reason=transport&productType=web_player)and it do give me some words like client id and access token stuff. So can i do it manually? i just wander if the client have somewhere to put those?

**Comment by qinfengge** [comment] 2024-01-04 06:50
same problem in V3.4.0

**Comment by ashoktvm** [comment] 2024-01-09 07:48
![image](https://github.com/KRTirtho/spotube/assets/45116583/ed889619-5a58-4114-817f-73f3078ccdd7)

Any soliution?

**Comment by ZorroHuang** [comment] 2024-01-17 02:19
Same problem in V3.4.0, and this is "timeout" problem. I don't think it is similar to #930 and #913. And I also think there is some bug with flutter. 

> It's similar to #930 and #913

**Comment by GeekYwl** [comment] 2024-04-16 14:22
same problem in V3.6.0

**Comment by KRTirtho** [comment] 2024-04-16 14:53
Just logout and login.
