### ISSUE TITLE
can not log in with spotify account in MacOS  system

### ISSUE THREAD

**Issue by DaneilWan** [KRTirtho/spotube#1010] opened 2024-01-03 07:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

something wrong in MacOS 
<img width="1405" alt="Screen Shot 2024-01-03 at 3 28 36 PM" src="https://github.com/KRTirtho/spotube/assets/51732084/b7c3845b-d71a-4da6-9855-2a232ad1bb0c">
 

### Expected Behavior

fix this bug,please

### Steps to reproduce

i open the app as you suggested, then i want to log in with my spotify account, i tried this step for many times,then it still happened.

### Operating System

macOS

### Spotube version

Version 3.4.0 (27)

### Installation source

GitHub Releases (Binary)

**Comment by KRTirtho** [comment] 2024-01-03 07:46
What is your region?

**Comment by KRTirtho** [comment] 2024-01-03 07:47
Duplicate of #930

**Closed by KRTirtho** 2024-01-03 07:47 UTC
Labels: bug
