### ISSUE TITLE
The music plays again after a pause

### ISSUE THREAD

**Issue by He5am** [KRTirtho/spotube#961] opened 2023-12-26 10:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you pause a song, the song will start playing after your phone rings or Instagram reels play with sound.

### Expected Behavior

It doesn't start playing music until I hit play

### Steps to reproduce

to try :
1)open app.
2)play music 
3)stop it 
4)go Instagram and watch some reels
5)back to home screen u can see music is playing 

### Operating System

android (MIUI 14)

### Spotube version

3.3.0

### Installation source

Play Store (Android)

### Additional information

Uploading video_2023-12-26_14-00-24.mp4…

**Comment by KRTirtho** [comment] 2023-12-30 13:19
Duplicate of #926

**Closed by KRTirtho** 2023-12-30 13:19 UTC
Labels: bug
