### ISSUE TITLE
Going back is bugged 

### ISSUE THREAD

**Issue by code3AGL3** [KRTirtho/spotube#1751] opened 2024-08-01 10:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I am in music player screen and I go back using my navigation back gesture the music player doesn't minimises rather it goes back to home page while the music player screen is on and when it reaches home screen after then if I press back the the music player screen minimises.

### Expected Behavior

Whenever I'm in the music player screen then pressing back or doing the back gesture should minimize the player screen.

### Steps to reproduce

1. Opened the app
2. Went to library
3. In library went to local tap
4. Opened a library
5. Played any music
6. Tap on the music player on the bottom to expand
7. Doing the back gesture(smartphone's slide from side back gesture).
8. Player screen doesn't minimises.

### Operating System

Android 11

### Spotube version

3.7.1

### Installation source

F-Droid (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-08-02 09:37
Duplicate of #1224

**Closed by KRTirtho** 2024-08-02 09:37 UTC
Labels: bug
