### ISSUE TITLE
Windows cursed

### ISSUE THREAD

**Issue by Unchanged4352** [KRTirtho/spotube#1890] opened 2024-09-16 17:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Ekran görüntüsü 2024-09-16 203929](https://github.com/user-attachments/assets/fd5b0acb-a320-450b-aec2-90ec215a613f)
Cursed

### Expected Behavior

Full screen

### Steps to reproduce

1. When first launched after pc initiated.

### Operating System

Windows

### Spotube version

V3.8.1 and V3.8.0

### Installation source

GitHub Actions (Nightly Binary)

### Additional information

If you close it from task manager and then reopen, it won't be cursed.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-10-03 04:08
Duplicate of #1553

**Closed by KRTirtho** 2024-10-03 04:08 UTC
Labels: bug

**Comment by GideonBear** [comment] 2024-10-07 16:25
@KRTirtho Voting to re-open. I have the exact same issue (also on v3.8.2) on Windows 10.

**Comment by Unchanged4352** [comment] 2024-10-07 18:38
> @KRTirtho Voting to re-open. I have the exact same issue (also on v3.8.2) on Windows 10. #1553

**Comment by Unchanged4352** [comment] 2024-10-07 18:41
@GideonBear #1553

**Comment by GideonBear** [comment] 2024-10-08 05:06
> @GideonBear #1553

#1553 was supposedly fixed in 3.7.1, so this might be a separate issue.
