### ISSUE TITLE
Connect with Spotify button Not working.

### ISSUE THREAD

**Issue by DrVektor** [KRTirtho/spotube#1793] opened 2024-08-16 10:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i click to "connect with spotify" anything does not happens.

### Expected Behavior

When I press the “connect with spofiy” button, the spotify connect page opens.

### Steps to reproduce

1. i opened the progam
2. I pressed to gear icon
3. i pressed to "connect with spotify"
4. it didnt opens spotify connection page.

### Operating System

Windows

### Spotube version

3.8.0

### Installation source

Scoop (Windows)

### Additional information

No. Everything thats it. Thank you. Spotube my most loved program. I want to see spotube every time good.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Sx4DoW** [comment] 2024-08-23 19:24
i've got the same issue, any fixes?

**Comment by KRTirtho** [comment] 2024-10-03 04:12
Duplicate of #1800

**Comment by KRTirtho** [comment] 2024-10-03 04:13
You've to have [Edge WebView2](https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH&ch=1) installed

**Closed by KRTirtho** 2024-10-03 04:12 UTC
Labels: bug
