### ISSUE TITLE
canot login

### ISSUE THREAD

**Issue by ziyourenchina** [KRTirtho/spotube#1541] opened 2024-05-31 22:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![屏幕截图 2024-06-01 065603](https://github.com/KRTirtho/spotube/assets/38931206/40ebf217-e191-4787-92c1-3227ace20472)

### Expected Behavior

please tell me how to do ?

### Steps to reproduce

open it and contact spotify.type the sp_dc,then it's wrong

### Operating System

windows11

### Spotube version

v3.6.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev), GitHub Releases (Binary), GitHub Actions (Nightly Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-06-01 04:54
Duplicate of #905

**Closed by KRTirtho** 2024-06-01 04:54 UTC
Labels: bug, potential-duplicate
