### ISSUE TITLE
Unable to log in to spotify

### ISSUE THREAD

**Issue by Evoke-W** [KRTirtho/spotube#1785] opened 2024-08-13 07:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I enter sp_dc Cookie, it always shows Authntication Failure, Error: SocketException. When I log in to Spotify again from the web page, I can't log in to spotube even if I copy cookie again

### Expected Behavior

Unable to log in

### Steps to reproduce

1.我是window11用户，很多人只能使用3.7版本，高本版无法进入软件
2.我用3.7版本进入软件，在网页登录spotify并复制cookie
3.在spotube输入cookie并登录
4.登陆超时

### Operating System

windows11

### Spotube version

v3.7.0

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Evoke-W** [comment] 2024-08-13 07:26
Steps to reproduce
1. I am a window11 user, many people can only use version 3.7, high version can not enter the software
2. I logged into the software with version 3.7, logged into spotify on the web and copied the cookies
3. Enter a cookie in spotube and log in
4. Login timeout

**Comment by KRTirtho** [comment] 2024-08-13 16:30
Upgrade to 3.8.0 first. 3.8.0 works on Windows 10 and 11 finely.

**Comment by KRTirtho** [comment] 2024-08-13 16:30
If 3.8.0 doesn't open follow this https://github.com/KRTirtho/spotube/issues/1786#issuecomment-2286653448

**Comment by KRTirtho** [comment] 2024-08-13 16:30
Duplicate of #930

**Closed by KRTirtho** 2024-08-13 16:30 UTC
Labels: bug
