### ISSUE TITLE
Audio Quality

### ISSUE THREAD

**Issue by Dae-Hang-Sook** [KRTirtho/spotube#884] opened 2023-11-17 09:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Audio quality *kbps* is always, always 192. That's absolutely annoying and the lowest available on android. It should be raised higher. Preferably give an option for 320kbps in the settings. Also, give a download option as mp3 and make it where we can change download folder. It's annoying because you're forced to use the preset because it's basically a cloud file until you move it.

### Suggested solution

Add: 320kbps quality option
Add: mp3 download option
Add: download location option (that works)
Remove: current download system so it's not a cloud-based file when downloading. (This forces the use of the preset download location)

### Useful resources

FFMPEG for all the audio related things.

**Comment by KRTirtho** [comment] 2023-11-17 09:41
Duplicate of #877

**Closed by KRTirtho** 2023-11-17 09:41 UTC
Labels: enhancement

**Comment by Dae-Hang-Sook** [comment] 2023-11-17 09:42
> Duplicate of #877 

This is for more than just the audio quality. Read all of it

**Comment by KRTirtho** [comment] 2023-11-18 03:22
There is nothing as "Cloud File". Downloaded tracks are local audio files in mp4 format, as currently this is the most used + supported high quality media container everywhere. mp3 support is possible but not being worked on currently (Discussed here #815 and #205). The issue with folder is a bug #809
