### ISSUE TITLE
Radio option not working 

### ISSUE THREAD

**Issue by Chickenshrimps** [KRTirtho/spotube#1710] opened 2024-07-12 17:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Screen freezes when clicked on radio option while playing a song 

### Expected Behavior

To start playing radio from that song 

### Steps to reproduce

Open app
Select a song
Click on radio option when you go to the 3dot section
Screen freezes and does not do anything 

### Operating System

Android 

### Spotube version

v.3.7.1

### Installation source

GitHub Releases (Binary)

### Self grab

- [X] I'm ready to work on this issue!

**Comment by Chickenshrimps** [comment] 2024-07-13 04:18
Pls fix it in the next update

**Comment by KRTirtho** [comment] 2024-07-14 13:59
Duplicate of #1629

**Closed by KRTirtho** 2024-07-14 13:59 UTC
Labels: bug
