### ISSUE TITLE
MacOS Mojave crash 

### ISSUE THREAD

**Issue by ikyquocked** [KRTirtho/spotube#472] opened 2023-04-10 11:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

2.7.0 is crashing when starts, 2.5.0 works

### Expected Behavior

just work)

### Steps to reproduce

open the app, got the crash

### Operating System

MacOS 10.14.6

### Spotube version

2.7.0

### Installation source

Website (spotube.netlify.app)

### Additional information

Process:               spotube [88030]
Path:                  /Applications/spotube 2.app/Contents/MacOS/spotube
Identifier:            oss.krtirtho.spotube
Version:               2.7.0 (17)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           spotube [88030]
User ID:               501

Date/Time:             2023-04-10 14:09:27.130 +0300
OS Version:            Mac OS X 10.14.6 (18G9323)
Report Version:        12
Anonymous UUID:        35045F90-0483-03DB-C64A-345DC2AD0F94

Sleep/Wake UUID:       45985D26-901D-400D-A92E-7195D0126E53

Time Awake Since Boot: 1600000 seconds
Time Since Wake:       1500000 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /Users/*/librust.dylib
  Referenced from: /Applications/spotube 2.app/Contents/MacOS/spotube
  Reason: image not found

Binary Images:
       0x104954000 -        0x104957ff7 +oss.krtirtho.spotube (2.7.0 - 17) <474930FD-5EA1-36FB-B731-9BA069282701> /Applications/spotube 2.app/Contents/MacOS/spotube
       0x1097ca000 -        0x10983470f  dyld (655.1.1) <4842B61A-B868-3146-9CA9-5582C4198B25> /usr/lib/dyld

Model: iMac17,1, BootROM 451.120.7.0.0, 4 processors, 4-Core Intel® Core™ i7-6700, 3,4 GHz, 32 GB, SMC 2.33f12
Graphics: NVIDIA GeForce GTX 780, NVIDIA GeForce GTX 780, spdisplays_pcie_device, 3 GB
Memory Module: BANK 1/ChannelA-DIMM1, 16 GB, DDR4, 2133 MHz, Kingston, 9905701-131.A00G
Memory Module: BANK 3/ChannelB-DIMM1, 16 GB, DDR4, 2133 MHz, Kingston, 9905625-066.A00G
Network Service: Ethernet, Ethernet, en0
PCI Card: NVIDIA GeForce GTX 780, Display Controller, Slot-1
Serial ATA Device: Samsung SSD 860 PRO 512GB, 512,11 GB
Serial ATA Device: Samsung SSD 850 EVO 120GB, 120,03 GB
USB Device: USB 3.0 Bus
USB Device: USB5734
USB Device: QUAD-CAPTURE
USB Device: USB2734
USB Device: USB Device
USB Device: USB 2.0 Hub [MTT]
USB Device: USB Keyboard
USB Device: Hub Controller
Thunderbolt Bus:

**Comment by karniv00l** [comment] 2023-04-10 11:16
Looks like duplicate of: https://github.com/KRTirtho/spotube/issues/468

**Comment by RaptaG** [comment] 2023-04-10 12:02
I'm closing this, if it's not a duplicate let me know @ikyquocked

**Closed by RaptaG** 2023-04-10 12:02 UTC
Labels: bug, duplicate
