### ISSUE TITLE
Appimage cannot run

### ISSUE THREAD

**Issue by newyorkthink** [KRTirtho/spotube#922] opened 2023-12-01 13:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/KRTirtho/spotube/assets/87791643/cf82e9de-8f6b-459c-945a-a7ad66eba91a)

### Expected Behavior

![image](https://github.com/KRTirtho/spotube/assets/87791643/4f842600-4ab1-4f46-aedb-3d6ff1bce026)

### Steps to reproduce

```

❯ ./Downloads/Spotube-linux-x86_64.AppImage

(spotube:67500): dbind-WARNING **: 21:35:40.036: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

(spotube:67500): Gdk-CRITICAL **: 21:35:40.053: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
package:media_kit_libs_linux registered.
flutter:
--------------------------------------------------------------------------------
media_kit: ERROR: MediaKit.ensureInitialized
This indicates that one or more required dependencies could not be located.

Refer to "Installation" section of the README for further details:
GitHub  : https://github.com/media-kit/media-kit#installation
pub.dev : https://pub.dev/packages/media_kit#installation

TIP: Copy-paste required packages from the above link to your pubspec.yaml.

If you recently added the packages, make sure to re-run the project ("hot-restart" & "hot-reload" is not sufficient for native plugins).
--------------------------------------------------------------------------------

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Cannot find libmpv at the usual places. Depending upon your distribution, you can install the libmpv package to make shared library available globally. On Debian or Ubuntu based systems, you can install it with: apt install libmpv-dev.
#0      NativeLibrary.ensureInitialized (package:media_kit/src/player/native/core/native_library.dart:78)
#1      nativeEnsureInitialized (package:media_kit/src/player/native/player/real.dart:47)
#2      MediaKit.ensureInitialized (package:media_kit/src/media_kit.dart:26)
#3      main (package:spotube/main.dart:45)
<asynchronous suspension>
```

### Operating System

linux

### Spotube version

latest

### Installation source

GitHub Releases (Binary)

**Comment by KRTirtho** [comment] 2023-12-02 16:51
Duplicate of #643

**Closed as completed** 2023-12-02 16:52 UTC
Labels: bug, duplicate
