### ISSUE TITLE
Incorrectly linked songs

### ISSUE THREAD

**Issue by LunasShade** [KRTirtho/spotube#1443] opened 2024-04-24 16:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have noticed with several songs that the song that should have been played is not played. The title and artist are correct, but the audio is completely wrong.

### Expected Behavior

If the title, the cover and the artist are correct, the audio track is the right one.

### Steps to reproduce

1. i opened the app
2. go to library
3. go to favourite songs
4. play a song
5. everything looks right, but the audio is the wrong one

### Operating System

Archlinux

### Spotube version

v3.6.0

### Installation source

Arch User Repository (AUR)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by SoftwareSchlosser** [comment] 2024-04-26 05:56
Same issue with the android app (current version from google store).

Steps:
1. fresh install of the app
2. login to spotify (premium account)
3. browsing and play several tracks
4. tracks get mixed up. some didn't play at all and skipped to the next one in the album

**Comment by KRTirtho** [comment] 2024-04-26 14:22
Duplicate of #883

**Closed by KRTirtho** 2024-04-26 14:22 UTC
Labels: bug
