### ISSUE TITLE
I can't download songs on iphone.

### ISSUE THREAD

**Issue by Root-FTW** [KRTirtho/spotube#1575] opened 2024-06-06 02:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can only play songs, but it doesn't allow me to download songs on iphone.

### Expected Behavior

I want to download the songs for offline use

### Steps to reproduce

I open the app, try to download a song, or several songs, and only the error icon appears.

### Operating System

Iphone 13 pro max 

### Spotube version

3.7.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Self grab

- [X] I'm ready to work on this issue!

**Comment by Root-FTW** [comment] 2024-06-06 02:43
Here some SS

![df300a5f-51ef-4067-91e4-9ef65f7e5de1](https://github.com/KRTirtho/spotube/assets/108767514/89376436-cdd4-4a92-834a-818e22c1736c)

![7ead59c1-1ab8-4a9c-b01b-22a584ca9aa0](https://github.com/KRTirtho/spotube/assets/108767514/af321c1f-8649-47a0-8d29-dbb602a6dd73)


![39096b60-6e98-49dc-a8a6-123741845505](https://github.com/KRTirtho/spotube/assets/108767514/9a81ebec-8879-45b5-bb5d-e8f589358096)

**Comment by Root-FTW** [comment] 2024-06-06 04:11
configuration I used in Sideloadly!
![Captura de pantalla 2024-06-05 211127](https://github.com/KRTirtho/spotube/assets/108767514/4f51ef4a-75d1-459f-aa60-369d7aa43272)

**Comment by Root-FTW** [comment] 2024-06-06 04:12
configuration I used in Sideloadly!

![image](https://github.com/KRTirtho/spotube/assets/108767514/e5b5678f-4f2f-4efa-8ca8-20200d9762e2)

**Comment by Root-FTW** [comment] 2024-06-06 04:28
LOGS:




============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-06-05 21:23:47.030604

------- DEVICE INFO -------
model: iPhone
isPhysicalDevice: true
name: iPhone
identifierForVendor: 28BBD19F-46B1-410E-9455-AA54B0BFAA18
localizedModel: iPhone
systemName: iOS
utsnameVersion: Darwin Kernel Version 23.5.0: Wed May  1 20:34:31 PDT 2024; root:xnu-10063.122.3~3/RELEASE_ARM64_T8110
utsnameRelease: 23.5.0
utsnameMachine: iPhone14,3
utsnameNodename: localhost
utsnameSysname: Darwin

------- APP INFO -------
environment: release
version: 3.7.0
appName: Spotube
buildNumber: 31
packageName: oss.krtirtho.spotube.stable

---------- ERROR ----------
type 'Null' is not a subtype of type 'String'

------- STACK TRACE -------
#0      AndroidBuildVersion._fromMap (package:device_info_plus/src/model/android_device_info.dart:239)
#1      AndroidDeviceInfo.fromMap (package:device_info_plus/src/model/android_device_info.dart:147)
#2      DeviceInfoPlugin.androidInfo (package:device_info_plus/device_info_plus.dart:54)
<asynchronous suspension>
#3      useGetStoragePermissions.<anonymous closure> (package:spotube/hooks/configurators/use_get_storage_perms.dart:17)
<asynchronous suspension>

------- CUSTOM INFO -------
======================================================================
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-06-05 21:23:47.370031

------- DEVICE INFO -------
model: iPhone
isPhysicalDevice: true
name: iPhone
identifierForVendor: 28BBD19F-46B1-410E-9455-AA54B0BFAA18
localizedModel: iPhone
systemName: iOS
utsnameVersion: Darwin Kernel Version 23.5.0: Wed May  1 20:34:31 PDT 2024; root:xnu-10063.122.3~3/RELEASE_ARM64_T8110
utsnameRelease: 23.5.0
utsnameMachine: iPhone14,3
utsnameNodename: localhost
utsnameSysname: Darwin

------- APP INFO -------
environment: release
version: 3.7.0
appName: Spotube
buildNumber: 31
packageName: oss.krtirtho.spotube.stable

---------- ERROR ----------
PlatformException(discoveryError, Bonsoir has encountered an error during discovery : -65555: NoAuth (error %s)., -65555, null)

------- STACK TRACE -------

------- CUSTOM INFO -------
======================================================================
============================== CATCHER 2 LOG ==============================
Crash occurred on 2024-06-05 21:24:26.706099

------- DEVICE INFO -------
model: iPhone
isPhysicalDevice: true
name: iPhone
identifierForVendor: 28BBD19F-46B1-410E-9455-AA54B0BFAA18
localizedModel: iPhone
systemName: iOS
utsnameVersion: Darwin Kernel Version 23.5.0: Wed May  1 20:34:31 PDT 2024; root:xnu-10063.122.3~3/RELEASE_ARM64_T8110
utsnameRelease: 23.5.0
utsnameMachine: iPhone14,3
utsnameNodename: localhost
utsnameSysname: Darwin

------- APP INFO -------
environment: release
version: 3.7.0
appName: Spotube
buildNumber: 31
packageName: oss.krtirtho.spotube.stable

---------- ERROR ----------
PathNotFoundException: Cannot copy file to '/var/mobile/Containers/Data/Application/FC62DBE8-B28B-4760-B28B-5EDF1538350B/Downloads/Spotube/End of Beginning - Djo.m4a', path = '/var/mobile/Containers/Data/Application/FC62DBE8-B28B-4760-B28B-5EDF1538350B/Library/Caches/spotube-downloads/End of Beginning - Djo.m4a.partial' (OS Error: No such file or directory, errno = 2)

------- STACK TRACE -------
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _File.copy.<anonymous closure> (dart:io/file_impl.dart:356)
<asynchronous suspension>
#2      DownloadManager.download (package:spotube/services/download_manager/download_manager.dart:143)
<asynchronous suspension>
#3      DownloadManager._startExecution (package:spotube/services/download_manager/download_manager.dart:409)
<asynchronous suspension>

------- CUSTOM INFO -------
======================================================================

**Comment by KRTirtho** [comment] 2024-06-06 07:12
Duplicate of #1327

**Closed by KRTirtho** 2024-06-06 07:12 UTC
Labels: bug, ios
