### ISSUE TITLE
Spotube hanging when clicking "add song to playlist"

### ISSUE THREAD

**Issue by hexlocation** [KRTirtho/spotube#888] opened 2023-11-20 17:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I searched for a song, right-clicked it and selected "Add To Playlist". After that, a dialogue appeared and a loading symbol, after that, spotube freezes.
If i don't close spotube, after ~1-2 minutes i noticed my system just hanged.

### Expected Behavior

A dialogue to appear giving me the option to select a playlist to which i want to add the song.

### Steps to reproduce

1. Open Spotube
2. Search for a song.
3. Right-click it
4. Select "Add To Playlist"
5. System/spotube hangs.

### Operating System

(Arch) Linux

### Spotube version

v3.2.0

### Installation source

Flathub (Flatpak)

### Additional information

Last 30 or so logs before force-resetting my laptop: https://pastebin.com/QHd5escK

I use gnome (45.1).

**Comment by KRTirtho** [comment] 2023-11-21 03:20
> Is there an existing issue for this?
> - [x] I have searched the existing issues

Clearly haven't

Duplicate of #817

**Closed by KRTirtho** 2023-11-21 03:20 UTC
Labels: bug
