### ISSUE TITLE
Missing Tray Icon when running Fedora 38

### ISSUE THREAD

**Issue by GoldenReverie** [KRTirtho/spotube#629] opened 2023-08-14 18:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Missing Tray Icon when running Fedora 38 normal right click functions intact  just blank space for the tray icon.

### Expected Behavior

Icon stored on the repo to be displayed instead of a blank space.

### Steps to reproduce

1. Launch app
2. Look at the tray to see a missing icon

### Operating System

Fedora 38

### Spotube version

v3.0.1

### Installation source

Flathub (Flatpak)

**Comment by GoldenReverie** [comment] 2023-08-14 18:10
![Screenshot_20230814_190448](https://github.com/KRTirtho/spotube/assets/2473398/6bfb389f-ab65-41da-9e6e-7ad054bf58ef)
Forgot the screen capture though its pretty self explanatory.

**Comment by KRTirtho** [comment] 2023-08-15 04:35
Duplicate of https://github.com/KRTirtho/spotube/issues/541

> Is there an existing issue for this?

>  [x]  I have searched the existing issues

Why did you check this even though there's already a duplicate issue? :eye:

**Closed** 2023-08-15 04:35 UTC
Labels: bug, duplicate

**Comment by GoldenReverie** [comment] 2023-08-15 09:35
> Duplicate of #541
> 
> > Is there an existing issue for this?
> 
> > [x]  I have searched the existing issues
> 
> Why did you check this even though there's already a duplicate issue? eyes

my bad, I searched for "tray" but alas I did not see anything at the time probably my fault. Shows up fine now, sorry to bother keep up the great work.

**Comment by KRTirtho** [comment] 2023-08-15 11:14
No worries. Enjoy 😊
