### ISSUE TITLE
type "double" is not a subtype of type "int?" in type cast 

### ISSUE THREAD

**Issue by bandinopla** [KRTirtho/spotube#1110] opened 2024-01-22 18:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you click on the artist's name of a song you get that error.

### Expected Behavior

see all songs from that artist

### Steps to reproduce

1. open the app
2. click on a song
3. click on the artist of that song

### Operating System

windows 10

### Spotube version

v3.4.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by terrarier2111** [comment] 2024-01-22 18:13
This is a duplicate of https://github.com/KRTirtho/spotube/issues/1018

**Comment by KRTirtho** [comment] 2024-01-23 17:11
Duplicate

**Closed by KRTirtho** 2024-01-23 17:11 UTC
Labels: bug, duplicate
