### ISSUE TITLE
Playing an incorrect song not matching the selected one.

### ISSUE THREAD

**Issue by simply-leon** [KRTirtho/spotube#1604] opened 2024-06-11 07:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried to play/search a song(specifically https://open.spotify.com/track/1O4JEMG1V06Lmkw8JQMY52?si=18e756d0a0224dbe), the search result option plays another song from the same album, and when I use my playlist which I have the song included, it just refuses to play the song(as in, not able to get selected)

### Expected Behavior

The correct song audio to play

### Steps to reproduce

1. I opened the app
2. I selected the song I wanted to play
3. It played another song but from the same album(the song which is AFTER the one im trying to play)

### Operating System

Windows

### Spotube version

3.7.1

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by mfaathirarsa** [comment] 2024-06-15 23:46
Bumping this up because I also experience the same issue as the user above me.

This issue is in bot the windows and android distribution

For example this is one of the songs : 
https://open.spotify.com/track/5563ySheBsw9qruduez5R4
But they played this song instead:
https://open.spotify.com/track/46LAOCq7tkuwgBYweIYLnt

And another example is:
https://open.spotify.com/track/2qdPWFrknWyLXYIPpbtAgD
Where they should've picked the whole song but they strangely picked the acoustic cover of it:
https://youtu.be/l434Zybp2To

And many more example but I've proven my point for now, I'll give more points if you ask me

*Now this problem could actually be solved* 
If you use the "Alternative track resources function" and pick the right video, which works for me

*But* they don't save your choice so you have to do this every single time, and even on the *windows* distribution this straight up breaks the song and I can't play it anymore (this method is safe in android version)

Maybe to code a better song detection is still out of reach, but I think to implement a *save feature* for the Alternative track resources would be a good start to mitigate the issue

**Comment by KRTirtho** [comment] 2024-07-09 14:00
Duplicate of #883

**Closed by KRTirtho** 2024-07-09 14:00 UTC
Labels: bug
