### ISSUE TITLE
No server seems to listen to the port

### ISSUE THREAD

**Issue by theArtechnology** [KRTirtho/spotube#25] opened 2022-02-07 20:29 UTC
**Describe the bug**

**To Reproduce**
1. Launch App
2. Add credentials (Client ID/Secret)
3. It opens your browser and you give access
4. After giving permissions, nothing listen to the port

**Expected behavior**
Supposed to open the app after going to `http://localhost:4304/auth/spotify/callback`

**Screenshots**
<img width="789" alt="Screenshot 2022-02-08 at 00 22 43" src="https://user-images.githubusercontent.com/26553194/152866656-b56894b0-5152-4ad8-9981-de266e34e213.png">

**Installation Source/Method**
[Spotube-macos-x86_64.dmg v1.1.0](https://github.com/KRTirtho/spotube/releases/download/v1.1.0/Spotube-macos-x86_64.dmg)

**Desktop:**
 Mac OS Darwin Kernel Version 19.6.0 Intel 2020

**Comment by KRTirtho** [comment] 2022-02-08 03:35
Duplicate of https://github.com/KRTirtho/spotube/issues/17
This bug has been fixed & will be shipped in the next release

**Closed** 2022-02-08 04:29 UTC
Labels: bug
