### ISSUE TITLE
I'm Connected To Internet, But It Says "You Are Currently Offline"

### ISSUE THREAD

**Issue by RinaChanBoard** [KRTirtho/spotube#728] opened 2023-09-17 10:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've Turned On The Internet, But The App Says That I'm Now Offline

### Expected Behavior

When I downloaded this application, logged in, and it said that I was not connected to the internet, aka offline, I thought "Oh, at least because I haven't logged in to Spotify", I logged in, but it's still the same, still offline

### Steps to reproduce

1. I Open The App
2. It Says "You Are Currently Offline"

### Operating System

Android

### Spotube version

v3.1.2

### Installation source

Play Store (Android)

### Additional information

Only the place to log in to Spotify is possible, the rest is not, such as searching for songs and others

**Comment by KRTirtho** [comment] 2023-09-17 16:24
Make sure you're not connected with VPN. Currently, it has issues working through a VPN

**Comment by KRTirtho** [comment] 2023-09-26 03:07
Duplicate of #706

**Closed by KRTirtho** 2023-09-26 03:07 UTC
Labels: bug
