### ISSUE TITLE
nothing load when using tor

### ISSUE THREAD

**Issue by TKZ2009** [KRTirtho/spotube#714] opened 2023-09-11 23:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

im using tor vpn and when i open the app it just a blank homepage with featured title on the top
(i do restart the app, phone , force stop and clear cash and log out&in)

### Expected Behavior

the homepage get loaded 

### Steps to reproduce

1:i connected to the tor vpn with inviZible client
2: i opened the app and nothing load

### Operating System

Android 13

### Spotube version

3.1.1

### Installation source

GitHub Releases (Binary), F-Droid (Android)

**Comment by KRTirtho** [comment] 2023-09-12 08:21
Duplicate of https://github.com/KRTirtho/spotube/issues/706

**Closed by KRTirtho** 2023-09-12 08:21 UTC
Labels: bug
