### ISSUE TITLE
Equaliser support for apps like Wavelet

### ISSUE THREAD

**Issue by geetaroraqaz** [KRTirtho/spotube#1965] opened 2024-10-06 01:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I don't like low bass and high treble in music, it makes my ear and head hurt.

### Suggested solution

Adding support of using Equaliser to customize music like increasing bass, reducing treble. And external support of using apps like wavelet would be really appreciated. 
Love your work ❤️

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-10-10 16:00
Duplicate of #465

**Closed by KRTirtho** 2024-10-10 16:00 UTC
Labels: enhancement

**Comment by KRTirtho** [comment] 2024-10-10 16:02
> Is there an existing issue for this?
> [x] I have searched the existing issues

![image](https://github.com/user-attachments/assets/10bf69d3-a2ac-4ad1-8454-00947bbcf391)

**Comment by geetaroraqaz** [comment] 2024-10-11 04:45
> > Is there an existing issue for this?
> > [x] I have searched the existing issues
> 
> ![image](https://private-user-images.githubusercontent.com/61944859/375456956-10bf69d3-a2ac-4ad1-8454-00947bbcf391.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MjIxMjYsIm5iZiI6MTcyODYyMTgyNiwicGF0aCI6Ii82MTk0NDg1OS8zNzU0NTY5NTYtMTBiZjY5ZDMtYTJhYy00YWQxLTg0NTQtMDA5NDdiYmNmMzkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA0NDM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0ZjViMTNjYjUwOWI4ZGFiNzYyNTExMzAxYzNkNzA0NWQ5ZWNlODg5NmIzMWNlNWJhMGM5YzM0OGE4ZDc3OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fVR_2hVDsbCYtFSW1O9QMUT0OHj5rAaDJIXfGNH6zNY)

I searched equaliser 😅 and not equalizer
