### ISSUE TITLE
no longer plays music, doesnt load songs fully

### ISSUE THREAD

**Issue by adam110902** [KRTirtho/spotube#1920] opened 2024-09-25 08:09 UTC
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

When i launch the app it just loads the title of the song, loads for a bit, skips the song and reapeats this until closed

### Expected Behavior

Play songs as normal

### Steps to reproduce

1. Open the app
2. look at the current playing song as it loads than skips

### Logs

https://gist.github.com/adam110902/60f5ba3b39f128d5b71b0a3449b99c68

Too long to paste

### Operating System

android

### Spotube version

3.8.1

### Installation source

Website (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by cancrexo** [comment] 2024-09-25 08:13
+1 here. No music at all, using spotify as source

**Comment by florent4014** [comment] 2024-09-25 09:10
+1 load the song for like 5-10 seconds then stop and nothing ever happen

**Comment by alfesc** [comment] 2024-09-25 10:28
Same here. After some seconds, play button stops spinning and no music at all.

**Comment by thomaslp** [comment] 2024-09-25 11:48
same thing on both Android and linux desktop app.

**Comment by JacobNussbaum** [comment] 2024-09-25 11:54
Same also here. MacOS 3.8.1 and Android Xperia 5 iv 3.4.0 and 3.8.1
Also doesn't load all my playlists. Every time I go to the playlist page it slowly populates the list, sometimes not finishing.

**Comment by workingmachine** [comment] 2024-09-25 12:03
Same here at Android and Windows.

**Comment by jojommeke** [comment] 2024-09-25 12:13
+1 flatpak on linux app, also tried piped with different instances, still refuses to play

**Comment by nathansCodes** [comment] 2024-09-25 12:53
Same here. Android and flatpak, all sources. Whenever I select a song from the queue, it loads the song (if it hasn't been loaded before) and immediately goes to the next one as if the song had finished playing. When the song is not in the queue, then it doesn't even try to clear/doesn't get added to the queue


https://github.com/user-attachments/assets/b2955830-c762-4dd3-86ae-2d97a46549c2


https://github.com/user-attachments/assets/948853fb-b72d-4444-84a2-97749e9f2a21

**Comment by MrPrezAtambaev** [comment] 2024-09-25 13:04
<img width="1129" alt="Снимок экрана 2024-09-25 в 19 03 33" src="https://github.com/user-attachments/assets/b357b470-e054-4ca9-8aa8-47854161cde8">

I also have

**Comment by Aro320x** [comment] 2024-09-25 14:00
I have exactly the same problem as the topic creator. 
I have an Android cell phone. 
It was still working 2 days ago.

**Comment by Aro320x** [comment] 2024-09-25 14:03
[2024-09-25 12:28:41.336771]---------------------
Bad state: The provider AutoDisposeStreamProvider<String>#805be was disposed during loading state, yet no value could be emitted.
#0      FutureHandlerProviderElementMixin.dispose (package:riverpod/src/async_notifier/base.dart:460)
#1      StreamProviderElement.dispose (package:riverpod/src/stream_provider/base.dart:170)
#2      ProviderContainer._disposeProvider (package:riverpod/src/framework/container.dart:319)
#3      ProviderScheduler._performDispose (package:riverpod/src/framework/scheduler.dart:128)
#4      ProviderScheduler._task (package:riverpod/src/framework/scheduler.dart:83)
#5      ProviderScheduler.vsync.<anonymous closure>.invoke (package:riverpod/src/framework/scheduler.dart:41)
#6      _UncontrolledProviderScopeElement.build (package:flutter_riverpod/src/framework.dart:396)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5487)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:5203)
#9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2905)
#10     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1136)
#11     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443)
#12     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392)
#13     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313)
#14     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171)
#15     _rootRun (dart:async/zone.dart:1399)
#16     _CustomZone.run (dart:async/zone.dart:1301)
#17     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#18     _invoke (dart:ui/hooks.dart:314)
#19     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419)
#20     _drawFrame (dart:ui/hooks.dart:283)

----------------------------------------
[2024-09-25 12:48:29.839991]---------------------
Option af: dynaudnorm doesn't exist.
#0      new AudioPlayerInterface.<anonymous closure> (package:spotube/services/audio_player/audio_player.dart:93)
#1      _rootRunUnary (dart:async/zone.dart:1407)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#5      _DelayedData.perform (dart:async/stream_impl.dart:541)
#6      _PendingEvents.handleNext (dart:async/stream_impl.dart:646)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617)
#8      _rootRun (dart:async/zone.dart:1391)
#9      _CustomZone.run (dart:async/zone.dart:1301)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#12     _rootRun (dart:async/zone.dart:1399)
#13     _CustomZone.run (dart:async/zone.dart:1301)
#14     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

----------------------------------------
---------
[2024-09-25 13:10:21.635617]---------------------
Option af: dynaudnorm doesn't exist.
#0      new AudioPlayerInterface.<anonymous closure> (package:spotube/services/audio_player/audio_player.dart:93)
#1      _rootRunUnary (dart:async/zone.dart:1407)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#5      _DelayedData.perform (dart:async/stream_impl.dart:541)
#6      _PendingEvents.handleNext (dart:async/stream_impl.dart:646)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617)
#8      _rootRun (dart:async/zone.dart:1391)
#9      _CustomZone.run (dart:async/zone.dart:1301)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#12     _rootRun (dart:async/zone.dart:1399)
#13     _CustomZone.run (dart:async/zone.dart:1301)
#14     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

----------------------------------------
---------
[2024-09-25 16:01:59.292040]---------------------
Option af: dynaudnorm doesn't exist.
#0      new AudioPlayerInterface.<anonymous closure> (package:spotube/services/audio_player/audio_player.dart:93)
#1      _rootRunUnary (dart:async/zone.dart:1407)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#5      _DelayedData.perform (dart:async/stream_impl.dart:541)
#6      _PendingEvents.handleNext (dart:async/stream_impl.dart:646)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617)
#8      _rootRun (dart:async/zone.dart:1391)
#9      _CustomZone.run (dart:async/zone.dart:1301)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#12     _rootRun (dart:async/zone.dart:1399)
#13     _CustomZone.run (dart:async/zone.dart:1301)
#14     _CustomZone.runGuarded (dart:async/zone.dart:1209)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

----------------------------------------
---------
[2024-09-25 16:01:59.582179]---------------------
OAuth authorization error (invalid_token): The access token expired.
#0      Client.send (package:oauth2/src/client.dart:134)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl.<anonymous closure> (package:spotify/src/spotify_base.dart:211)
<asynchronous suspension>
#3      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:247)
<asynchronous suspension>
#4      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#5      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:253)
<asynchronous suspension>
#6      SinglePages.stream.handlePageAndGetNext (package:spotify/src/endpoints/endpoint_paging.dart:187)
<asynchronous suspension>

----------------------------------------
provider/spotify/album/releases.dart:50)
<asynchronous suspension>
#8      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-09-25 16:01:59.584456]---------------------
DioException [bad response]: This exception was thrown because the response has a status code of 401 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 401 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:509)
<asynchronous suspension>
#1      CustomSpotifyEndpoints.getView (package:spotube/services/custom_spotify_endpoints/spotify_endpoints.dart:80)
<asynchronous suspension>
#2      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-09-25 16:01:59.600089]---------------------
OAuth authorization error (invalid_token): The access token expired.
#0      Client.send (package:oauth2/src/client.dart:134)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl.<anonymous closure> (package:spotify/src/spotify_base.dart:211)
<asynchronous suspension>
#3      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:247)
<asynchronous suspension>
#4      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#5      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:253)
<asynchronous suspension>
#6      FeaturedPlaylistsNotifier.fetch (package:spotube/provider/spotify/playlist/featured.dart:33)
<asynchronous suspension>
#7      FeaturedPlaylistsNotifier.build (package:spotube/provider/spotify/playlist/featured.dart:44)
<asynchronous suspension>
#8      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-09-25 16:01:59.621761]---------------------
DioException [bad response]: This exception was thrown because the response has a status code of 401 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 401 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:509)
<asynchronous suspension>
#1      CustomSpotifyEndpoints.getHomeFeed (package:spotube/services/custom_spotify_endpoints/spotify_endpoints.dart:131)
<asynchronous suspension>
#2      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-09-25 16:02:27.306369]---------------------
[TrackNotFoundError] Rain Poets - Phillip Boa And The Voodooclub
#0      JioSaavnSourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sources/jiosaavn.dart:60)
<asynchronous suspension>
#1      SourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sourced_track.dart:139)
<asynchronous suspension>
#2      sourcedTrackProvider.<anonymous closure> (package:spotube/provider/server/sourced_track.dart:25)
<asynchronous suspension>
#3      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------

**Comment by Numbzin** [comment] 2024-09-25 14:24
Same here, the songs load infinitely, then skip to the next one, but nothing plays

**Comment by R2D2ar** [comment] 2024-09-25 16:35
I also encountered the same problem

**Comment by AarushiswinnerYo** [comment] 2024-09-25 17:04
Same here, trying to listen to my everyday playlist, it's not working

**Comment by TheTridentGuy** [comment] 2024-09-25 17:04
Same issue, songs try to load but never play

**Comment by MrPrezAtambaev** [comment] 2024-09-25 17:36
> This is probably related to #1916 and should be fixed in the library causing the issue according to https://github.com/Hexer10/youtube_explode_dart/issues/286
> Bumping the version and rebuilding spotube should resolve the problem - will try later.

And how to make a rebuild in the application?

**Comment by ksaadDE** [comment] 2024-09-25 18:37
Same over here 403 error. I upgraded a second ago, after the old version was not loading songs anymore.

I guess it is some kind of endpoint or endpoint data processing issue. 403.

Like here (as previously pointed out in #1916)
https://github.com/Hexer10/youtube_explode_dart/issues/286

For me it's on Desktop. Non-Windows env.

```
[2024-09-25 a few mins ago] 
Error Code: 400
Invalid base62 id
#0      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:282)
#1      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#3      Pages.getPage (package:spotify/src/endpoints/endpoint_paging.dart:253)
<asynchronous suspension>
#4      AlbumTracksNotifier.fetch (package:spotube/provider/spotify/album/tracks.dart:33)
<asynchronous suspension>
#5      AlbumTracksNotifier.build (package:spotube/provider/spotify/album/tracks.dart:48)
<asynchronous suspension>
#6      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

[2024-09-25 a few mins ago]
Error Code: 400
Invalid base62 id
#0      SpotifyApiBase.handleResponseWithBody (package:spotify/src/spotify_base.dart:282)
#1      SpotifyApiBase._requestWrapper (package:spotify/src/spotify_base.dart:256)
<asynchronous suspension>
#2      SpotifyApiBase._getImpl (package:spotify/src/spotify_base.dart:210)
<asynchronous suspension>
#3      Me.containsSavedAlbums (package:spotify/src/endpoints/me.dart:224)
<asynchronous suspension>
#4      albumsIsSavedProvider.<anonymous closure>.<anonymous closure> (package:spotube/provider/spotify/album/is_saved.dart:7)
<asynchronous suspension>
#5      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

[2024-09-25 a few mins ago] 
YoutubeExplodeException: Video xyz returned 403 (stream: 137
#0      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46)
<asynchronous suspension>
#1      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:949)
<asynchronous suspension>
#3      YoutubeSourcedTrack.toSiblingType (package:spotube/services/sourced_track/sources/youtube.dart:145)
<asynchronous suspension>
#4      YoutubeSourcedTrack.fetchSiblings (package:spotube/services/sourced_track/sources/youtube.dart:239)
<asynchronous suspension>
#5      YoutubeSourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sources/youtube.dart:63)
<asynchronous suspension>
#6      SourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sourced_track.dart:117)
<asynchronous suspension>
#7      sourcedTrackProvider.<anonymous closure> (package:spotube/provider/server/sourced_track.dart:25)
<asynchronous suspension>
#8      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>
```

We seemingly have to wait until the next build gets released.

**Comment by ksaadDE** [comment] 2024-09-25 18:40
@Aro320x omg please fix the formatting your "#id" is mentioning other issues, which are not related to it. Simply put backticks:  \`\`\` text here \`\`\` around it.

**Comment by Aro320x** [comment] 2024-09-25 18:50
> @Aro320xoh mein Gott, bitte korrigieren Sie die Formatierung. Ihre „#Zeile“ erwähnt andere Probleme, die damit nichts zu tun haben. Setzen Sie einfach Backticks: „Text hier“ darum.

Sorry, but I'm not a programmer. 
I have no idea where I can change my formatting!

**Comment by kleyton67** [comment] 2024-09-25 19:28
+1 Here

Steps to reproduce
1 - Login user
2 - Select a playlist
3 - Click on play button 
4 - Supposed to start (fail)

1 - Click in a music on your library
2 - Click in play button
3 - Supposed to start (fail)

.spotube_logs
`----------------------------------------
[2024-09-25 16:22:58.469419]---------------------
YoutubeExplodeException: Video DRig8NXudvQ returned 403 (stream: 18
#0      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46)
<asynchronous suspension>
#1      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:949)
<asynchronous suspension>
#3      YoutubeSourcedTrack.toSiblingType (package:spotube/services/sourced_track/sources/youtube.dart:145)
<asynchronous suspension>
#4      YoutubeSourcedTrack.fetchSiblings (package:spotube/services/sourced_track/sources/youtube.dart:239)
<asynchronous suspension>
#5      YoutubeSourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sources/youtube.dart:63)
<asynchronous suspension>
#6      SourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sourced_track.dart:117)
<asynchronous suspension>
#7      sourcedTrackProvider.<anonymous closure> (package:spotube/provider/server/sourced_track.dart:25)
<asynchronous suspension>
#8      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------`

OS

`Ubuntu 22.04.4 LTS \n \l`


App version
![Captura de tela de 2024-09-25 16-28-14](https://github.com/user-attachments/assets/fb3243b9-5318-451c-a0af-47b10c1dea95)

Tried with nightly version too, same behavior.

**Comment by ksaadDE** [comment] 2024-09-25 19:49
> > @Aro320xoh mein Gott, bitte korrigieren Sie die Formatierung. Ihre „#Zeile“ erwähnt andere Probleme, die damit nichts zu tun haben. Setzen Sie einfach Backticks: „Text hier“ darum.
> 
> Sorry, but I'm not a programmer. I have no idea where I can change my formatting!

Dreipunkte obere rechte Ecke, dann "editieren" - alles gut :D

**Comment by ksaadDE** [comment] 2024-09-25 19:51
@kleyton67  please fix your formatting as well. Top right corner, three dots, edit and put back ticks around it. Atm you ping unrelated issues.

**Comment by kleyton67** [comment] 2024-09-25 19:52
> @kleyton67 please fix your formatting as well. Top right corner, three dots, edit and put back ticks around it. Atm you ping unrelated issues.
I have changed it, can u check again?

**Comment by aws1313** [comment] 2024-09-25 21:37
> This is probably related to #1916 and should be fixed in the library causing the issue according to [Hexer10/youtube_explode_dart#286](https://github.com/Hexer10/youtube_explode_dart/issues/286) Bumping the version and rebuilding spotube should resolve the problem - will try later.

I can confirm that updating `youtube_explode_dart: ^2.2.2` in `pubspec.yaml` and building the app solves the problem for me. I tried several songs and they all worked fine.
Is it possible to release a new version of Spotube outside the release schedule with only this dependency changed to make the app usable again? Even if it does not seem to fix the problem for everyone (mentioned in https://github.com/Hexer10/youtube_explode_dart/issues/286), I think it would be better if at least some people could use the app.

**Comment by Aro320x** [comment] 2024-09-25 21:55
> > > @Aro320xoh mein Gott, bitte korrigieren Sie die Formatierung. Ihre „#Zeile“ erwähnte andere Probleme, die damit nichts zu tun haben. Setzen Sie einfach Backticks: „Text hier“ darum.
> > 
> > 
> > Tut mir leid, aber ich bin kein Programmierer. Ich habe keine Ahnung, wo ich meine Formatierung ändern kann!
> 
> Dreipunkte obere rechte Ecke, dann "editieren" - alles gut :D In der Übersetzung klingt es echt gemein, ist aber eher ein freundlicher Hinweis :)

Sorry, but I don't know what I've done wrong! 
I don't know what to change!

**Comment by s-b-repo** [comment] 2024-09-25 22:12
> > This is probably related to #1916 and should be fixed in the library causing the issue according to [Hexer10/youtube_explode_dart#286](https://github.com/Hexer10/youtube_explode_dart/issues/286) Bumping the version and rebuilding spotube should resolve the problem - will try later.
> 
> I can confirm that updating `youtube_explode_dart: ^2.2.2` in `pubspec.yaml` and building the app solves the problem for me. I tried several songs and they all worked fine. Is it possible to release a new version of Spotube outside the release schedule with only this dependency changed to make the app usable again? Even if it does not seem to fix the problem for everyone (mentioned in [Hexer10/youtube_explode_dart#286](https://github.com/Hexer10/youtube_explode_dart/issues/286)), I think it would be better if at least some people could use the app.

we could make a hotfix release

**Comment by skruglov2023** [comment] 2024-09-25 23:02
+1 to having this issue, started last night

**Comment by pa88word** [comment] 2024-09-25 23:31
+1 to having this issue.

**Comment by certifiedfoolio** [comment] 2024-09-25 23:47
+1 songs load for a few seconds, then stops like it never happened, plz fix :)

**Comment by rigobersio** [comment] 2024-09-26 12:24
# Error Report 🛠️

**Date:** 24-09-2024  
**Platforms:** Android and Windows  
**Version:** v3.8.1 (Nightly Channel) and latest stable version of Spotube

---

## Description of the Problem

I confirm that the problem has been identified on both platforms. Song search works correctly, and there is access to the Spotify library, but the playback process has issues.

---

## Observed Behavior

- **Correct Playback:**  
  - **Artist:** A  
  - **Song:** 003  
  - **Genre:** Rock  

- **Incorrect Playback:**  
  - When searching:  
    - **Artist:** Z  
    - **Song:** 001  
    - **Genre:** Tango  
  - **Player Behavior:**  
    1. After finishing the last song from the album of the artist where it got stuck, the player begins to jump to other artists (B, C, D).
    2. Although playback is possible when the source is **JioSaavn**, it continues to play random songs from the same genre as the last correct playback instead of accessing the selected content from the search.

---

## Affected Sources

The error persists with any of the sources used by the program, including:
- YouTube
- Piped
- JioSaavn (where playback is possible, but it still does not play the selected content from the search).

---

## Summary

The issue lies in that, despite performing a specific search, the player remains stuck on the last correct playback and fails to access the new search, maintaining confusing behavior by jumping between artists and songs of the same genre.

I hope this additional information is helpful in resolving the issue. 😊

Best regards,  
**Rigoberto Martínez**
![errorSpotube_26-9-2024](https://github.com/user-attachments/assets/c0942f2b-1bdf-486a-8f7d-1661bb299b8d)

**Comment by aws1313** [comment] 2024-09-26 16:22
> > This is probably related to #1916 and should be fixed in the library causing the issue according to [Hexer10/youtube_explode_dart#286](https://github.com/Hexer10/youtube_explode_dart/issues/286) Bumping the version and rebuilding spotube should resolve the problem - will try later.
> 
> I can confirm that updating `youtube_explode_dart: ^2.2.2` in `pubspec.yaml` and building the app solves the problem for me. I tried several songs and they all worked fine. Is it possible to release a new version of Spotube outside the release schedule with only this dependency changed to make the app usable again? Even if it does not seem to fix the problem for everyone (mentioned in [Hexer10/youtube_explode_dart#286](https://github.com/Hexer10/youtube_explode_dart/issues/286)), I think it would be better if at least some people could use the app.

@KRTirtho would it be possible for you to publish a new version with just that dependency updated?

**Comment by s-b-repo** [comment] 2024-09-26 18:58
> > > This is probably related to #1916 and should be fixed in the library causing the issue according to [Hexer10/youtube_explode_dart#286](https://github.com/Hexer10/youtube_explode_dart/issues/286) Bumping the version and rebuilding spotube should resolve the problem - will try later.
> > 
> > 
> > I can confirm that updating `youtube_explode_dart: ^2.2.2` in `pubspec.yaml` and building the app solves the problem for me. I tried several songs and they all worked fine. Is it possible to release a new version of Spotube outside the release schedule with only this dependency changed to make the app usable again? Even if it does not seem to fix the problem for everyone (mentioned in [Hexer10/youtube_explode_dart#286](https://github.com/Hexer10/youtube_explode_dart/issues/286)), I think it would be better if at least some people could use the app.
> 
> @KRTirtho would it be possible for you to publish a new version with just that dependency updated?

just compile it from source but before you do the compileing update it

**Comment by aws1313** [comment] 2024-09-26 19:36
> > > > This is probably related to #1916 and should be fixed in the library causing the issue according to [Hexer10/youtube_explode_dart#286](https://github.com/Hexer10/youtube_explode_dart/issues/286) Bumping the version and rebuilding spotube should resolve the problem - will try later.
> > > 
> > > 
> > > I can confirm that updating `youtube_explode_dart: ^2.2.2` in `pubspec.yaml` and building the app solves the problem for me. I tried several songs and they all worked fine. Is it possible to release a new version of Spotube outside the release schedule with only this dependency changed to make the app usable again? Even if it does not seem to fix the problem for everyone (mentioned in [Hexer10/youtube_explode_dart#286](https://github.com/Hexer10/youtube_explode_dart/issues/286)), I think it would be better if at least some people could use the app.
> > 
> > @KRTirtho would it be possible for you to publish a new version with just that dependency updated?
> 
> just compile it from source but before you do the compileing update it

I did and it works for me, but many people do not have the needed knowledge for doing this themselves. For them it would be nice to have a fixed version.

**Comment by Lennonnag** [comment] 2024-09-26 20:06
> > > > > This is probably related to #1916 and should be fixed in the library causing the issue according to [Hexer10/youtube_explode_dart#286](https://github.com/Hexer10/youtube_explode_dart/issues/286) Bumping the version and rebuilding spotube should resolve the problem - will try later.
> > > > 
> > > > 
> > > > I can confirm that updating `youtube_explode_dart: ^2.2.2` in `pubspec.yaml` and building the app solves the problem for me. I tried several songs and they all worked fine. Is it possible to release a new version of Spotube outside the release schedule with only this dependency changed to make the app usable again? Even if it does not seem to fix the problem for everyone (mentioned in [Hexer10/youtube_explode_dart#286](https://github.com/Hexer10/youtube_explode_dart/issues/286)), I think it would be better if at least some people could use the app.
> > > 
> > > 
> > > @KRTirtho would it be possible for you to publish a new version with just that dependency updated?
> > 
> > 
> > just compile it from source but before you do the compileing update it
> 
> I did and it works for me, but many people do not have the needed knowledge for doing this themselves. For them it would be nice to have a fixed version.

I just need to update the pubscpec.yaml and compile?

**Comment by s-b-repo** [comment] 2024-09-26 20:33
> > > > > This is probably related to #1916 and should be fixed in the library causing the issue according to [Hexer10/youtube_explode_dart#286](https://github.com/Hexer10/youtube_explode_dart/issues/286) Bumping the version and rebuilding spotube should resolve the problem - will try later.
> > > > 
> > > > 
> > > > I can confirm that updating `youtube_explode_dart: ^2.2.2` in `pubspec.yaml` and building the app solves the problem for me. I tried several songs and they all worked fine. Is it possible to release a new version of Spotube outside the release schedule with only this dependency changed to make the app usable again? Even if it does not seem to fix the problem for everyone (mentioned in [Hexer10/youtube_explode_dart#286](https://github.com/Hexer10/youtube_explode_dart/issues/286)), I think it would be better if at least some people could use the app.
> > > 
> > > 
> > > @KRTirtho would it be possible for you to publish a new version with just that dependency updated?
> > 
> > 
> > just compile it from source but before you do the compileing update it
> 
> I did and it works for me, but many people do not have the needed knowledge for doing this themselves. For them it would be nice to have a fixed version.

true

**Comment by konashevich** [comment] 2024-09-26 22:35
same in windows. any solution yet?

**Comment by Hoosck** [comment] 2024-09-27 04:41
Same on android since september 24th

**Comment by Mark3xtrm** [comment] 2024-09-29 15:06
+1 Same on Linux Mint 21.3

**Comment by Renegade-Master** [comment] 2024-09-29 15:08
Temporary fix here. Android not working yet. Hopefully will get all platforms working at some point until @KRTirtho can release an official update.
https://github.com/Renegade-Master/spotube/releases

**Comment by FlowDownTheRiver** [comment] 2024-09-30 02:22
> Temporary fix here. Android not working yet. Hopefully will get all platforms working at some point until @KRTirtho can release an official update. https://github.com/Renegade-Master/spotube/releases

thanks for your contribution,in pc it works great,in android,it shows the album arts etc but unfortunately something is force closing it. Used device s24 ultra. I have given every permission to the app.

**Comment by MrPrezAtambaev** [comment] 2024-09-30 11:28
> Temporary fix here. Android not working yet. Hopefully will get all platforms working at some point until @KRTirtho can release an official update. https://github.com/Renegade-Master/spotube/releases

I installed your version, but the application shows version 3.8.1, maybe I should have deleted the old application and installed your version?

**Comment by kleyton67** [comment] 2024-09-30 11:33
https://github.com/Renegade-Master/spotube/releases/tag/v3.8.4 is working on Ubuntu 22. I didnt test it on android yet.

**Comment by KRTirtho** [comment] 2024-09-30 14:23
I was really busy with some personal life issues so I couldn't fix it. Sorry for the delay. I've merged the PR with fix. It should be released by tomorrow

**Comment by KRTirtho** [comment] 2024-09-30 14:23
Duplicate of #1916

**Closed by KRTirtho** 2024-09-30 14:23 UTC
Labels: bug

**Comment by FlowDownTheRiver** [comment] 2024-10-09 01:42
@KRTirtho After you made and update here : https://github.com/KRTirtho/spotube/releases/tag/v3.8.2
PC desktop and android version worked for a while,now it is not working again at date 09.10.2024.
Something is not working. Possibly other versions are broken too... If you have time can you take a look at it?
