### ISSUE TITLE
Lyrics Terrible

### ISSUE THREAD

**Issue by jeffdumcum** [KRTirtho/spotube#304] opened 2022-11-12 02:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The lyrics are most times wrong, and on the 0.00001% percent of the times where it is kind of correct, the lyrics are unsynced

### Expected Behavior

The lyrics to be correct and synced

### Spotube Version

idk

### Operating System

Android

### Operating System Version

Android 12

### Installation Source

F-Droid (Android)

**Comment by XenHat** [comment] 2022-11-17 20:03
Probably duplicate of #112 for the first part of the bug.

**Comment by KRTirtho** [comment] 2022-11-24 06:44
Props to the awesome title :joy:

**Closed** 2023-01-05 04:16 UTC
Labels: bug, duplicate, good first issue
