### ISSUE TITLE
[Duplicate] different track

### ISSUE THREAD

**Issue by koboingangkang** [KRTirtho/spotube#128] opened 2022-06-29 09:53 UTC
hey,

1. why songs played in spotube, different with ones I have in spotify playlist? 
ex song I have in my playlist is : https://open.spotify.com/track/476V2d6iA2tWXgQboKmTtA?si=a5d006a0c837402b
one in spottube played (from my playlist too) : https://open.spotify.com/track/20y3DqwhOEWft7nQncfc9O?si=34c810fa15b544e8
3. what is the function of "format of the YouTube Search Term" ? I try to make it blank, but all songs from my playlist turn to "Unconditionally" by Katy Perry

thanks for your great work.

**Comment by KRTirtho** [comment] 2022-06-30 16:03
duplicate of https://github.com/KRTirtho/spotube/issues/32

**Closed** 2023-01-05 04:16 UTC
Labels: bug, duplicate
