### ISSUE TITLE
Artist Page Shows Error 

### ISSUE THREAD

**Issue by mithu2649** [KRTirtho/spotube#1036] opened 2024-01-07 08:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error Message: "Type 'double' is not a subtype of 'int?' in type cast

 ![gif-20240107-133743](https://github.com/KRTirtho/spotube/assets/25825910/3c642a48-a77d-4bb1-be7b-a5cdb9b37d5f)

### Expected Behavior

Artist profile page

### Steps to reproduce

1. Open the app
2. Search for an artist
3. Click on any Artist

### Operating System

Android

### Spotube version

v3.4.0

### Installation source

GitHub Releases (Binary)

**Comment by dennisgit282** [comment] 2024-01-07 15:24
Are you sure you don't have a variable you just need to change to int to make things more consistent. Why would you need a double variable in this app. You would maybe have an int for the id of the song but double variables are more for like money and science.

**Comment by barthphi** [comment] 2024-01-08 08:25
I have same issue. Installation from play store

**Comment by abhinavanand-fed** [comment] 2024-01-08 09:58
I'm experiencing the same issue in the Nightly Build.
![image](https://github.com/KRTirtho/spotube/assets/110715459/d9f39e8e-dc63-43ab-aacc-5facea5a0503)

**Comment by g0-n** [comment] 2024-01-08 10:22
I'm also experiencing the same issue over the latest version. Playing songs from my playlists work just as expected though.

**Comment by clmaes** [comment] 2024-01-08 16:08
I have the same issue.

**Comment by g0-n** [comment] 2024-01-08 16:11
I downgrade back to v3.3.0 (Android) and now works fine.

**Comment by KRTirtho** [comment] 2024-01-08 16:11
Duplicate of #1018

**Closed** 2024-01-08 16:11 UTC
Labels: bug, potential-duplicate
