### ISSUE TITLE
how to login spotify to windows desktop

### ISSUE THREAD

**Issue by oliver-xie666** [KRTirtho/spotube#752] opened 2023-09-27 06:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i try using spotify login ,type sp_dc and sp_key, click the submit, There's no response，even error message

### Expected Behavior

i wish can login

### Steps to reproduce

see the Current Behavior

### Operating System

windows

### Spotube version

latest

### Installation source

GitHub Releases (Binary)

**Comment by KRTirtho** [comment] 2023-09-27 07:06
Not reproducible + no reproduction instructions. Thus closing

Tip!: You're probably pasting the wrong cookies. Please check thoroughly. Other it's a connection issue

**Closed by KRTirtho** 2023-09-27 07:06 UTC
Labels: bug

**Comment by UnoNYC** [comment] 2024-01-03 08:39
Hi, I just downloaded this for Windows, and I am having the same issue. I followed the instructions to the letter and it still isn't working.

When I put in the requested info, and submit it, the button turns gray for a bit, as if it is doing something and then it goes back to its original color without any change whatsoever. 

I have tried both ways, using the main screen, and from page 4 of the tutorial, and it still doesn't work.

I am using W10.

The Android app works fine on my tablet, so the problem is on Windows only.

Is it possible that this was mislabeled for a different version of Windows or a developer error?

Thank you for your time.
