### ISSUE TITLE
add proxy settings

### ISSUE THREAD

**Issue by zhulong333** [KRTirtho/spotube#1009] opened 2024-01-03 03:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Hello, is it possible to add the proxy function in the settings?

Thank you for your help!

### Suggested solution

No ideas at the moment

**Comment by KRTirtho** [comment] 2024-01-03 03:50
Duplicate of #88

**Closed by KRTirtho** 2024-01-03 03:50 UTC
Labels: enhancement
