### ISSUE TITLE
iOS app halts playback when sent to background mode

### ISSUE THREAD

**Issue by darkxdd** [KRTirtho/spotube#1157] opened 2024-01-26 13:27 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

Right now, when you switch the app to the background, it unexpectedly hits pause on the music.

### Expected Behavior

The app should continue playing music seamlessly even when it's pushed to the background.

### Steps to reproduce

1. Open the app and start playing music.
2. Navigate to another app or press the device's home button to send the app to the background.
3. Observed that the music playback stops unexpectedly.

### Operating System

iOS (15.7.7)

### Spotube version

latest release

### Installation source

GitHub Actions (Nightly Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Sakhalinfox** [comment] 2024-01-29 20:09
Can confirm this is an issue on Spotube v3.4.1 on iOS 17.3. Glancing through the code for iOS I think audio_service is being used and I was of the assumption that audio_service (https://pub.dev/packages/audio_service) allows running the audio in the background even with the screen turned off.

**Comment by powenn** [comment] 2024-02-01 04:20
https://github.com/KRTirtho/spotube/pull/1166

**Comment by Sakhalinfox** [comment] 2024-02-05 20:17
@powenn Thanks for sharing the pull request. I'm assuming it is pending review to be merged? 

Also, since audio_service is already being used, was the only the below addition to the plist files required to resolve this issue?:

`<key>UIBackgroundModes</key>
  <array>
    <string>audio</string>
  </array>`

Do you have a compiled iOS IPA that I can use to test. I am unable to generate a build on codemagic.

**Comment by powenn** [comment] 2024-02-06 01:23
https://github.com/powenn/spotube/releases/tag/3.4.1
```

	<key>UIBackgroundModes</key>
	<array>
		<string>audio</string>
		<string>fetch</string>
		<string>location</string>
		<string>processing</string>
		<string>remote-notification</string>
	</array>
```

**Comment by Sakhalinfox** [comment] 2024-02-06 12:46
> https://github.com/powenn/spotube/releases/tag/3.4.1
> 
> ```
> 
> 	<key>UIBackgroundModes</key>
> 	<array>
> 		<string>audio</string>
> 		<string>fetch</string>
> 		<string>location</string>
> 		<string>processing</string>
> 		<string>remote-notification</string>
> 	</array>
> ```

Hi Powen,

Thank you for the IPA! I ran it and it was able to successfully perform the background audio playback, even while the phone is locked. 

However, I also figured out one thing. I was able to modify the Info.plist of the compiled IPA from the stable iOS release version 3.4.1 and have background playback work with just the following addition to its Info.plist:


```
	<key>UIBackgroundModes</key>
	<array>
		<string>audio</string>
	</array>
```

I was able to then side load this and it worked fine. I do not believe the UIBackgroundmodes for fetch, location, processing and remote-notifications are required for this use cause. Please feel free to do the above and verify and let me know what you think.

**Comment by powenn** [comment] 2024-02-06 12:54
> > https://github.com/powenn/spotube/releases/tag/3.4.1
> > ```
> > 
> > 	<key>UIBackgroundModes</key>
> > 	<array>
> > 		<string>audio</string>
> > 		<string>fetch</string>
> > 		<string>location</string>
> > 		<string>processing</string>
> > 		<string>remote-notification</string>
> > 	</array>
> > ```
> 
> Hi @powenn
> 
> Thank you for the IPA! I ran it and it was able to successfully perform the background audio playback, even while the phone is locked.
> 
> However, I also figured out one thing. I was able to modify the Info.plist of the compiled IPA from the stable iOS release version 3.4.1 and have background playback work with just the following addition to its Info.plist:
> 
> ```
> 	<key>UIBackgroundModes</key>
> 	<array>
> 		<string>audio</string>
> 	</array>
> ```
> 
> I was able to then side load this and it worked fine. I do not believe the UIBackgroundmodes for fetch, location, processing and remote-notifications are required for this use cause. Please feel free to do the above and verify and let me know what you think.

Glad to see the test result 
yes , the others are not necessary , these modes will disable

**Comment by Sakhalinfox** [comment] 2024-02-06 21:05
@powenn Thank you!

**Comment by EnTaroAiur** [comment] 2024-02-21 02:56
Hi @powenn. When will the new release with ios background play be implemented?

**Comment by powenn** [comment] 2024-02-21 04:11
> Hi @powenn. When will the new release with ios background play be implemented?

I don't know, it's depends on when will this request being pulled or code update

**Comment by KRTirtho** [comment] 2024-02-24 15:25
Duplicate of #1061

**Closed by KRTirtho** 2024-02-24 15:25 UTC
Labels: bug
