### ISSUE TITLE
See other Spotify users' profiles

### ISSUE THREAD

**Issue by Porrumentzio** [KRTirtho/spotube#1792] opened 2024-08-14 22:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I cannot see other Spotify users' profiles, so their playlists and liked songs.

### Suggested solution

Develop API compatibility and an interface to do so.

### Self grab

- [X] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-08-15 14:55
Duplicate of #1299

**Closed by KRTirtho** 2024-08-15 14:55 UTC
Labels: enhancement
