### ISSUE TITLE
Songs buffer for infinite time

### ISSUE THREAD

**Issue by 123Sanyam123** [KRTirtho/spotube#1387] opened 2024-04-11 12:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sometimes with songs that have multiple versions etc (like taylor swift's, i could be wrong and it might just be doing it randomly with any song but this is what I noticed), the music player will keep on loading forever. Only way to resume songs is to play another one from playlists or liked songs.

### Expected Behavior

Songs should buffer for like 2-3 seconds max. If a match can't be found within 5-10 seconds, an error should come up telling us to choose the song from the Alternative Track Songs menu

### Steps to reproduce

1. Opened the app
2. played some songs
3. started buffering endlessly

### Operating System

Android, Windows 11

### Spotube version

v3.5.0

### Installation source

Play Store (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-04-11 14:56
Duplicate of https://github.com/KRTirtho/spotube/issues/870

**Closed by KRTirtho** 2024-04-11 14:56 UTC
Labels: bug
