### ISSUE TITLE
Download source incorrect

### ISSUE THREAD

**Issue by remclean** [KRTirtho/spotube#1684] opened 2024-07-04 12:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I download a song the only source it downloads from is the default source. If the default source is wrong you can't fix it.

### Expected Behavior

When downloading a song it should draw from whatever source you choose from the alternative track source feature.

### Steps to reproduce

1. Select song
2. Change track source
3. Download song
4. See that the downloaded song did not draw from chooses source.

### Operating System

Android 14

### Spotube version

v3.7.1

### Installation source

Play Store (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by djkac** [comment] 2024-07-04 14:55
Hi All, same thing is happening on windows and mac (latest spotube version) . Badly needed feature when looking to download extended mix  instead of radio version. btw Spotube rulez!

**Comment by KRTirtho** [comment] 2024-07-09 12:33
It's been fixed in the nightly version on PR #1687

**Comment by KRTirtho** [comment] 2024-07-09 12:34
Related to #1223

**Comment by KRTirtho** [comment] 2024-07-09 12:35
Actually,
Duplicate of #1223

**Closed by KRTirtho** 2024-07-09 12:35 UTC
Labels: bug
