### ISSUE TITLE
Different song playing when another song is supposed to be playing.

### ISSUE THREAD

**Issue by TheJosephKhong** [KRTirtho/spotube#135] opened 2022-07-05 16:06 UTC
Different song playing when another song is supposed to be playing.

I don't know what caused this.

Installation Source/Method

https://github.com/KRTirtho/spotube/releases/latest/download/Spotube-windows-x86_64-setup.exe
Desktop:

OS: Windows 10
![spotube_YiDnLzMDQg](https://user-images.githubusercontent.com/102836277/177370557-6f79ec9f-0b94-4e8e-b651-fb29bcfdabbd.png)

Version 21H2 (OS Build 19044.1766)

**Comment by KRTirtho** [comment] 2022-07-07 04:07
Duplicate of https://github.com/KRTirtho/spotube/issues/32

**Closed** 2022-07-07 04:07 UTC
Labels: bug, duplicate
