### ISSUE TITLE
Podcast support

### ISSUE THREAD

**Issue by pepershots** [KRTirtho/spotube#1482] opened 2024-05-06 11:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

IS there a Podcast section?

### Suggested solution

If no please add it

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-05-06 12:35
No. Podcasts are not supported yet. But, we're looking for alternatives.

Duplicate of #1214

**Closed** 2024-05-09 17:56 UTC
Labels: duplicate, enhancement
