### ISSUE TITLE
Taking too long to stream a song

### ISSUE THREAD

**Issue by singhh9596** [KRTirtho/spotube#510] opened 2023-05-15 17:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've been trying to play a song but seems like the app is having some trouble playing it. It takes a minute or so to load a song. I tried switching to low quality playbacks but the result remains same.but once the 1st song is loaded rest of the songs don't take much time to play.

### Expected Behavior

Progress icon keeps on loading

### Steps to reproduce

1. Opened the app
2. Played the random song/ playlist
3. Progress icon keeps loading for about a minute or so.

### Operating System

Android

### Spotube version

V2.7.1

### Installation source

F-Droid (Android)

**Comment by owencz1998** [comment] 2023-05-27 11:36
Being fixed

**Comment by singhh9596** [comment] 2023-05-27 11:40
> Being fixed

I appreciate it.

**Comment by KRTirtho** [comment] 2023-05-27 16:35
Duplicate of https://github.com/KRTirtho/spotube/issues/480

**Comment by KRTirtho** [comment] 2023-05-27 16:36
Please continue conversion/enquiries there

**Closed by KRTirtho** 2023-05-27 16:36 UTC
Labels: bug, duplicate
