### ISSUE TITLE
type 'double' is not a subtype of type 'int?' in type cast

### ISSUE THREAD

**Issue by EleRam** [KRTirtho/spotube#1046] opened 2024-01-09 19:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello
I tried to search for an artist and a blank page with an error appeared. 

### Expected Behavior

Showing artist page.

### Steps to reproduce

1. I went to search page.
2. Typed for an artist: "Shahram Nazeri".
3. Scrolled to view `Artists` section.
4. Tapped on desired artist.
5. View the error instead of artist page.
![Screenshot_2024-01-09-22-33-54-659_oss krtirtho spotube](https://github.com/KRTirtho/spotube/assets/3352418/1298a0b5-80be-4429-9bfa-e53313e658b2)

### Operating System

Android 

### Spotube version

v3.4.0

### Installation source

F-Droid (Android)

**Comment by m7d2** [comment] 2024-01-10 06:06
Same behavior happens when you click on artist name from the currently playing track and if you try to click on the artist name directly from the track list.

**Comment by taha-ghadirian** [comment] 2024-01-10 06:33
Duplicate https://github.com/KRTirtho/spotube/issues/978

**Comment by AriyanMushtaq** [comment] 2024-01-10 18:08
Same problem happens when I trying to open album of the artist 
![Screenshot_2024-01-10-23-14-37-031_oss krtirtho spotube](https://github.com/KRTirtho/spotube/assets/156232327/1b7dcc8c-668d-4622-977b-f9aa8e0ed14a)

**Comment by UnoNYC** [comment] 2024-01-15 04:52
The same thing happens to me whenever I search for anything in the Android app. It will first show the search results, but once I click on one of them, you will see the next page results for a second before it goes blank leaving only the message above.

This happens with the playlist page as well when you click on the artist of a song.

**Comment by taha-ghadirian** [comment] 2024-01-15 05:09
> The same thing happens to me whenever I search for anything in the Android app. It will first show the search results, but once I click on one of them, you will see the next page results for a second before it goes blank leaving only the message above.
> 
> This happens with the playlist page as well when you click on the artist of a song.

Hello, you can refer to #1018 for more information.

**Comment by KRTirtho** [comment] 2024-01-22 11:54
Duplicate of #1018

**Closed by KRTirtho** 2024-01-22 11:54 UTC
Labels: bug
