### ISSUE TITLE
Add Rich Presence for Mobile

### ISSUE THREAD

**Issue by driftedawqy** [KRTirtho/spotube#1964] opened 2024-10-05 15:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

it's kinda self explanatory

### Suggested solution

no clue im the original suggestor of discord rpc though

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Erwin-Iosef** [comment] 2024-10-07 13:15
I'd love to have this feature enabled as well!

**Comment by KRTirtho** [comment] 2024-10-10 16:03
Duplicate of #1053

**Comment by KRTirtho** [comment] 2024-10-10 16:06
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues

![Stop lying man](https://github.com/user-attachments/assets/728c36f0-f5bc-49b2-b6f8-dc32e1cc92b1)

**Closed** 2024-10-10 16:07 UTC
Labels: duplicate, enhancement
