### ISSUE TITLE
Songs are not playing as long as they should

### ISSUE THREAD

**Issue by Juna-2006** [KRTirtho/spotube#1230] opened 2024-02-12 11:43 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

some songs are only 2-3 minutes long yet the app plays 1 hour long loops of them. sometimes the app will only play a small part of the song before skipping to the next one. The issue has occurred only on specific songs. example, the imagine dragons song, "Bones" is nearly 3 minutes long but only the first 46 seconds of it play before the app skips to the next track and the song, "Destroyer of Worlds" is nearly 3 minutes long yet the app plays a 1 hour loop of it everytime.

### Expected Behavior

the song should play only as long as it is. the app shouldn't play 1 hour loops of songs or skip a song midway.

### Steps to reproduce

1)I opened the app (mobile version)
2) I played a song from my playlist, specifically "Bones" by Imagine Dragons
3) the app only played the first 46 seconds of the song before skipping to the next track
4) when I played the song, "destroyer of worlds", the app played a 1 hour long loop of it despite the song being only 3 minutes long

### Operating System

Android 10

### Spotube version

v3.4.1

### Installation source

Play Store (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by armanleft** [comment] 2024-02-13 07:07
I thing this is because some songs plays from Alternative Track Source, that is a different song.
same issue I mentioned [here](https://github.com/rinukkusu/spotify-dart/issues/194)

**Comment by KRTirtho** [comment] 2024-02-17 16:48
Duplicate of #883

**Closed by KRTirtho** 2024-02-17 16:48 UTC
Labels: bug
