### ISSUE TITLE
Spotube only showing blank/transparent screen (NOT FIXED)

### ISSUE THREAD

**Issue by charlixcx-droid** [KRTirtho/spotube#1812] opened 2024-08-23 14:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

V3.8.0: I cant see a single thing on the spotube app
v3.7.1: The app works but i had this one song that has all the lyrics but suddenly the lyrics menu said "No lyrics for this song"

### Expected Behavior

i dont really expect anything

### Steps to reproduce

1 i opened the app. 2. nothing shows up + there is no issue like this when i searched it

### Operating System

Windows 10 (version 1909)

### Spotube version

v3.8.0+33, v3.7.1+31

### Installation source

GitHub Releases (Binary)

### Additional information

how do i fix it 😢

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by josejmm** [comment] 2024-08-24 09:56
Operating System: macOS Big Sur
I installed the macOS app and following all the steps. 
When I clicked the Spotify button, then appeared the gray screen.
Then, I closed the app and started again. Everything is working.
Many thanks for the app.

**Comment by KRTirtho** [comment] 2024-08-24 14:15
Duplicate of #1800

**Closed by KRTirtho** 2024-08-24 14:15 UTC
Labels: bug
