### ISSUE TITLE
cannot install v2 on android 12

### ISSUE THREAD

**Issue by danielphan2003** [KRTirtho/spotube#39] opened 2022-03-24 16:58 UTC
**Describe the bug**
I downloaded the arm64 version on GitHub releases and tried to install it but failed 

**To Reproduce**
1. Go to GitHub releases
2. Download arm64 android version
3. Install apk via Package Installer, or via SAI (split apk installer) which also contains error logs.
4. See error:
```
Rooted installer error:

 Device: Redmi Redmi Note 9S | Not MIUI | Android 12 | Using FilterApkSource ApkSource implementation | SAI 4.5

APK manifest is malformed

Command: pm install-commit 1618081676
Exit code: 1
Out:
Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1618081676.tmp/base.apk (at Binary XML file line #71): com.ryanheise.audioservice.AudioService: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]
=============
Err:
```

**Expected behavior**
Spotube should be installed.

**Screenshots**
![Screenshot_20220324-235526_Quickstep](https://user-images.githubusercontent.com/34669737/159969422-966ea9bf-cfc3-4a4e-a94e-863dbbbb340c.png)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 9S
 - OS: Android 12
 - Version 2.0.0

**Comment by KRTirtho** [comment] 2022-03-24 17:06
Duplicate of #38

**Comment by KRTirtho** [comment] 2022-03-25 13:54
Android 12 support has arrived. Please Download & install the latest .apk from the release

**Closed** 2022-03-26 04:03 UTC
Labels: bug
