### ISSUE TITLE
Only the first 4 lines of lyrics are shown

### ISSUE THREAD

**Issue by xCeeTee** [KRTirtho/spotube#1540] opened 2024-05-31 10:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

So I know Spotify removed lyrics for free some time ago, although they do show the first four lines. A few days ago the app was showing all of the lyrics but today I'm only getting the first four lines. I haven't updated the app either.

### Expected Behavior

I expect to see all of the lyrics as reported via the Musixmatch.com api. 

### Steps to reproduce

1. Open app
2. Play song
3. Press "see lyrics"

### Operating System

Windows 10 

### Spotube version

3.6.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-06-01 05:46
Duplicate of #1461

**Closed by KRTirtho** 2024-06-01 05:46 UTC
Labels: bug
