### ISSUE TITLE
[Bug] ERR_CONNECTION_REFUSED & ERR_CONNECTION_TIMED_OUT on Android

### ISSUE THREAD

**Issue by DanceOfEternity** [KRTirtho/spotube#195] opened 2022-09-05 22:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I did everything by looking at the guide and I checked and I'm sure I did it right if I try to connect my spotify account while on Android I get this error at localhost:4304/auth/spotify/callback
When I refresh the page sometimes I get the error ERR_CONNECTION_REFUSED and sometimes ERR_CONNECTION_TIMED_OUT

### Expected Behavior

Same as #17 but on Android

### Spotube Version

v2.3.0

### Operating System

Android

### Operating System Version

Android 11

### Installation Source

Github Release (Binary)

**Comment by KRTirtho** [comment] 2022-09-08 16:43
duplicate of #152

**Closed** 2022-09-30 02:06 UTC
Labels: bug, duplicate, good first issue

**Comment by KRTirtho** [comment] 2022-10-03 15:20
@DanceOfEternity see https://github.com/KRTirtho/spotube/issues/152#issuecomment-1265625104
