### ISSUE TITLE
Alternative track feature

### ISSUE THREAD

**Issue by AwesomeGamerAW** [KRTirtho/spotube#1054] opened 2024-01-11 21:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i change the track through that feature cuz it picked a wrong one, close the app and open it, it goes back to the wrong track

### Expected Behavior

when i change the track through that feature, close the app and open it, it stays as i picked earlier

### Steps to reproduce

1- open the app
2- change track through "Alternative track feature"
3- close the app and reopen it
4- the track goes back to the wrong one

### Operating System

all

### Spotube version

v3.4.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

**Comment by KRTirtho** [comment] 2024-01-27 14:59
Duplicate of #840

**Closed by KRTirtho** 2024-01-27 14:59 UTC
Labels: bug
