### ISSUE TITLE
Error Authentication Failure

### ISSUE THREAD

**Issue by jeec** [KRTirtho/spotube#972] opened 2023-12-30 04:17 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

![Screenshot 2023-12-30 at 12 12 02](https://github.com/KRTirtho/spotube/assets/10796826/89c7d726-3250-441a-a05e-995afacbf347)

### Expected Behavior

log in

### Steps to reproduce

follow the instruction

### Operating System

Mac OS  14.1.2 

### Installation source

GitHub Releases (Binary)

**Comment by happyeverydays414** [comment] 2023-12-30 10:52
me too same problem with macos 12.6.7 with m1max 
my spotube version is v3.3.0

**Comment by happyeverydays414** [comment] 2023-12-30 11:04
but on intel mac with os catalina this problem can be solved through clash x pro(enhanced mode)

**Comment by QiKe-007** [comment] 2024-01-01 03:48
I had the same problem with Windows 10

**Comment by KRTirtho** [comment] 2024-01-01 03:55
@QiKe-007 follow this thread for your issue #905 
It's usually outdated ssl certificates and you probably need to update Windows

**Comment by KRTirtho** [comment] 2024-01-03 07:47
Duplicate of #930

**Closed by KRTirtho** 2024-01-03 07:47 UTC
Labels: bug, potential-duplicate

**Comment by tychoon** [comment] 2024-01-21 18:52
me too. Authentication Failure

**Comment by ushishishishishi** [comment] 2024-01-23 12:35
same error here with macos 12.3 M1
