### ISSUE TITLE
The artist's page takes forever to load

### ISSUE THREAD

**Issue by Ardub92** [KRTirtho/spotube#1049] opened 2024-01-11 07:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The page loads endlessly even after two minutes. The whole app works fine, but except for this page.

Might be related or duplicate of #1018, but I expirience different behaviour.

### Expected Behavior

Artist page to load.

### Steps to reproduce

1. Go to search and find any artist.
2. Click on it.

### Operating System

Android

### Spotube version

3.2.0

### Installation source

F-Droid (Android)

**Comment by shygamer123** [comment] 2024-01-11 11:45
does work well....no issues, can u send a video on discord:- prathamm_gupta

**Comment by KRTirtho** [comment] 2024-01-22 11:52
Duplicate of #1018

**Closed by KRTirtho** 2024-01-22 11:52 UTC
Labels: bug
