### ISSUE TITLE
Unable to play background 

### ISSUE THREAD

**Issue by sanups90** [KRTirtho/spotube#2091] opened 2024-11-28 08:45 UTC
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

The app can't perform background play.  The app will minimise automatically closing 

### Expected Behavior

Need to rectify this.. need a smoothly and continuous playing 

### Steps to reproduce

1.open app 2. Select song 3. Playing started 4. Press back button 
5. App closed.. stopped working ( Playing)

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

Android 

### Spotube version

v3.8.3

### Installation source

Website (spotube.krtirtho.dev), GitHub Releases (Binary), GitHub Actions (Nightly Binary), Play Store (Android), F-Droid (Android), Arch User Repository (AUR), Flathub (Flatpak), chocolatey (Windows), WinGet (Windows), Scoop (Windows)

### Additional information

Please rectify this issue 

### Self grab

- [X] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-12-01 11:58
Duplicate of #1366

**Closed by KRTirtho** 2024-12-01 11:58 UTC
Labels: bug

**Comment by sanups90** [comment] 2024-12-01 12:02
Closed without solve
