### ISSUE TITLE
Songs stuck at 0:00

### ISSUE THREAD

**Issue by Happyfeet01** [KRTirtho/spotube#630] opened 2023-08-15 06:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

hello,

I have installed on my Google Pixel 6 Pro Spotube. Yesterday I have played some songs, but now I have no sound in this App. I can see the music playing but I can't hear anything. The logs show the following

```------- DEVICE INFO -------
id: TQ3A.230705.001.A1
board: raven
bootloader: slider-1.2-9883526
brand: google
device: raven
display: TQ3A.230705.001.A1
fingerprint: google/raven/raven:13/TQ3A.230705.001/10216780:user/release-keys
hardware: raven
host: android-build
isPhysicalDevice: true
manufacturer: Google
model: Pixel 6 Pro
product: raven
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: eng.nobody.20230715.190317
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-07-05
------- APP INFO -------
environment: release
version: 3.0.1
appName: Spotube
buildNumber: 97
packageName: oss.krtirtho.spotube
---------- ERROR ----------
DioException [bad response]: The request returned an invalid status code of 504.
------- STACK TRACE -------
#0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:507)
#1      _RootZone.runUnary (dart:async/zone.dart:1661)
#2      _FutureListener.handleError (dart:async/future_impl.dart:165)
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:796)
#4      Future._propagateToListeners (dart:async/future_impl.dart:817)
#5      Future._completeError (dart:async/future_impl.dart:592)
#6      _SyncCompleter._completeError (dart:async/future_impl.dart:51)
#7      _Completer.completeError (dart:async/future_impl.dart:23)
#8      Future.any.onError (dart:async/future.dart:620)
#9      _RootZone.runBinary (dart:async/zone.dart:1666)
#10     _FutureListener.handleError (dart:async/future_impl.dart:162)
#11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:796)
#12     Future._propagateToListeners (dart:async/future_impl.dart:817)
#13     Future._completeError (dart:async/future_impl.dart:592)
#14     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:537)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
------- CUSTOM INFO -------```

### Expected Behavior

If the error is fixed, you should be able to play the music without problems. 

### Steps to reproduce

1. Open the App
2. Sign up for Spotify
3. Try playing music 

### Operating System

Android

### Spotube version

13

### Installation source

GitHub Releases (Binary)

### Additional information

_No response_

**Comment by KRTirtho** [comment] 2023-08-15 06:14
Piped APIs are down due to an recent YouTube API change that returns 403 (Forbidden) error for any YouTube video/audio stream
Same issue was on unofficial youtube API client (YouTubeExplode.dart) old version. Luckily, youtube _explode.dart fixed the issue in their library & the streams are now working

So update is now available on [Nightly](https://spotube.netlify.app/other-downloads/nightly-downloads)
Just go to "Setting" > "API Type"  & change it to "YouTube" from "Piped" to get everything working again

**Comment by KRTirtho** [comment] 2023-08-15 06:15
The piped API depends on https://github.com/TeamPiped/Piped developers. They need to fix & update the backend

**Comment by Happyfeet01** [comment] 2023-08-15 06:18
Okay thanks, good to know. 👍

**Comment by Happyfeet01** [comment] 2023-08-15 06:35
@KRTirtho Maybe this Fix? https://github.com/TeamNewPipe/NewPipeExtractor/pull/1084

**Comment by KRTirtho** [comment] 2023-08-15 07:17
Not sure

**Comment by jazznfunk** [comment] 2023-08-15 08:21
Thanks! I can confirm that Nightly + Piped => Youtube works on Linux Mint 21 and Android 12 phone!

**Comment by TBNRDev** [comment] 2023-08-15 15:37
Hello, looks like it's not fixed yet but the simple fix is to change the Piped Instance to the working API of Piped, the working one that i found is api.piped.ProjectSegFau.lt (projectsegfau.lt us)

**Comment by Vitalya-code** [comment] 2023-08-16 12:21
The "projectsegfau.lt" is working for me, thank you

**Comment by VXEAD** [comment] 2023-08-16 21:45
> Piped APIs are down due to an recent YouTube API change that returns 403 (Forbidden) error for any YouTube video/audio stream Same issue was on unofficial youtube API client (YouTubeExplode.dart) old version. Luckily, youtube _explode.dart fixed the issue in their library & the streams are now working
> 
> So update is now available on [Nightly](https://spotube.netlify.app/other-downloads/nightly-downloads) Just go to "Setting" > "API Type" & change it to "YouTube" from "Piped" to get everything working again

i have same problem 
![image](https://github.com/KRTirtho/spotube/assets/103393069/6316a092-bc54-44e7-a312-3e7841164dae)
![image](https://github.com/KRTirtho/spotube/assets/103393069/e056839e-392a-4d8c-9436-51cf218cd3e1)
i make like u said + that was defaults setting. but i cant hear anything

**Comment by VXEAD** [comment] 2023-08-16 21:57
> Piped APIs are down due to an recent YouTube API change that returns 403 (Forbidden) error for any YouTube video/audio stream Same issue was on unofficial youtube API client (YouTubeExplode.dart) old version. Luckily, youtube _explode.dart fixed the issue in their library & the streams are now working
> 
> So update is now available on [Nightly](https://spotube.netlify.app/other-downloads/nightly-downloads) Just go to "Setting" > "API Type" & change it to "YouTube" from "Piped" to get everything working again

TBH i cant listen music on differents API, idk why, im just installed Spotube, and thying listening. I choose one right API, and then he broken

**Comment by TBNRDev** [comment] 2023-08-17 09:26
> 

try projectsegfau.lt us server

**Comment by KRTirtho** [comment] 2023-08-19 06:16
In my case **drgns.space** also worked if anyone needed in case

**Comment by KRTirtho** [comment] 2023-08-19 06:17
v3.1.0 now uses YouTube API by default now. Also it'll warn user if it detects any of the instance doesn't work

**Comment by KRTirtho** [comment] 2023-08-26 03:59
I'm closing this issue as it's fixed & released
_piped_ related issues can be tracked in https://github.com/TeamPiped/Piped repository

**Closed** 2023-08-26 03:59 UTC
Labels: bug
