### ISSUE TITLE
Use system proxy if one detected

### ISSUE THREAD

**Issue by Anime-Forevere** [KRTirtho/spotube#1951] opened 2024-10-02 16:46 UTC
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

Spotube doesn't use system proxy

### Expected Behavior

Spotube uses system proxy if one detected

### Steps to reproduce

1. Open app
2. Spotube should use system proxy for all connections

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

Windows 10

### Spotube version

v3.8.2

### Installation source

GitHub Releases (Binary)

### Additional information

I'm new to spotube and was confused firstly because I logged in with my spotify (through integrated browser with proxy) but spotube couldn't retrieve my playlists. In issues, I found a proxy parameter, it allows spotube to fetch my playlists, but doesn't play songs (it tries to play them, but can't and starts to go through all of them trying to play them which causes the app to start lagging).

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Mahantor** [comment] 2024-10-03 02:36
i have same problem
and 3.8.2 version notworking
still i have endless loading issue

**Comment by KRTirtho** [comment] 2024-10-03 04:03
Duplicate of #88

**Comment by KRTirtho** [comment] 2024-10-03 04:03
Please at least try searching. There's already like 5 different open issues for it.
It only waste our time for actual development, if the maintainers only closing duplicate issues

**Closed by KRTirtho** 2024-10-03 04:03 UTC
Labels: bug

**Comment by Anime-Forevere** [comment] 2024-10-03 14:41
> Please at least try searching. There's already like 5 different open issues for it. It only waste our time for actual development, if the maintainers only closing duplicate issues

Sorry for wasting your time, as I saw there are proxy parameters in that issue (HTTP_PROXY and etc), I thought you could implement auto detection for system proxy.

**Comment by Mahantor** [comment] 2024-10-04 07:25
Steps to reproduce

   1. Open app
   2.  Spotube should use system proxy for all connections

I did this but unfortunately it doesn't work properly (I have done this with several other vpn's as well)

https://github.com/user-attachments/assets/e7aa5341-b4c5-4612-b9e2-7a3efddc1a75
