### ISSUE TITLE
[Feature] Play from local copy if track exists on storage instead of streaming

### ISSUE THREAD

**Issue by famewolf** [KRTirtho/spotube#223] opened 2022-09-19 17:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Category of the Feature

More Efficiency

### Credits

Myself

### Pain

For those on limited bandwidth playing from the local copy instead of additional downloading will cut down on the data required as well as having less gaps in music being played in areas of poor connectivity.

### Suggested Solution

Check if the track from the current playlist exists on storage in download location and if so play that version.

**Comment by Alliba** [comment] 2022-09-21 19:26
Yes that would be really awesome this function instead of streaming the song over and over again.

Otherwise a really great app.

**Comment by vico93** [comment] 2023-08-28 19:20
This and the ability to load from subfolders would be a crucial change for me to ditch WMP completely (basically #595)

**Comment by Karol-G** [comment] 2023-10-08 12:36
Hey,

This is also something I wish would be possible. Especially in areas where there is simply no internet this would be quite benefitial as that would enable the user to use Spotube as usual if some or all playlists have been downloaded previously.

@KRTirtho Is this feature on your roadmap? It would be a really cool feature! :)

Best,
Karol

**Comment by jeaye** [comment] 2024-04-15 01:57
I just installed spotube on my Android device, with the plan of taking my spotify playlists, downloading them locally, and then being able to play them while I'm driving. Looks like spotube doesn't support this workflow right now, but it would surely be amazing. Sounds like it'd require:

1. Downloading all tracks on a spotify playlist locally
2. Allow syncing with the spotify playlist, to download new songs as they're added
3. Use the local version of the song when playing from the playlist
4. If a local version isn't available and the phone is offline, skip to the next local song

I'm not sure why others want this, but I thought it might be helpful to explain the goal I had in mind. Thanks so much for spotube! :heart:

**Comment by u1b4n** [comment] 2024-06-04 12:28
+1
If this feature is added, please also consider adding an icon that shows if the song/playlist is already downloaded. I don't know how many times I clicked "Download track" only to be informed that I already downloaded the song. ^^

**Comment by KRTirtho** [comment] 2024-08-13 17:01
Duplicate of #127

**Comment by KRTirtho** [comment] 2024-08-13 17:01
I never realized there was already a parent issue. But, the support is coming soon!

**Closed by KRTirtho** 2024-08-13 17:01 UTC
Labels: enhancement
