### ISSUE TITLE
Add a equalizer option like in youtube music and spotify

### ISSUE THREAD

**Issue by ItzMarioPlayz12** [KRTirtho/spotube#735] opened 2023-09-19 01:24 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Pain

i cannot use equalizer like in spotify

### Suggested solution

Add one :))

**Comment by KRTirtho** [comment] 2023-09-19 11:01
duplicate of #465

**Closed by KRTirtho** 2023-09-19 11:01 UTC
Labels: duplicate, enhancement
