### ISSUE TITLE
Non-English text is garbled sometimes (non-ASCII mojibake)

### ISSUE THREAD

**Issue by JapanYoshi** [KRTirtho/spotube#1475] opened 2024-05-04 14:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot_20240504-232048](https://github.com/KRTirtho/spotube/assets/8707990/05d86144-56ac-4a3d-84b0-5b582da1ae0d)

As you can see in the screenshot, all non-English text (more precisely, every non-ASCII character) is garbled by the app.

A quick bit of research shows that `ä»¤` is the result of mis-interpreting `令` in `令和ポップス`, and that the app mis-interprets UTF-8 encoded bytes as Latin-1 (an ancient encoding that nobody serious uses today except where backwards-compatibility with 90s-2000s computer programs is critical).

![Screenshot_20240504-232905](https://github.com/KRTirtho/spotube/assets/8707990/bf95992a-a3fa-47d1-9042-f8e0f3d952b6)

Oddly enough, some sections are correctly displaying Japanese text, including the same album I used as an example! The use of Latin-1 seems not to be a hard-coded choice, but a mistake in character encoding detection somewhere. I couldn’t imagine Spotify’s API changing character encodings on the fly like that, so forcing UTF-8 should work 100% correctly.

### Expected Behavior

Non-ASCII text should display correctly as UTF-8 encoded text. There must be an error introduced somewhere between receiving the data from Spotify’s API and displaying the text on screen. Perhaps some parsing function detects some UTF-8 text as Latin-1, and must be told to always use UTF-8?

### Steps to reproduce

1. Open the app
2. Log into Spotify if not already done so
3. Make the app display non-ASCII text

### Operating System

Android

### Spotube version

v3.6.0

### Installation source

F-Droid (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by HUYDGD** [comment] 2024-05-06 03:03
same bug happened to me

**Comment by UlyC** [comment] 2024-05-07 02:43
same  bug

**Comment by SuTree** [comment] 2024-05-08 09:28
same bug

**Comment by KRTirtho** [comment] 2024-05-09 18:06
Duplicate of #1463

**Closed by KRTirtho** 2024-05-09 18:06 UTC
Labels: bug
