### ISSUE TITLE
bug on the  flatpak version

### ISSUE THREAD

**Issue by lessan-cyber** [KRTirtho/spotube#1563] opened 2024-06-03 19:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i have update spotube today and i am experiencing a bug on it . i have install it with flatpak. when i trying to launch it i have an error that says there is an error with the proxy or something like that

### Expected Behavior

I hope you will be able to fix that very soon

### Steps to reproduce

1 i update the app
2 i try to open it and it didn't work
3 i try to open it for flatpak software store on my computer and it display that there an issue with the proxy

### Operating System

linuxgWrite the title here

### Spotube version

3.7.0

### Installation source

Flathub (Flatpak)

### Additional information

i really like your app

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Arthurdw** [comment] 2024-06-05 07:46
This is probably related/the same as #1564

**Comment by KRTirtho** [comment] 2024-06-05 11:57
Duplicate of #1555

**Closed by KRTirtho** 2024-06-05 11:57 UTC
Labels: bug, duplicate
