### ISSUE TITLE
Wrong update message when I start Spotube.

### ISSUE THREAD

**Issue by thedragon40** [KRTirtho/spotube#1674] opened 2024-06-28 13:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I start Spotube it shows me this message, I update it and I still get this.
![Captura de pantalla 2024-06-28 151800](https://github.com/KRTirtho/spotube/assets/87898162/6cf0bb16-3412-4e60-bb05-930bc8fc6fb8)

### Expected Behavior

Well, let it update without problems.

### Steps to reproduce

1. Open the application
2. Wait for it to start.
3. He already shows it to you.

### Operating System

Windows

### Spotube version

3.7.0

### Installation source

WinGet (Windows)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by OfficialMuffin** [comment] 2024-06-28 19:23
Same here, both with the website download and the github .exe

**Comment by mfaathirarsa** [comment] 2024-06-28 23:10
This is a duplicate of #1595

**Comment by Peperehobbits01** [comment] 2024-07-01 08:46
Like @mfaathirarsa this bug as already been reported, meaning you haven't searched the existing issues or didn't see it, but it's fine. Could you please close this issues to help developers go trhow issues faster and fixing bugs more efficently. Thanks you 😉

**Comment by KRTirtho** [comment] 2024-07-09 12:42
Duplicate of #1595

**Closed by KRTirtho** 2024-07-09 12:42 UTC
Labels: bug
