### ISSUE TITLE
Won't load anything in Library except for Liked Tracks

### ISSUE THREAD

**Issue by TotallyNotK0** [KRTirtho/spotube#1409] opened 2024-04-15 16:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using Spotube, nothing loads in the Library section except for Liked Tracks. None of my other playlists are present.

### Expected Behavior

To be able to see my playlists and select them to play my songs.

### Steps to reproduce

1. Open the application
2. Wait

### Operating System

Linux Mint 21.3 x86_64

### Spotube version

v3.6.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-04-16 14:58
Duplicate of #1403

**Closed** 2024-04-16 14:58 UTC
Labels: bug, duplicate
