### ISSUE TITLE
V3.4.0: Albums & Artists don't display

### ISSUE THREAD

**Issue by GrampaWildWilly** [KRTirtho/spotube#1136] opened 2024-01-24 09:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I click on Library it shows my playlists.  When I then click on either Artists or Albums at the top, it never shows anything.  I left it sit for at least a half hour & it never completed.  I even had the heart-stopping experience of it saying I had no playlists.  Fortunately, closing & reopening Spotube made them reappear.

### Expected Behavior

I am quite new to this product so my expectations are not based on what I have seen before.  They are based on an intuitive expectation of what I think the buttons ought to do.  I think the functions are supposed to comb through my selected playlist & show me, respectively, all the artists in my playlist & all the albums in my playlist.

### Steps to reproduce

1. I opened the app.  Can't we sort of assume this step?
2. I clicked Library.
3. I click Artists at the top.  Separately, I clicked Albums at the top.

### Operating System

Windows 11 Pro 64-bit version 23H2 build 22631.3085

### Spotube version

V3.4.0

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-01-24 12:03
Duplicate of #1018

**Comment by KRTirtho** [comment] 2024-03-12 14:34
Fixed in 3.50

**Closed by KRTirtho** 2024-03-12 14:34 UTC
Labels: bug
