### ISSUE TITLE
Automatically Permanently Remember Alternative Song Source

### ISSUE THREAD

**Issue by fleamour** [KRTirtho/spotube#1127] opened 2024-01-23 12:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Not all song results are 100% accurate from Spotify playlist.

### Suggested solution

I would like option to permanently set & forget alternative song source. 

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-01-27 14:57
It's a bug actually. During refactoring this bug happend

**Comment by KRTirtho** [comment] 2024-01-27 14:58
Duplicate of #840

**Closed by KRTirtho** 2024-01-27 14:58 UTC
Labels: bug
