### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by my999god** [KRTirtho/spotube#1301] opened 2024-03-08 08:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="789" alt="image" src="https://github.com/KRTirtho/spotube/assets/29770935/f97892be-74ac-40c7-ac54-442334ea79d4">

### Expected Behavior

Authentication successful

### Steps to reproduce

1. Install the latest version of the software mac
2. 按照指南使用sp_dc的cookie               
3. 提示认证错误         

### Operating System

macos

### Spotube version

3.4.1

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-03-08 10:59
Duplicate of #930 #905

**Comment by KRTirtho** [comment] 2024-03-08 11:00
Don't share the sp_dc cookie. Anyone can access your account now

**Closed by KRTirtho** 2024-03-08 10:59 UTC
Labels: bug
