### ISSUE TITLE
Grey screen

### ISSUE THREAD

**Issue by sasoriza** [KRTirtho/spotube#1285] opened 2024-03-01 02:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want to use this app and am getting a grey screen
![Unbenannt](https://github.com/KRTirtho/spotube/assets/2168304/43ba49be-3c2d-439a-b581-f7c73faf94ac)

### Expected Behavior

I shouldn't be getting a grey screen

### Steps to reproduce

1. open the app
2. use it for some time
3. search for a song /band
4. try to open that song / band page

### Operating System

Windows

### Spotube version

3.4.1

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Bowarc** [comment] 2024-03-01 12:14
I have the same problem, artist pages are gray

**Comment by KRTirtho** [comment] 2024-03-01 12:52
Issue on Spotify endpoint https://github.com/rinukkusu/spotify-dart/issues/207

**Comment by KRTirtho** [comment] 2024-03-01 12:54
Duplicate of #1282

**Closed by KRTirtho** 2024-03-01 12:54 UTC
Labels: bug
