### ISSUE TITLE
Still not open at Windows 11

### ISSUE THREAD

**Issue by cutydina** [KRTirtho/spotube#1771] opened 2024-08-11 18:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

App wont launch on Windows 11

### Expected Behavior

Open APP

### Steps to reproduce

Download any version above 3.6.0, this is the last one that can be open on Windows 11, so can't update with new versions :(

### Operating System

Windows 11

### Spotube version

from version 3.7 upwards

### Installation source

Website (spotube.krtirtho.dev), GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-08-12 03:09
Duplicate of #1578

**Closed by KRTirtho** 2024-08-12 03:09 UTC
Labels: bug

**Comment by Evoke-W** [comment] 2024-08-13 08:31
v3.7.0 can launch on Windows 11
