### ISSUE TITLE
Scrolling bug

### ISSUE THREAD

**Issue by MadameMalady** [KRTirtho/spotube#1797] opened 2024-08-16 18:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm using a linux phone (thank you so much for the port btw!, been watching this app for a second!) and the ui does not scroll at all.

it does not allow scrolling up or down on any tab of the application.

### Expected Behavior

for scrolling to function.

### Steps to reproduce

opened app

searched a song

listened to song,

looked for another

Attempted to scroll through the results

scrolling doesnt work at all 

### Operating System

postmarketOS Stable - arm64 linux

### Spotube version

v3.7.1

### Installation source

Website (spotube.krtirtho.dev)

### Additional information

I'm realizing now looking at the selections for Installation source, that you likely didnt upload this to Flathub or port it yourself, so apologies if that's the case, sadly when someone does putup software on Flathub, they always list the devs issues section, even if the dev isnt interested, so if thats the case, sorry.

I actually got this from Flathub, but that's not a listed option, so I clicked the top option instead.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-08-18 06:02
Duplicate of #1763

**Comment by KRTirtho** [comment] 2024-08-18 06:03
This is a known issue. Touch screen on desktop isn't supported yet

**Closed by KRTirtho** 2024-08-18 06:03 UTC
Labels: bug

**Comment by erebion** [comment] 2024-08-26 14:18
@MadameMalady Until it works properly, try to scroll on the right edge of your screen. There's a scroll bar, but it is invisible. Does not work well yet, but at least there's a way to scroll down somehow.

**Comment by MadameMalady** [comment] 2024-08-26 22:37
@erebion Good lookin, ty that works for now
