### ISSUE TITLE
Cache/download next queued track to prevent silent streaming gaps.

### ISSUE THREAD

**Issue by CSeriestechhero** [KRTirtho/spotube#1722] opened 2024-07-19 07:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

When I listen to tracks in a playlist or album, once a track concludes, it leaves a silent gap as the Spotube client has to quickly download the next track.

### Suggested solution

Spotube should download or cache the next queued track so that it can immediately play once the current track concludes. This could also be a feature you have to toggle, knowing that the user might face the consequence of higher data and storage consumption because Spotube has to download the next track while the current one is playing.

### Useful resources

I have nothing technical, but this Spotify Community FAQ page references what I am talking about:
https://community.spotify.com/t5/FAQs/Spotify-use-of-Storage-Overview/ta-p/4812442#:~:text=Spotify%20stores%20songs,will%20take%20up.

### Additional information

If the Spotube client already pre-downloads/caches tracks, try to implement a way to have tracks play in a playlist gap-less.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by madman38** [comment] 2024-07-19 10:10
thank you for your submission. i hope the devs add this in the next version because this is the most unbearable thing imo.

**Comment by KRTirtho** [comment] 2024-12-08 13:32
Duplicate of #783

**Closed by KRTirtho** 2024-12-08 13:32 UTC
Labels: enhancement
