### ISSUE TITLE
playlist loading

### ISSUE THREAD

**Issue by CacaPedoPis212** [KRTirtho/spotube#1991] opened 2024-10-12 06:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Hi, when I open a playlist, not all the songs load immediately. I have to scroll all the way down to the last song for the entire list to load so I can download them.

.

### Suggested solution

It would be great if all the songs in a playlist could load at once when I open it, making the experience smoother and more convenient.

.

### Useful resources

You could look into how other music apps handle playlist loading, such as Spotify or Apple Music. Implementing a lazy loading strategy or pre-loading a full playlist when opened could enhance user experience. Additionally, articles on optimizing app performance for large data sets may also be helpful.

### Additional information

Nothing

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-10-13 05:23
Duplicate of #1456

**Closed by KRTirtho** 2024-10-13 05:23 UTC
Labels: enhancement

**Comment by KRTirtho** [comment] 2024-10-13 05:24
### Is there an existing issue for this?

- [X] I have searched the existing issues

![image](https://github.com/user-attachments/assets/161637ef-7f9b-4f9e-a26a-1764ca23ea0d)
