### ISSUE TITLE
Download error if changed download dictionary 

### ISSUE THREAD

**Issue by mandeep1305** [KRTirtho/spotube#836] opened 2023-10-23 16:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Download fails when i switch download dictionary.if i change it to default it starts working again.don't how it works but it  is bug.

### Expected Behavior

Download should work in any download dictionary 

### Steps to reproduce

1.opend
2.login
3.downloaded songs 
4.changed download folder 
5.strated to download more songs but doesn't worked shows error ( log is empty for me )
6.uninstall and reinstall form GitHub page .
7.open logged in and changed download dictionary and same error download failed (or something)

### Operating System

Android 13

### Spotube version

Latest 23 oct 23

### Installation source

GitHub Releases (Binary)

### Additional information

Mobile is not rooted

**Comment by KRTirtho** [comment] 2023-10-26 04:20
Duplicate of https://github.com/KRTirtho/spotube/issues/720

**Closed by KRTirtho** 2023-10-26 04:20 UTC
Labels: bug
