### ISSUE TITLE
Please add android auto enablement for apk

### ISSUE THREAD

**Issue by sreealeti** [KRTirtho/spotube#965] opened 2023-12-27 23:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Cannot be used part of android auto as spotify.

### Suggested solution

Add lines to manifest

**Comment by KRTirtho** [comment] 2023-12-28 05:54
Duplicate of #623

**Closed by KRTirtho** 2023-12-28 05:54 UTC
Labels: enhancement
