### ISSUE TITLE
Add song covers to rich presence

### ISSUE THREAD

**Issue by Barracuda1337** [KRTirtho/spotube#1548] opened 2024-06-01 20:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

The Discord Rich Presence status uses an image for the cover that means nothing considering all songs use it.

### Suggested solution

Please consider adding the covers for tracks as they would add a lot of value to the rich presence!

### Useful resources

I'm not a developer but you already have access to the Spotify API and song covers as they are used in the app. Therefore, they should be usable for discord rich presence (I'd assume) :)

### Additional information

> alright, for anyone who has the Flutter dev tools on their machine, adding the image URL on this line should do it:
> 
> https://github.com/KRTirtho/spotube/blob/cb95663412fcc9a829c5657e0160132f13fb0649/lib/provider/discord_provider.dart#L32

We don't have an application that can do this and it would be nice if it was added.

### Self grab

- [X] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-06-02 13:01
Duplicate of #1503

**Closed by KRTirtho** 2024-06-02 13:01 UTC
Labels: duplicate, enhancement, potential-duplicate

**Comment by KRTirtho** [comment] 2024-06-02 13:02
>Is there an existing issue for this?

> [x] I have searched the existing issues

It seems like you already knew an issue exits already. Please don't waste maintainers and developer's time **knowingly**
