### ISSUE TITLE
Spotube can't be sideloaded with AltStore or SideStore on iOS

### ISSUE THREAD

**Issue by cooldude-91** [KRTirtho/spotube#1653] opened 2024-06-22 06:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Installing with AltStore or SideStore fails with following error message.

/Users/rileytestut/iCloud Drive (Archive)/Documents/Developer/Projects/AltStore/Dependencies/AltSign/AltSign/ldid/../../Dependencies/ldid/ldid.cpp(1354): _assert(): end >= size - 0x10

Additional details: https://github.com/altstoreio/AltStore/issues/1034#issuecomment-1998081907

### Expected Behavior

It should install successfully as all other ipas

### Steps to reproduce

1. Download Spotube ipa from GitHub
2. Try to install with SideStore or AltStore
3. It fails during installation

### Operating System

iOS 17.5.1

### Spotube version

v3.7.1

### Installation source

GitHub Releases (Binary)

### Additional information

[More details are provided here, apparently this could be a signing issue](https://github.com/altstoreio/AltStore/issues/1034#issuecomment-1998081907)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-07-09 12:52
Duplicate of #1037

**Closed by KRTirtho** 2024-07-09 12:52 UTC
Labels: bug
