### ISSUE TITLE
Linux arm64 build

### ISSUE THREAD

**Issue by franklinprakash1090** [KRTirtho/spotube#901] opened 2023-11-26 10:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I tried to install on raspberry pi in flatpak there is no aarch64 support 

### Suggested solution

Build for aarch64/arm32 Linux and windows

**Comment by KRTirtho** [comment] 2023-11-26 16:06
Duplicate of #715

> Is there an existing issue for this?
> - [x] I have searched the existing issues

Clearly haven't 🙂

**Closed by KRTirtho** 2023-11-26 16:06 UTC
Labels: enhancement
