### ISSUE TITLE
Window corners are not rounded on linux

### ISSUE THREAD

**Issue by skewty** [KRTirtho/spotube#1486] opened 2024-05-07 15:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Window corners are not rounded.

### Suggested solution

Use Handy Window (see useful resources below).

### Useful resources

https://pub.dev/packages/handy_window

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-05-09 17:48
Duplicate of #694

**Closed by KRTirtho** 2024-05-09 17:48 UTC
Labels: enhancement
