### ISSUE TITLE
Latest version not working for me

### ISSUE THREAD

**Issue by xphantomdavex** [KRTirtho/spotube#1737] opened 2024-07-26 23:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Opening the latest release does nothing

### Expected Behavior

Program to launch

### Steps to reproduce

1. I had just preformed a clean install of windows 11 PC is fresh
2. Download the app 
3.  Try to launch
4. No launch :( 

### Operating System

Window 11

### Spotube version

Latest 3.7.1

### Installation source

GitHub Releases (Binary)

### Additional information

Downgrading solved this problem. Any solutions for future releases would of course be useful. 

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Clerynka** [comment] 2024-07-31 11:12
Have same issue Win10 x64  Version attached crashfile (originaly appcrash.wer) 
[Report.txt](https://github.com/user-attachments/files/16440365/Report.txt)

Previous version 3.7.0+31 works but have strange aspect ratio like half screen

**Comment by KRTirtho** [comment] 2024-08-12 03:10
Duplicate of #1578

**Closed by KRTirtho** 2024-08-12 03:10 UTC
Labels: bug, Windows
