### ISSUE TITLE
I see this on this app, html tag not rendered

### ISSUE THREAD

**Issue by nasirDoe** [KRTirtho/spotube#1788] opened 2024-08-14 02:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="902" alt="Screenshot 2024-08-14 at 09 18 48" src="https://github.com/user-attachments/assets/a9dd20be-37fe-4adb-aa7c-34009e3b93a9">

### Expected Behavior

-

### Steps to reproduce

-

### Operating System

macos

### Spotube version

v3.8.0

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by skruglov2023** [comment] 2024-08-14 06:46
#1784 but this one's for mac looks like.

**Comment by LetsBuild-exe** [comment] 2024-08-14 19:14
I have the same bug on Windows 11, Spotube 3.8.0
Some mixes have the html tags visible but not all
![grafik](https://github.com/user-attachments/assets/4d0dc5f7-dd86-4435-9875-86f6e43bd0d5)

**Comment by KRTirtho** [comment] 2024-08-15 16:59
Duplicate of #1784

**Closed** 2024-08-15 16:59 UTC
Labels: bug
