### ISSUE TITLE
Spotube app not play next song

### ISSUE THREAD

**Issue by Domipoke** [KRTirtho/spotube#587] opened 2023-07-18 14:14 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

Not play next songs. When the song ends, no songs starts again. 

### Expected Behavior

Reproduce the following song

### Steps to reproduce

1. Open app
2. Select playlist
3. Reproduce playlist
4. Listen all the first song
5. At the end of first song the app give two errors
6. No song starts next

### Operating System

android 

### Spotube version

V3.0.0

### Installation source

Website (spotube.netlify.app)

### Additional information

------- DEVICE INFO -------
id: TP1A.220624.014
board: viva
bootloader: unknown
brand: Redmi
device: viva
display: TP1A.220624.014
fingerprint: Redmi/viva_eea/viva:13/TP1A.220624.014/V14.0.1.0.TGDEUXM:user/release-keys
hardware: mt6781
host: pangu-build-component-system-85668-krq9n-225d4-f7p35
isPhysicalDevice: true
manufacturer: Xiaomi
model: 2201116TG
product: viva_eea
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.1.0.TGDEUXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-04-01
------- APP INFO -------
environment: release
version: 2.7.1
appName: Spotube
buildNumber: 18
packageName: oss.krtirtho.spotube
---------- ERROR ----------
ClientException: {url: https://spotube.pockethost.io/api/collections/users/auth-with-password, isAbort: false, statusCode: 0, response: {}, originalError: FormatException: Unexpected character (at character 1)
This instance is in Maintenance Mode. See https://pockethost.gitbook.io/man...
^
}
------- STACK TRACE -------
#0      PocketBase.send (package:pocketbase/src/client.dart:191)
<asynchronous suspension>
#1      initializePocketBase (package:spotube/services/pocketbase.dart:9)
<asynchronous suspension>
#2      main (package:spotube/main.dart:186)
<asynchronous suspension>
------- CUSTOM INFO -------

And one minute later:

------- DEVICE INFO -------
id: TP1A.220624.014
board: viva
bootloader: unknown
brand: Redmi
device: viva
display: TP1A.220624.014
fingerprint: Redmi/viva_eea/viva:13/TP1A.220624.014/V14.0.1.0.TGDEUXM:user/release-keys
hardware: mt6781
host: pangu-build-component-system-85668-krq9n-225d4-f7p35
isPhysicalDevice: true
manufacturer: Xiaomi
model: 2201116TG
product: viva_eea
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.1.0.TGDEUXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-04-01
------- APP INFO -------
environment: release
version: 3.0.0
appName: Spotube
buildNumber: 19
packageName: oss.krtirtho.spotube
---------- ERROR ----------
type 'int' is not a subtype of type 'String?' in type cast
------- STACK TRACE -------
#0      SharedPreferences.getString (package:shared_preferences/shared_preferences.dart:112)
#1      new PersistedChangeNotifier.<anonymous closure>.<anonymous closure> (package:spotube/utils/persisted_change_notifier.dart:23)
#2      ListBase.fold (dart:collection/list.dart:202)
#3      new PersistedChangeNotifier.<anonymous closure> (package:spotube/utils/persisted_change_notifier.dart:14)
<asynchronous suspension>
------- CUSTOM INFO -------

**Comment by Aro320x** [comment] 2023-08-03 18:13
Is with me exactly as described here by you! Android 13, Xiaomi redmi note 10 pro

**Comment by chernoslyv** [comment] 2023-08-04 18:23
> Please check if latest version (v3.0.1) works

I also have the same issue, on the latest version, Android 13, pixel 6

**Comment by xididri** [comment] 2023-08-07 18:59
duplicate of #580

**Comment by Aro320x** [comment] 2023-08-07 21:50
> Bitte prüfen Sie, ob die neueste Version (v3.0.1) funktioniert

It is also like this with version (v3.0.1)

**Comment by KRTirtho** [comment] 2023-08-08 04:05
@xididri #580 is actually duplicate of this one

**Comment by KRTirtho** [comment] 2023-08-08 04:05
Since all the activity is there, let's just continue discussion there instead of here

**Closed** 2023-08-08 04:06 UTC
Labels: bug, duplicate
