### ISSUE TITLE
Fade in/out

### ISSUE THREAD

**Issue by SudiptaSaha20** [KRTirtho/spotube#2112] opened 2024-12-07 18:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Whenever the current song ends, there is a sudden change of track which is very annoying

### Suggested solution

A simple fade in and fade out effect

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-12-08 13:32
Duplicate of #783

**Closed by KRTirtho** 2024-12-08 13:32 UTC
Labels: duplicate, enhancement
