### ISSUE TITLE
Auto play not available 

### ISSUE THREAD

**Issue by Sunilr001** [KRTirtho/spotube#1197] opened 2024-02-03 14:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

When you play single song app dose not recommend next songs, means auto play not available.
![Screenshot_20240203_193538_Spotube](https://github.com/KRTirtho/spotube/assets/150259844/d0973b59-c557-4b6f-bfa6-14eb3b436db4)

### Suggested solution

Please add Auto play.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-02-04 04:34
Duplicate of #285 

Btw, it's been added and you can check it out on Nightly version

**Closed by KRTirtho** 2024-02-04 04:34 UTC
Labels: enhancement

**Comment by gentleAmateur** [comment] 2024-02-13 04:49
I haven’t had this work for me on the latest nightly for Linux, I installed via the .deb package. 

Is there perhaps a setting/certain option I need to click that I missed, or should it do so automatically (similar to what Spotify already does)? Or will that be the next nightly/current bleeding edge version?

**Comment by ZenKyma** [comment] 2024-03-04 21:08
@gentleAmateur just go check out https://github.com/KRTirtho/spotube/releases/tag/nightly and download the [Spotube-linux-x86_64.deb](https://github.com/KRTirtho/spotube/releases/download/nightly/Spotube-linux-x86_64.deb) version.
