### ISSUE TITLE
Discord RPC Support

### ISSUE THREAD

**Issue by odiplol** [KRTirtho/spotube#470] opened 2023-04-09 18:00 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Pain

I love using Spotube, but I do miss being able to have my friends view my songs on my Discord profile, I would love if you could add this feature.

### Suggested solution

Add Discord RPC.

**Comment by KRTirtho** [comment] 2023-04-10 02:57
Duplicate of #8

**Closed** 2023-04-10 11:13 UTC
Labels: duplicate, enhancement
