### ISSUE TITLE
Various Artists Play the wrong/ Fan Versions of Sons, needs further investigation

### ISSUE THREAD

**Issue by cyndarion01** [KRTirtho/spotube#1945] opened 2024-10-01 07:00 UTC
### Is there an existing issue for this? (Please read the description)
There is but not the same issue as reported, the other report was for the songs not saving changes.
- [X] I have searched the existing issues

### Current Behavior

Off the top of my head: 
- Meteora by Linkin Park only pulls live versions even though the entire album is available without live audio
- Taekyun "Date Me not them" plays the "CAT" version by a RUS fan in entirely the wrong language
- Various fan remakes play original IP ie searching a Pokemon Fandub from youtube music produces the official Nintendo account
Too many to reasonably list, suggest optimizing the way your program searches for the correct title to playback somehow or manually flagging the incorrect ones based on user reports till theres a better way?

### Expected Behavior

Some tracks are mislabled/misplay the wrong selected track and there is no easy way to change track source in mobile/ its very hidden in browsers and takes several minutes.
Edit: The "alternative track" section does not appear in the three dot drop down, which would be convenient. It also doesn't appear consistently during the Compact or Adaptive modes on mobile, only on Extended. Also it crashes search feature, search stays stuck open now if using Extended mode to view the Alt playlists and then closes the app. Playback stops on close and the new track stays saved as is on reopen but its still weirdly not correct sometimes?

### Steps to reproduce

Search various tracks, random but many popular songs come as wrong versions of selected song.

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

All

### Spotube version

Current

### Installation source

Website (spotube.krtirtho.dev), GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-10-01 16:51
Duplicate of #883

**Closed by KRTirtho** 2024-10-01 16:51 UTC
Labels: bug
