### ISSUE TITLE
Songs Not Loading Due to Server Selection Choice

### ISSUE THREAD

**Issue by JaivishChauhan** [KRTirtho/spotube#1921] opened 2024-09-26 01:44 UTC
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

When fetching songs from different sources like _YouTube, Piped, or JioSaavn_,  if any source fails to retrieve the song, it skips that track and moves to the next one without attempting to play it.

### Expected Behavior

If fetching a song fails from one source (YouTube, Piped, or JioSaavn), it should attempt to retrieve the song from the other available sources. Only if all three sources fail should the system skip the song and move to the next one.If all three sources fail, the system should

### Logs

<details>
<summary>Logs</summary>

```
<asynchronous suspension>
#7      sourcedTrackProvider.<anonymous closure> (package:spotube/provider/server/sourced_track.dart:25)
<asynchronous suspension>
#8      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
[2024-09-26 07:00:05.300054]---------------------
Null check operator used on a null value
#0      QueryTableExtensions.whereSamePrimaryKey (package:drift/src/runtime/query_builder/statements/query.dart:418)
#1      UpdateStatement.replace (package:drift/src/runtime/query_builder/statements/update.dart:133)
#2      UserPreferencesNotifier.reset (package:spotube/provider/user_preferences/user_preferences_provider.dart:95)
#3      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1171)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309)
#7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:279)
#8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167)
#9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:499)
#10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475)
#11     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:425)
#12     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420)
#13     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383)
#14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330)
#15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299)
#16     _rootRunUnary (dart:async/zone.dart:1415)
#17     _CustomZone.runUnary (dart:async/zone.dart:1308)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#19     _invoke1 (dart:ui/hooks.dart:330)
#20     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442)
#21     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)

----------------------------------------
```
</details>

### Operating System

Android, Windows 

### Spotube version

V3.8.1

### Installation source

Website (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-10-01 16:57
Duplicate of #1916

**Closed by KRTirtho** 2024-10-01 16:57 UTC
Labels: bug
