### ISSUE TITLE
Write the title here

### ISSUE THREAD

**Issue by Zukureneno** [KRTirtho/spotube#828] opened 2023-10-21 18:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Windows defender automatically picks up the start menu .ink as a threat.

![image](https://github.com/KRTirtho/spotube/assets/60487234/75a52933-755e-4a7e-9547-b2d69e453fbb)

### Expected Behavior

Not be triggered

### Steps to reproduce

1. Download latest x64 windows version. (From the update pop up)
2. Install the .exe
3. Open notification bar
4. See picked up threat

### Operating System

Windows 10 Home 22H2

### Spotube version

Product Version: 3.2.0+25

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

**Comment by KRTirtho** [comment] 2023-10-26 04:12
Duplicate of https://github.com/KRTirtho/spotube/issues/701

**Closed by KRTirtho** 2023-10-26 04:12 UTC
Labels: bug
