### ISSUE TITLE
ridiculous memory usage

### ISSUE THREAD

**Issue by adam110902** [KRTirtho/spotube#710] opened 2023-09-10 15:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the app uses a ridiculous amount of memory after being active for some time
![image](https://github.com/KRTirtho/spotube/assets/104318712/e2380b4c-14df-4113-9914-d52c89cfd966)
i have seen it go above 20gb

### Expected Behavior

the app not using above 1gb of ram

### Steps to reproduce

1: open the app
2: wait
3: despair

### Operating System

windows 11

### Spotube version

v3.1.1

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev), GitHub Releases (Binary)

**Comment by KRTirtho** [comment] 2023-09-10 15:11
Duplicate of #659

**Closed by KRTirtho** 2023-09-10 15:11 UTC
Labels: bug
