### ISSUE TITLE
Add more music formats for downloads

### ISSUE THREAD

**Issue by charlixcx-droid** [KRTirtho/spotube#1884] opened 2024-09-15 10:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Id love for more music formats cause my computer literally wont play m4a

### Suggested solution

Maybe add mp3, wav, or other formats. I really give a big thanks i spotube add this

### Additional information

Thank you!!!

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by charlixcx-droid** [comment] 2024-09-15 10:48
And keep up for more updates!! I appreciate it

**Comment by KRTirtho** [comment] 2024-09-15 13:20
Somewhat
Duplicate of #815

**Closed** 2024-09-15 13:20 UTC
Labels: duplicate, enhancement
