### ISSUE TITLE
Not run on Raspberry PI400 with ubuntu 22.04 (arm64)

### ISSUE THREAD

**Issue by jackygoule** [KRTirtho/spotube#1544] opened 2024-06-01 09:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**After install  Spotube-linux-aarch64.deb  
In terminal:**

(process:95747): GLib-GObject-CRITICAL **: 11:36:29.502: g_object_new_is_valid_property: object class 'MyApplication' has no property named 'com.github.KRTirtho.Spotube'
package:media_kit_libs_linux registered.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library '/usr/share/spotube/lib/libdiscord-rpc.so': /usr/share/spotube/lib/libdiscord-rpc.so: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce nom
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22)
#2      DiscordRPC.initialize (package:dart_discord_rpc/dart_discord_rpc_native.dart:152)
#3      main (package:spotube/main.dart:76)
<asynchronous suspension>

**With  spotube-linux-nightly-aarch64.tar.xz 
In terminal**
(process:95115): GLib-GObject-CRITICAL **: 11:33:20.959: g_object_new_is_valid_property: object class 'MyApplication' has no property named 'com.github.KRTirtho.Spotube'
package:media_kit_libs_linux registered.
flutter: 
--------------------------------------------------------------------------------
media_kit: ERROR: MediaKit.ensureInitialized
This indicates that one or more required dependencies could not be located.

Refer to "Installation" section of the README for further details:
GitHub  : https://github.com/media-kit/media-kit#installation
pub.dev : https://pub.dev/packages/media_kit#installation

TIP: Copy-paste required packages from the above link to your pubspec.yaml.

If you recently added the packages, make sure to re-run the project ("hot-restart" & "hot-reload" is not sufficient for native plugins).
--------------------------------------------------------------------------------

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Cannot find libmpv at the usual places. Depending upon your distribution, you can install the libmpv package to make shared library available globally. On Debian or Ubuntu based systems, you can install it with: apt install libmpv-dev.
#0      NativeLibrary.ensureInitialized (package:media_kit/src/player/native/core/native_library.dart:78)
#1      nativeEnsureInitialized (package:media_kit/src/player/native/player/real.dart:47)
#2      MediaKit.ensureInitialized (package:media_kit/src/media_kit.dart:30)
#3      main (package:spotube/main.dart:58)
<asynchronous suspension>

### Expected Behavior

What can i do for run spotube on pi400

### Steps to reproduce

run https://github.com/KRTirtho/spotube/releases/download/nightly/spotube-linux-nightly-aarch64.tar.xz on Raspberry pi400 with ubtuntu 22.04

### Operating System

Ubuntu 22.04 LTS for Raspberry

### Spotube version

last

### Installation source

GitHub Actions (Nightly Binary)

### Self grab

- [X] I'm ready to work on this issue!

**Comment by Mubelotix** [comment] 2024-06-02 14:50
Same on Ubuntu 23.10

**Comment by KRTirtho** [comment] 2024-06-05 12:05
Duplicate of #929

**Closed by KRTirtho** 2024-06-05 12:05 UTC
Labels: bug
