### ISSUE TITLE
touch screen input dose not work on Linux Desktop

### ISSUE THREAD

**Issue by nanderer** [KRTirtho/spotube#1854] opened 2024-09-05 20:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i am using a thinkpad with touchscreen under gnome 3, its not as good as win 10 but gnome 3 is capable of some usefull gestures and chrome and firefox are capable of swiping through pages without problems. But spottube dose not destinguish between touch and mouse input and handles touch input thereby wrong, no scrolling through swipe gestures possible, in case of songtext it selects stuff insted of, in case of play queue it just dose nothing

### Expected Behavior

it should act like an android tablet when using touch controls

### Steps to reproduce

1. get a device with touchscreen and install linux on it
2. make sure touchscreen works probably in other desktop apps like the gnome desktop and chromium
3. install spotube
4. see how it dose not

### Operating System

Debian 11.11

### Spotube version

v3.8.0

### Installation source

Flathub (Flatpak)

### Additional information

i am using x server not Wayland (cause its not ready to use jet imho) but it should be no problem, other apps also have access to multi-touch gestures and and are able to distinguish from mouse/touchscreen input

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by FunctionalHacker** [comment] 2024-09-07 05:05
Doesn't work on Wayland either. Well clicking works but no scrolling. This makes spotube unusable on my tablet where touch screen is the only input.

Using spotube-bin on Arch, latest Gnome on Wayland.

**Comment by KRTirtho** [comment] 2024-09-15 04:51
Duplicate of #1763

**Closed by KRTirtho** 2024-09-15 04:51 UTC
Labels: bug
