### ISSUE TITLE
extermely slow skipping of songs

### ISSUE THREAD

**Issue by PantiesIsStoopid** [KRTirtho/spotube#2030] opened 2024-10-26 22:42 UTC
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

the app  when trying skip more then about 3 songs in a row the app lags for roughly 3 seconds

### Expected Behavior

the app should lag and should pre cache the next couple songs to reduce this issue especially on slow computers

### Steps to reproduce

open app. play a playlist on shuffle .skip the song a couple times

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

windows 11

### Spotube version

3.8.3

### Installation source

Website (spotube.krtirtho.dev)

### Additional information

i use arch btw

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-12-08 13:33
Duplicate of #783

**Closed by KRTirtho** 2024-12-08 13:33 UTC
Labels: bug
