### ISSUE TITLE
Listen Along support on Discord with Vencord

### ISSUE THREAD

**Issue by upseguest** [KRTirtho/spotube#1821] opened 2024-08-25 17:46 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Pain

I want listen along with discord and Vencord lets you do it without spotify premium but only with the Normal spotify desktop app (which has ads)

### Suggested solution

Make it compatible with the vencord version or without vencord if also possible (but its fine if it only works with vencord for me)

### Additional information

I have searched the existing issues and there is that one thats been open for a while but it doesnt have many details and seems to be abandoned basically

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-10-13 05:58
Duplicate of #8

**Closed by KRTirtho** 2024-10-13 05:58 UTC
Labels: enhancement
