### ISSUE TITLE
Spottifi shows a login error

### ISSUE THREAD

**Issue by kingpluginser** [KRTirtho/spotube#1457] opened 2024-04-30 05:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The replication sp_dc shows that the timeout has expired

### Expected Behavior

Login successful

### Steps to reproduce

![image](https://github.com/KRTirtho/spotube/assets/116493602/99a4a6b3-a397-4c36-8b14-54f805b0ef61)

### Operating System

Windows

### Spotube version

v3.6.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Goylife** [comment] 2024-05-01 04:23
Open the proxy software and turn on these three options
![photo_2024-04-15_16-14-42](https://github.com/KRTirtho/spotube/assets/20964031/b7e99c86-6424-4808-a8d5-fe38f074a411)

**Comment by Goylife** [comment] 2024-05-01 04:23
Open the proxy software and turn on these three options
<img width="595" alt="屏幕截图 2024-05-01 122155" src="https://github.com/KRTirtho/spotube/assets/20964031/79087ba2-f898-47cb-951e-dc4ac2c95093">

**Comment by kingpluginser** [comment] 2024-05-01 06:07
> 打开代理软件并打开这三个选项 <img alt="屏幕截图 2024-05-01 122155" width="595" src="https://private-user-images.githubusercontent.com/20964031/327048130-79087ba2-f898-47cb-951e-dc4ac2c95093.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NDMyNjksIm5iZiI6MTcxNDU0Mjk2OSwicGF0aCI6Ii8yMDk2NDAzMS8zMjcwNDgxMzAtNzkwODdiYTItZjg5OC00N2NiLTk1MWUtZGM0YWMyYzk1MDkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDA1NTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1NjRmMmEyNTAzNWE2ZGQ0MmI0NmE3OTA3ZmYxYWViYTQzODcyZmVhNWU5OTAyM2Y3ZWY5MzAyNzhkMTUwOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GPWIqMUeGNqjQqykSpJJo3oOUzIwzWbrZxj8qlG977s">
![image](https://github.com/KRTirtho/spotube/assets/116493602/65f2a2ee-390b-4d10-9b2a-eeddfddb43fa)

Sorry, I tried following your method and showed new issues

**Comment by KRTirtho** [comment] 2024-05-02 08:25
Duplicate of #1403

**Closed by KRTirtho** 2024-05-02 08:25 UTC
Labels: bug
