### ISSUE TITLE
Add a YouTube music source to the app

### ISSUE THREAD

**Issue by Chickenshrimps** [KRTirtho/spotube#1714] opened 2024-07-15 14:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I don't like the YouTube source because it fetches music videos directly from the YouTube app, which makes it hard to listen to 

### Suggested solution

Adding YouTube music source api to the app makes it better because  it fetche's the song  from the youtube videos and saves lot of the data 

### Useful resources

YouTube music source api 
https://music.youtube.com/

### Additional information

Pls update it the next update 
You said that you can't directly use from Spotify, can you use it from Yt music ?

### Self grab

- [X] I'm ready to work on this issue!

**Comment by GhoulBoii** [comment] 2024-07-15 18:37
there is already a youtube music source tho

**Comment by Chickenshrimps** [comment] 2024-07-16 02:27
> there is already a youtube music source tho

There isn't there is only a YouTube source , YouTube piped source, and a Jiosaavn source

**Comment by GhoulBoii** [comment] 2024-07-16 19:28
There is also the youtube piped source with the youtube music search method

**Comment by Chickenshrimps** [comment] 2024-07-17 02:49
Yes but the source they take is from YouTube directly not YouTube music

**Comment by rsnazrin** [comment] 2024-07-25 13:44
I was looking to raise this issue myself.

The main concern is that the YouTube source pulls videos directly from YouTube, leading to:
- Video clips including interludes or skits, which can be annoying or disrupt the listening experience, and potentially contain censored content.
- Suboptimal audio quality, as YouTube typically limits audio to 128kbps, whereas YouTube Music can offer up to 256kbps. Additionally, some YouTube videos may have inherently poor audio quality, which is less likely with YouTube Music due to the use of studio-quality tracks.

@Chickenshrimps, are you working on this?

**Comment by Chickenshrimps** [comment] 2024-07-25 14:26
I'm not a contributor, I can't work on this but I asked the creator for it but no reply has come from him 
@KRTirtho

**Comment by KRTirtho** [comment] 2024-10-13 06:17
Duplicate of #292

**Comment by KRTirtho** [comment] 2024-10-13 06:17
We can't directly use YouTube Music API but we can use through Piped (which doesn't work 100% the time)

**Closed by KRTirtho** 2024-10-13 06:17 UTC
Labels: enhancement
