### ISSUE TITLE
The Music Stops

### ISSUE THREAD

**Issue by Donoso005** [KRTirtho/spotube#1348] opened 2024-03-24 02:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a problem, why the music stops when i play some playlist, the music starts normally but in the 4-5 song stops, when the song stops, the next music keeps loading infinite.
I tried with the audio source - Piped and Youtube.
Piped on the server Kavin.rocks

### Expected Behavior

Reproduce all the PlayList

### Steps to reproduce

1. Open App
2. select a PlayList
3. start a song
4. On the 4 song the next song never reproduce

### Operating System

Windows 11 - Latest Version

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by callegar** [comment] 2024-03-25 18:29
Same issue here... but please fix the bug title as it is not very helpful as is...

**Comment by callegar** [comment] 2024-03-25 18:34
Probably the same issue as in #1154 or #1234

**Comment by Donoso005** [comment] 2024-03-25 21:46
But is not in Android the bug, the bug that I explained is on Windows 11, and next and previous button works, the problem is that when a ther is a queue more than 4-5 songs like a playlist the music stops on the 3th or 4th song, and when that song finish and starts the next one, the next songs keeps loading forever

**Comment by callegar** [comment] 2024-03-26 09:08
I am also not experiencing it in Android: I am on linux and the bug is exactly as you say. Playing from a playlist stops. It happens when a song ends and spotube cannot start the next one. The song that should be played appears with a never ending spinner on it (the player remains stuck on it). This is extra similar to what is described in issue #1154, apart from the different platform. I have also mentioned #1234, since the very spotube author suggests that #1154 could be a duplicate of it. The strange thing is that #1234 is declared as fixed, while #1154 and the present issue are still present.

**Comment by knightmar** [comment] 2024-04-07 09:51
Same issue here on all my platforms (win11, arch, android) with the stable version but also the nighty one.

**Closed** 2024-04-15 14:47 UTC
Labels: bug
