### ISSUE TITLE
Add recommended songs to queue

### ISSUE THREAD

**Issue by AliWhoi666** [KRTirtho/spotube#563] opened 2023-07-08 19:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Currently when a song is being played, new songs aren't added to queue

### Suggested solution

Similar to how Spotify does it, it'd be nice if recommended songs could be added based on the currently playing song

**Comment by abhisheksharma886** [comment] 2023-07-10 00:45
Hello, I would like to work on this, can it be assigned to me

**Comment by KRTirtho** [comment] 2023-07-10 06:36
Of course 😄 
Thanks ❤️

**Comment by KRTirtho** [comment] 2023-07-10 06:37
Make sure to read [this](https://github.com/KRTirtho/spotube/blob/master/CONTRIBUTION.md#your-first-code-contribution) and make PR against the `dev` branch 😃

**Comment by KRTirtho** [comment] 2024-02-04 04:33
Duplicate of #285

**Closed by KRTirtho** 2024-02-04 04:33 UTC
Labels: enhancement
