### ISSUE TITLE
Opening Android App causes playback event

### ISSUE THREAD

**Issue by JoAllg** [KRTirtho/spotube#110] opened 2022-06-10 16:14 UTC
**Describe the bug**
On Android opening the SpotTube App causes some kind of sound event to be sent, withouth any other user interaction.
I.e. if there has been music playing in another app then it is stopped and in the Notifications it shows that SpotTube is playing music right now (though there is no sound)

**edit: just installed Spottube on PC and experienced a similar problem. Just by starting the App, it sends some sound event that confuses the playback of other apps (in this case, my bluetooth speaker stoped playing sound for a moment)**

**To Reproduce**
1. Open the SpotTube while playing music from another app
2. Notice the music playing is stopped immediately
3. Look at the notifications to see that SpotTube seems to play sound

**Expected behavior**
Do not play any sound / do not send any sound event to android until the user has told the app to play music.

**Installation Source/Method**
apk from github (2.2.1)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Poco X3 NFC
 - OS: Android (ArrowOS)
 - Version 11

**Comment by KRTirtho** [comment] 2022-06-10 16:17
Yeah, this is an intended behavior to warm up (initialize) the device speakers. But stopping other music coming from different source is unintended. I've to investigate a bit to find out why is this happening

**Comment by JoAllg** [comment] 2022-06-10 16:32
Thanks for the fast reply. Please notice my edit, I experience a similar problem on Windows 10, though here it is only with a connected bluetooth speaker, not if I were to use the internal speakers of my laptop. On Android it happens in both cases.

**Comment by KRTirtho** [comment] 2022-07-11 06:22
Latest version v2.3.0 is just released. Can you try checking if the issue got fixed

**Comment by KRTirtho** [comment] 2022-07-11 11:05
I'll be working on that for finding what's the cause

**Comment by KRTirtho** [comment] 2022-09-09 12:26
Can you check again. It should be fixed in v2.4.0

**Comment by JoAllg** [comment] 2022-09-10 20:10
The problems I described before are all fixed! The only thing I noticed is that after a phone call (to be exact, I tested calling with Whatsapp) the playback does not resume automatically, as I am accustomed from other apps.

**Comment by KRTirtho** [comment] 2023-03-08 04:34
> The only thing I noticed is that after a phone call (to be exact, I tested calling with Whatsapp) the playback does not resume automatically, as I am accustomed from other apps.

@JoAllg if it still happens, create a separate issue for it :smile:

**Closed** 2023-03-08 04:33 UTC
Labels: bug
