### ISSUE TITLE
Crossfade/ overlap/fading 

### ISSUE THREAD

**Issue by Prashant0000007** [KRTirtho/spotube#2136] opened 2024-12-13 19:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

The silence between songs stops the vibe in which we are in 

### Suggested solution

A 0 to 12 Seconds slider just like Spotify foes can be included in the app 
Spotify slider for crossfade included
![Screenshot_20241214_004902_Spotify](https://github.com/user-attachments/assets/42dc0811-f81b-43f8-b9db-af627349c604)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-12-24 03:22
Duplicate of https://github.com/KRTirtho/spotube/issues/783

**Closed** 2024-12-24 03:22 UTC
Labels: duplicate, enhancement
