### ISSUE TITLE
Sluggish performance.

### ISSUE THREAD

**Issue by Staffed** [KRTirtho/spotube#750] opened 2023-09-25 18:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I live in the USA and I use 5G UC and the moment my speed gets a little slow all my songs just buffer. The songs also just buffer when skipping or playing to the next song. I did a speed test and I am getting 200 down and 30 up.

### Expected Behavior

I expect that Spotube would skip my tracks normally but it does not do that it buffers for some reason.

### Steps to reproduce

1. Open app.
2. Play song
3. Wait 5 seconds to even 30 seconds for the song to play.
4. Song finishes, then I have to upwards to 45 seconds or a minute for the song to play.

### Operating System

Android, Windows.

### Spotube version

3.1.2

### Installation source

GitHub Releases (Binary)

**Comment by KRTirtho** [comment] 2023-09-26 03:12
It depends on the performance of the CDN. If the CDN near u is having problems or is slower, the music can buffer

**Comment by KRTirtho** [comment] 2023-09-26 03:16
Duplicate of #743

**Closed** 2023-09-26 03:16 UTC
Labels: bug, duplicate

**Comment by wefalltomorrow** [comment] 2025-03-09 07:56
Not sure why this was closed, I have this issue (in Australia)
