### ISSUE TITLE
Crash when trying to close the search menu while on home screen

### ISSUE THREAD

**Issue by GStudiosX2** [KRTirtho/spotube#1998] opened 2024-10-14 03:10 UTC
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

When you open search and go to home page and press the arrow icon to close the search menu it crashes (black screen but sound still plays)

### Expected Behavior

The search menu to be closed

### Steps to reproduce

1. Open the search menu
2. Go to the home page 
3. Press the arrow button

### Logs

<details>
<summary>Logs</summary>

----------------------------------------
[2024-10-14 03:56:54.624496]---------------------
Null check operator used on a null value
#0      SearchController.closeView (package:flutter/src/material/search_anchor.dart:1113)
#1      SearchPage.build.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:spotube/pages/search/search.dart:151)
#2      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1170)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:656)
#5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:313)
#6      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:283)
#7      GestureArenaManager.sweep (package:flu</details>

### Operating System

Android

### Spotube version

v3.8.3

### Installation source

Play Store (Android)

### Additional information

https://github.com/user-attachments/assets/87048ac8-deff-446c-bf25-fab92be3d7ad

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-10-14 05:02
Duplicate of #1502

**Comment by KRTirtho** [comment] 2024-10-14 05:03
Please at least search before creating the issues. Duplicate issues only wastes everyone's time

**Closed by KRTirtho** 2024-10-14 05:02 UTC
Labels: bug

**Comment by GStudiosX2** [comment] 2024-10-14 05:49
> Please at least search before creating the issues. Duplicate issues only wastes everyone's time

I did search I guess I didn't use the right keywords
