### ISSUE TITLE
Cannot open artist pages

### ISSUE THREAD

**Issue by AniAdamPashut** [KRTirtho/spotube#1137] opened 2024-01-24 09:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

search a song, open an album, whatever that let's you click an artist to listen more songs that they created.
tried local and global artists.
got same message: "type 'double' is not subtype of type 'int?' in type cast"

### Expected Behavior

Show the artist main page
list songs whatever.

### Steps to reproduce

- open the app
- search for a song, open an album whatever
- click below the song name for an artist page (this also happens when directly searching for the artist)
- error shown

### Operating System

Arch Linux (from yay)

### Spotube version

3.4.0-2

### Installation source

Arch User Repository (AUR)

### Additional information

might be when calculating some meta data about the artists

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by paolog1994** [comment] 2024-01-24 11:18
This also happen on ubuntu, see below for log:

> ============================== CATCHER 2 LOG ==============================
> 
> ------- DEVICE INFO -------
> name: Ubuntu
> version: 23.10 (Mantic Minotaur)
> id: ubuntu
> idLike: [debian]
> versionCodename: mantic
> versionId: 23.10
> prettyName: Ubuntu 23.10
> buildId: null
> variant: null
> variantId: null
> ------- APP INFO -------
> environment: release
> version: 3.4.0
> appName: spotube
> buildNumber: 27
> packageName: spotube
> ---------- ERROR ----------
> type 'double' is not a subtype of type 'int?' in type cast
> ------- STACK TRACE -------
> #0      _$FollowersFromJson (package:spotify/src/models/_models.g.dart:513)
> #1      new Followers.fromJson (package:spotify/src/models/followers.dart:12)
> #2      _$ArtistFromJson (package:spotify/src/models/_models.g.dart:345)
> #3      new Artist.fromJson (package:spotify/src/models/artist.dart:11)
> #4      EndpointBase._list.<anonymous closure> (package:spotify/src/endpoints/endpoint_base.dart:60)
> #5      MappedIterable.elementAt (dart:_internal/iterable.dart:385)
> #6      ArtistPageRelatedArtists.build.<anonymous closure> (package:spotube/pages/artist/section/related_artists.dart:43)
> #7      SliverChildBuilderDelegate.build (package:flutter/src/widgets/scroll_delegate.dart:490)
> #8      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:829)
> #9      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:843)
> #10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2835)
> #11     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:835)
> #12     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349)
> #13     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2657)
> #14     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1071)
> #15     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2657)
> #16     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338)
> #17     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:424)
> #18     RenderSliverGrid.performLayout (package:flutter/src/rendering/sliver_grid.dart:615)
> #19     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
> #20     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139)
> #21     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:361)
> #22     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
> #23     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139)
> #24     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:361)
> #25     RenderObject.layout (package:flutter/src/rendering/object.dart:2546)
> #26     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:601)
> #27     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1554)
> #28     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1463)
> #29     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2385)
> #30     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1025)
> #31     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1038)
> #32     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591)
> #33     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986)
> #34     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457)
> #35     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
> #36     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255)
> #37     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113)
> #38     _invoke (dart:ui/hooks.dart:312)
> #39     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383)
> #40     _drawFrame (dart:ui/hooks.dart:283)
> ------- CUSTOM INFO -------

**Comment by KRTirtho** [comment] 2024-01-24 12:03
Duplicate of #1018

**Closed by KRTirtho** 2024-01-24 12:03 UTC
Labels: bug

**Comment by m1v1** [comment] 2024-03-05 09:14
Ditto on Mac OS Sonoma.
