### ISSUE TITLE
Please add the option to donwload a full playlist !

### ISSUE THREAD

**Issue by 17xr** [KRTirtho/spotube#90] opened 2022-05-27 22:37 UTC
I (and certainly other users) would like to be able to download a full playlist, Liked songs for example, instead of having to choose and download each track separately ! 

and Thanks for the genius developper and all contributors for this app !

Have a good day <3

**Comment by KRTirtho** [comment] 2022-05-28 10:03
duplicate of https://github.com/KRTirtho/spotube/issues/67

**Closed by KRTirtho** 2022-05-28 10:03 UTC
Labels: duplicate, enhancement
