### ISSUE TITLE
Searching for a song while playing a song.

### ISSUE THREAD

**Issue by TheJosephKhong** [KRTirtho/spotube#132] opened 2022-07-05 15:47 UTC
While listening to a song, many people would like to go ahead and make a search for another song. However, while clicking the space bar and making a search, the song pauses. The next time the bar is clicked again, the song plays. The patterns repeats over and over again and gets quite annoying. Hopefully, you can fix this. 

1. Play any song
2. Search button on the top left 
3. Search for any song that has more than 2 words and requires the spacebar
5. See error

**Expected behavior**
I was hoping to be able to type and not pause the play the music repeatedly when making a search. 

**Installation Source/Method**
- https://github.com/KRTirtho/spotube/releases/latest/download/Spotube-windows-x86_64-setup.exe

**Desktop:**
 - OS: Windows 10
 - Version 21H2 (OS Build 19044.1766)

**Comment by KRTirtho** [comment] 2022-07-06 07:54
This was a bug that create conflicts with play/pause shortcut with Search bar input & it has been already fixed

**Comment by KRTirtho** [comment] 2022-07-06 07:56
Duplicate of https://github.com/KRTirtho/spotube/issues/28

**Closed** 2022-07-06 08:03 UTC
Labels: bug, duplicate
