### ISSUE TITLE
Make Spotube remember "Alternative Track Sources" choice.

### ISSUE THREAD

**Issue by abrushworkriot** [KRTirtho/spotube#1706] opened 2024-07-10 13:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I've been using Spotube on both my Linux machine and Android phone and it's been mostly pretty good. Huge thanks for developing this app!

I have absolutely no clue how Spotube picks the video to play (does it just query Track Name - Album Name and pick the first result?), but sometimes, when trying to listen to certain albums, Spotube doesn't pick the right YouTube video to play. This is especially common in case of albums that multiple re/releases, remasters, live versions etc.
From time to time it's because the requested track is not available on YouTube(tough luck), but most of the time I am able to quickly find the correct track. The problem is that when I go back to the same track later, it still starts playing the same track, not the one I set before.

### Suggested solution

We could make Spotube save our previous choice to a file and make list of objects pairing the Spotify track with a YouTube video.
It would be especially useful if we could sync the list between devices, import, export and merge said files.

I'd love to help on that, but I haven't written a single line of Dart in my life.

One additional idea that's MUCH more ambitious, as a further step, is to create a way for community to moderate a list of track sources, and make it an option in Spotube to use it.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-07-10 14:46
Duplicate of #1223

**Closed by KRTirtho** 2024-07-10 14:46 UTC
Labels: enhancement
