### ISSUE TITLE
When I open search box and I go to another section of the app, it doesn't close

### ISSUE THREAD

**Issue by lorypelli** [KRTirtho/spotube#1959] opened 2024-10-04 16:04 UTC
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/user-attachments/assets/efceef38-7dbe-4ae9-856e-9cbfc638d6e1)

### Expected Behavior

It should close

### Steps to reproduce

1. Go to search section
2. Click to search
3. Change section

### Logs

Just visual issue, it also causes the app to be completely blank if you click the button to go back

### Operating System

Windows 11

### Spotube version

3.8.2

### Installation source

Website (spotube.krtirtho.dev)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-10-13 05:27
Duplicate of #1502

**Comment by KRTirtho** [comment] 2024-10-13 05:27
> ### Is there an existing issue for this?
> 
> - [X] I have searched the existing issues

![image](https://github.com/user-attachments/assets/161637ef-7f9b-4f9e-a26a-1764ca23ea0d)

**Closed by KRTirtho** 2024-10-13 05:27 UTC
Labels: bug
