### ISSUE TITLE
Need of Suggestions in Home and Search Feed

### ISSUE THREAD

**Issue by RIZZARSHI** [KRTirtho/spotube#2075] opened 2024-11-21 21:49 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Pain

Sometimes we don't know the name of the song but we know the Lyrics and by the lyrics we can find songs but in Spotube there is nothing like that and please add a system to add songs to playlist!!!

![Screenshot_2024-11-22-03-09-18-425_com spotify music](https://github.com/user-attachments/assets/a09bc977-5ff8-4ee0-8366-e6699451927a)

### Suggested solution

So please add that Thing and ya if Spotube gives our music taste songs in the Home it'll be Greatful.♥️♥️

### Useful resources

Sorry I'm not in Computer Field so I have no idea🙁

### Additional information

It'll be very grateful if you make a Bot for Discord like the Grrovy and ya You're solving a big problem for us♥️♥️

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-12-01 12:03
Duplicate of #93

**Closed** 2024-12-01 12:04 UTC
Labels: duplicate, enhancement
