### ISSUE TITLE
Spotify loging doesnt work on windows app 

### ISSUE THREAD

**Issue by CorruptedSpring** [KRTirtho/spotube#2081] opened 2024-11-25 20:09 UTC
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

we cant connect to spotify int he windows app

![image](https://github.com/user-attachments/assets/b31ca517-8201-4da5-8b6a-c30b928445c8)
![image](https://github.com/user-attachments/assets/f35f6825-4ad4-4e05-b0c0-c0bc3e3b1f90)
![image](https://github.com/user-attachments/assets/9f963f8d-3298-48d6-8c6d-9de1def08150)

### Expected Behavior

should be normally log in to spotify like android app

### Steps to reproduce

1. opened app
2. logged in
3. it doesnt work

### Logs

<details>
<summary>Logs</summary>

```
```
</details>

### Operating System

Windows

### Spotube version

latest

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-12-01 12:27
Duplicate of #1858

**Closed by KRTirtho** 2024-12-01 12:27 UTC
Labels: bug
