### ISSUE TITLE
Need proxy setting like original Spotify

### ISSUE THREAD

**Issue by Nadal3** [KRTirtho/spotube#1704] opened 2024-07-10 05:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I can't view anyting from the app without proxy app in windows.

### Suggested solution

Add proxy setting.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-07-11 14:57
Duplicate of #88

**Closed by KRTirtho** 2024-07-11 14:57 UTC
Labels: enhancement
