### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [KRTirtho/spotube#490] opened 2023-04-25 01:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Please support the Android 13 "Themed App Icons" feature.

![Screenshot_2023-04-25-05-21-42-691_de mm20 launcher2 release](https://user-images.githubusercontent.com/23485114/234154938-97eda9dc-e743-449f-9b61-a4e1bda7b168.jpg)

### Suggested solution

Please support the Android 13 "Themed App Icons" feature.

**Comment by KRTirtho** [comment] 2023-04-25 05:49
Duplicate of https://github.com/KRTirtho/spotube/issues/272

**Closed** 2023-04-25 05:49 UTC
Labels: duplicate, enhancement
