### ISSUE TITLE
Wrong song

### ISSUE THREAD

**Issue by NeyTwix** [KRTirtho/spotube#1360] opened 2024-03-27 20:20 UTC
### Is there an existing issue for this?

- [ x] I have searched the existing issues
(existing but seams to be different)
### Current Behavior

When selected a song, it isn't the write song played. I've a song in my library that i can't play beacause it's not the correct song.
The music in question is "0 question" (french song) but the song seems like a tuto. pretty disapointing...
![image](https://github.com/KRTirtho/spotube/assets/95046265/a8b9c2fb-4e09-4520-a8ca-96444e3c37c8)

### Expected Behavior

Play the correct music or make us the ability to choose the source in this case.

### Steps to reproduce

1. Open the app
2. Search for "0 questions Carbonne"
3. Play
4. Listen a tuto 26min longs

### Operating System

Windows / Android

### Spotube version

v3.5.0

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev), F-Droid (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by beastr45** [comment] 2024-03-29 03:40
you can change the audio provider in settings, also if you click the merge icon to the right you can change the source. Def a duplicate bug.

**Comment by OnyxJet** [comment] 2024-04-02 14:46
Since spotube searches for the selected song on YouTube and takes in from YouTube as its source, this means it isn't always accurate. This can be becuase the song may not be on YouTube or it accidenly played something with a similar title. Knowing this, the developer added a feature to help. On the playback screen where you pause/play, skip/rewind, etc, you will see a button on the button left that resembles a spilt (or fork). Upon pressing that you can search for the song name and select the correct audio.
![Screenshot_2024-04-02-10-46-40-89_1c96baa6fc3a4338d23fd334c3c04599](https://github.com/KRTirtho/spotube/assets/164056953/4a05193e-f92a-43b2-a883-89f407e989f1)

**Comment by KRTirtho** [comment] 2024-04-11 04:47
Duplicate of #883

**Closed by KRTirtho** 2024-04-11 04:47 UTC
Labels: bug

**Comment by dualposition** [comment] 2025-03-29 22:04
oh so this is why teto was speaking spanish 💔

**Comment by dualposition** [comment] 2025-03-29 22:05
why the fuck would it choose spanish out of everything 

![Image](https://github.com/user-attachments/assets/e9268d9d-9c10-49ac-8a4a-b57580d9bda6)
