### ISSUE TITLE
Youtube Playlists integration

### ISSUE THREAD

**Issue by TruFelix** [KRTirtho/spotube#1923] opened 2024-09-26 09:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I have a lot of playlists already from youtube(music), I don't want to create them all again.

I am quite sure some other people experience this situation as well.

### Suggested solution

As the library used for youtube audio also supports the manipulation & loading of youtube playlists I think it should be possible to do, the abstraction also seems rather good, so I don't think this would take ages to implement.

### Useful resources

https://github.com/Hexer10/youtube_explode_dart#working-with-playlists

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-10-03 04:04
Duplicate of #633

**Closed by KRTirtho** 2024-10-03 04:04 UTC
Labels: duplicate, enhancement, wontfix / Alternatively patched
