### ISSUE TITLE
New features: convert downloaded music into mp3

### ISSUE THREAD

**Issue by kafkagrey** [KRTirtho/spotube#2023] opened 2024-10-24 13:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

When i download some music on Spotube there isn't the possibility in the setting to convert the files into mp3s

### Suggested solution

Idk if this is possible (i'm a noob) but there are already some apps opensource on linux and android to download and convert music to mp3s files and idk if is possible to add that code to Spotube. I suggerest this if it's possible.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Vitalii-code** [comment] 2024-10-24 18:57
If you want to download music you can try using [Seal](https://github.com/JunkFood02/Seal)

**Comment by KRTirtho** [comment] 2024-10-25 03:21
Duplicate of #815

**Closed** 2024-12-08 13:36 UTC
Labels: duplicate, enhancement
