### ISSUE TITLE
app constantly crashing on page switch, too much unoptimized

### ISSUE THREAD

**Issue by syr1ne** [KRTirtho/spotube#2099] opened 2024-11-30 13:04 UTC
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

i am using linux on host, spotube is keeps on crashing when i switch to search tab, feels like very unoptimized... needs to work on that

### Expected Behavior

should be fast and smooth.

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

linuxmint

### Spotube version

v3.8.3

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-12-01 11:46
Duplicate of #1502

**Closed by KRTirtho** 2024-12-01 11:46 UTC
Labels: bug
