### ISSUE TITLE
Error Download

### ISSUE THREAD

**Issue by yshinryu** [KRTirtho/spotube#809] opened 2023-10-14 04:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can't download any song

### Expected Behavior

Download a song.

### Steps to reproduce

Select a song.
Click download button.
![Screenshot_20231014_122124_oss krtirtho spotube](https://github.com/KRTirtho/spotube/assets/147899905/11bcbf14-e5aa-4f1e-be17-d163f2ca8075)

### Operating System

Android

### Spotube version

3.1.2

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev), Play Store (Android)

**Comment by KRTirtho** [comment] 2023-10-14 04:36
Duplicate of #720

**Closed** 2023-10-14 04:36 UTC
Labels: bug, duplicate
