### ISSUE TITLE
I can't login to Spotify and last.fm, Authentication Failure Failed

### ISSUE THREAD

**Issue by arianasenky** [KRTirtho/spotube#1159] opened 2024-01-26 16:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![screenshot-1706284698521](https://github.com/KRTirtho/spotube/assets/157824870/b8852661-8375-4f98-9f14-6b40240c99e2)
![screenshot-1706284632222](https://github.com/KRTirtho/spotube/assets/157824870/3d178ddb-d00e-40ec-96e1-da426602e47e)
I can't login to Spotify and last.fm

### Expected Behavior

i want to login spotify and last.fm

### Steps to reproduce

1.I open this app
2.then i go to setting
3.I can't login to Spotify and last.fm

### Operating System

Windows 10

### Spotube version

v.3.4.0

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-01-27 06:21
Duplicate of #974

**Closed by KRTirtho** 2024-01-27 06:21 UTC
Labels: bug
