### ISSUE TITLE
Specific song wont play at all

### ISSUE THREAD

**Issue by vortexal** [KRTirtho/spotube#889] opened 2023-11-21 02:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Darkish by A-One wont play at all, the list of alternative track sources is blank and if I manually search for an alternative, all videos (including videos used for other songs) are grey-out and unselectable.

### Expected Behavior

The song to play like how everything else does.

### Steps to reproduce

1. open the app
2. navigate to Toho Eurobeat Vol.7
3. press play on Darkish
4. song doesn't play, nothing I do seems to get the song to play

### Operating System

Linux Mint 21.2

### Spotube version

v3.2.0.

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev)

### Additional information

I'm not sure what else might be necessary but I can confirm that the videos themselves play just fine for me when I use YouTube, so they are not blocked in my country (US). The issue also persists when changing the API type to Piped.

**Comment by KRTirtho** [comment] 2023-11-21 03:25
Duplicate of #883

**Closed** 2023-11-21 03:25 UTC
Labels: bug, duplicate

**Comment by vortexal** [comment] 2023-11-21 03:44
This is completely different from #883 as nothing is playing for me at all.

**Comment by vortexal** [comment] 2023-11-21 05:20
You know what, forget about it. I have determined that this app is not for me and I don't want to waste the dev's time fixing an issue that, based on what I've been told by people on other platforms, seems to somehow be specific to me and possibly not helpful to the development of this app. So just keep this issue closed unless someone else starts having a similar issue.
