### ISSUE TITLE
Spotify login

### ISSUE THREAD

**Issue by GeekYwl** [KRTirtho/spotube#1413] opened 2024-04-16 13:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I submit the value of sp_dc, after some time it prompts me that the request timed out, as shown here

![1713278576957](https://github.com/KRTirtho/spotube/assets/97236582/274cbdd9-ac9c-44e6-b8ce-8fe3ae81a383)

### Expected Behavior

I guess if it's working it should prompt a successful login.

### Steps to reproduce

I opened the app, and click the button of connect with spotify.2.I logged into spotify in Chrome then F12 to find the value of sp_dc in the cookie then copied it, then pasted it into the app and submitted it, then after a while it prompted the error shown in my picture.

### Operating System

Windows11

### Spotube version

v3.6 and earlier versions

### Installation source

Website (spotube.netlify.app) or (spotube.krtirtho.dev), GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by hongsedaima** [comment] 2024-04-16 14:13
me tooooooooooooooooooooooo

**Comment by KRTirtho** [comment] 2024-04-16 14:55
Simply, logout, quit the app and login. It's happening due to a change in the cache structure.
Logging out simply clears the cache and re-login just saves the token in the new structure.

**Comment by KRTirtho** [comment] 2024-04-16 14:57
Duplicate of #1403

**Closed by KRTirtho** 2024-04-16 14:57 UTC
Labels: duplicate, help wanted

**Comment by hongsedaima** [comment] 2024-04-17 02:19
> logout

Please tell me,logout the app or the web account?
Is there another way to clear the cache to fix this problem?
Thank you.
![image](https://github.com/KRTirtho/spotube/assets/37997806/cd521452-a64d-48c3-8d15-94d2d432038a)

**Comment by GeekYwl** [comment] 2024-04-17 07:31
> > logout
> 
> Please tell me,logout the app or the web account? Is there another way to clear the cache to fix this problem? Thank you. ![image](https://private-user-images.githubusercontent.com/37997806/323048629-cd521452-a64d-48c3-8d15-94d2d432038a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMzkwNzksIm5iZiI6MTcxMzMzODc3OSwicGF0aCI6Ii8zNzk5NzgwNi8zMjMwNDg2MjktY2Q1MjE0NTItYTY0ZC00OGMzLThkMTUtOTRkMmQ0MzIwMzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA3MjYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNGMwYzNiNDFmMzQ3ZTRiM2JjMDFjNjc4ZWUxYWQxNzNiYmU1NWQ1ZDhhYmU4NWU3MzIxMDg1OGNkNDhiZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YE450OKgMB6cdzfkQc8L4HRfFoBnOgsRL6WiqeZfRjc)

I have the same question. I have not successfully logged in, how do I log out to clears the cache and re-login? @KRTirtho
