### ISSUE TITLE
[Bug] Error Type "Null" is not a subtype of type 'Map<String,dynamic>'

### ISSUE THREAD

**Issue by famewolf** [KRTirtho/spotube#224] opened 2022-09-19 19:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attempted to pull up the "Just Good Music" playlist from browse and received the error:  [Bug] Error Type "Null" is not a subtype of type 'Map<String,dynamic>'

![Screenshot_20220919-155014_Spotube](https://user-images.githubusercontent.com/4558832/191105273-316705f3-08f0-48c7-be4a-850d4292eb6f.png)

### Expected Behavior

Playlist should display.

### Steps To Reproduce

Browse in spotube and select the "Just Good Music" playlist.

### Spotube Version

v2.4.1

### Operating System

Android

### Operating System Version

Lineage 19.1 (Android 12)

### Installation Source

F-Droid (Android)

**Comment by famewolf** [comment] 2022-09-20 01:43
Might be related to https://github.com/KRTirtho/spotube/issues/201

**Comment by KRTirtho** [comment] 2022-09-21 03:05
> Might be related to #201

duplicate of #201

**Closed** 2022-09-21 03:06 UTC
Labels: bug, duplicate, good first issue
