### ISSUE TITLE
Hoping add app-level proxy on Mac version

### ISSUE THREAD

**Issue by jiangaq** [KRTirtho/spotube#1071] opened 2024-01-17 07:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Now have to use system-level proxy to log in spotify account, which I don't hope every app on my Mac using proxy through the internet.

### Suggested solution

Hoping add app-level proxy on Mac version.

**Comment by KRTirtho** [comment] 2024-01-17 14:36
Duplicate of #88

**Closed by KRTirtho** 2024-01-17 14:36 UTC
Labels: enhancement
