### ISSUE TITLE
“spotube.app” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by MEMEO-PRO** [KRTirtho/spotube#1172] opened 2024-01-28 16:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Apple is not able to check for malicious software stuff

### Expected Behavior

Should be able to open the app without any difficulty

### Steps to reproduce

1. Download the .dmg file
2. open the app after moving it to apps folder

### Operating System

macOS

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by amit** [comment] 2024-01-29 03:38
Check #1086

**Comment by KRTirtho** [comment] 2024-01-31 08:52
Duplicate of #1086

**Closed by KRTirtho** 2024-01-31 08:52 UTC
Labels: bug

**Comment by Obambulate** [comment] 2025-03-16 21:18
Since the earlier report was closed, could you "notarize" the app? If not, I will not be able to use it due to not having an admin password. Thanks.
