### ISSUE TITLE
iOS app

### ISSUE THREAD

**Issue by SonyaADM** [KRTirtho/spotube#675] opened 2023-08-29 19:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

we need iOS app

### Suggested solution

Hi. I like your project, it is very promising. However, I believe that the iOS version is simply necessary. It is desirable to be able to install directly from the AppStore. If Apple doesn't allow such a program to run on the AppStore, you can create a Spotube with a fake name something like "my top music" and inside the option to manually change domains in case the servers shut down after removing the application from the Appstore. In this way, you will be able to spread free access to music for iOS users

**Comment by KRTirtho** [comment] 2023-08-30 04:19
I can't do that myself as I don't own a Mac & Apple doesn't allow using any CI/CD to publish apps to any of their AppStore.
That means I need a physical Mac (or Hackintosh) to get a developer Apple ID & then build the app, sign it using the ID & finally publish.

Not to forget $99 yearly store fee & planet's worst app reviewing (moderation) system. Where Spotube's collective barely made few hundred bucks over 2 years! So, iOS is a big no-go zone for this project.
But don't lose hope

**Comment by SonyaADM** [comment] 2023-08-30 06:05
I think that this would be a good option for the development of the project, since hacked music applications on iOS are very rare, due to which the program can gain much more popularity than on Android/Windows where you can install a hacked version in two minutes. Yes, I understand that you need a Hackintosh, but I think it will be a good investment in the project, because if you think logically, in the iOS market, you can become a monopoly in the hacked Spotify, even if you ask for a one-time buy of $2, but at the same time will add a feature like changing servers in case the app is blocked in the AppStore, it will add new users

**Comment by KRTirtho** [comment] 2023-08-30 08:56
This is not any "hack" app. It legitimately gets your music from publicly available resources (YouTube or Piped.video)
FYI, even the Spotify library, playlists, albums etc. it gets by using Spotify's official API not by any form of scrapping. The only pirating part of this app is music downloads.

> If you think logically, in the iOS market, you can become a monopoly in the hacked Spotify, even if you ask for a one-time buy of $2.

This is a hobby + FOSS project. I don't intend to make income or profit from it. The collective was opened to financially aid only this project (by the community). Also, we don't have a goal to become a market monopoly. This project might use GitHub but it's not another Microsoft corp.

So, it's a no for iOS users now until I personally buy a mac/macbook or someone with mac is willing to maintain the iOS version.

**Comment by SonyaADM** [comment] 2023-08-30 08:58
ok. are there any similar apps to yours on iOS?

**Comment by KRTirtho** [comment] 2023-08-31 08:26
I'm not sure about. No experience with AppStore at all

**Comment by meenbeese** [comment] 2023-09-04 22:28
Duplicate of #178 btw

**Closed** 2023-09-05 09:08 UTC
Labels: duplicate, enhancement

**Comment by muhammadbahaa2001** [comment] 2023-09-18 12:40
Can't you make a signed IPA of Spotube so, it can be installed without JailBreak?
You upload IPA here in this Github repo, or any other non-Apple store like SideStore, TrollStore, and etc...

> I'm not sure about that. No experience with AppStore at all 😅

**Comment by meenbeese** [comment] 2023-09-18 20:05
> Can't you make a signed IPA of Spotube so, it can be installed without JailBreak?
> 
> You upload IPA here in this Github repo, or any other non-Apple store like SideStore, TrollStore, and etc...

Have you read the rest of the thread before asking questions?

> I can't do that myself as I don't own a Mac & Apple doesn't allow using any CI/CD to publish apps to any of their AppStore.
> 
> That means I need a physical Mac (or Hackintosh) to get a developer Apple ID & then build the app, sign it using the ID & finally publish.

**Comment by meenbeese** [comment] 2023-09-18 20:05
You can't even sign an iOS app without owning a Mac.

**Comment by karniv00l** [comment] 2023-09-19 06:22
GitHub actions can run on macOS. There's plenty of articles on how to sign and publish

**Comment by KRTirtho** [comment] 2023-09-19 09:20
Can you share one? I tried & failed multiple times :')

**Comment by keshavashiya** [comment] 2024-01-21 12:49
@KRTirtho did you tried this? [blog](https://medium.com/team-rockstars-it/the-easiest-way-to-build-a-flutter-ios-app-using-github-actions-plus-a-key-takeaway-for-developers-48cf2ad7c72a)
