### ISSUE TITLE
Helper app to intercept Spotify intents, to redirect Spotify Android integrations w/ Spotube

### ISSUE THREAD

**Issue by e-t-l** [KRTirtho/spotube#776] opened 2023-10-03 03:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Android/Google has lots of great Spotify integrations already, e.g. the Google Clock app can connect to Spotify and set a Spotify playlist as a clock alarm sound. However, Google doesn't let users integrate arbitrary music apps, so Spotube cannot be used. 

### Suggested solution

The Android Spotify app has an intent-based API and URI scheme, where apps can send an intent to the Spotify app instructing it to play a song or playlist. We could create a Spotube helper app that has the package name "com.spotify.music" and which registers the `spotify:` URI, which would intercept these intents, and then communicate with the Spotube app to start playing the appropriate music.

(Yes, this does mean that the official Spotify app could not be installed simultaneously, since this helper app would essentially be pretending to be the real Spotify app. Naming the package may or may not ultimately be necessary, but registering the URI scheme definitely is necessary to make the intents work.) 

### Useful resources

https://developer.spotify.com/documentation/android/tutorials/content-linking

https://developer.spotify.com/documentation/android

https://github.com/spotify/android-sdk

**Comment by KRTirtho** [comment] 2023-10-03 15:52
Duplicate of [#307](https://github.com/KRTirtho/spotube/issues/307)

**Closed** 2023-11-17 07:57 UTC
Labels: duplicate, enhancement
