### ISSUE TITLE
library "|||\" button,

### ISSUE THREAD

**Issue by vshal5** [KRTirtho/spotube#1225] opened 2024-02-10 09:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

type 'double' is not a subtype of 'int?' in type cast

### Expected Behavior

able to show songs under artist

### Steps to reproduce

1. home page
2. click on "||\" icon (which 2nd from below right)
3. click on arists (above right)
4. click on one of the artist displayed
5. you would notice this exception from code mentioned above

### Operating System

Android

### Spotube version

v3.4.0 (27)

### Installation source

GitHub Releases (Binary)

### Additional information

 and not able to update this(when clicked on download android .apk file, nothing happens)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by olivier2** [comment] 2024-02-11 22:13
Hey @vshal5 , I was able to reproduce this issue on 3.4.0. Fortunately, it's been reported in issue #1018 (with slightly different repro steps) and was fixed for version 3.4.1. Can you update and confirm the issue is fixed on your end?

**Comment by olivier2** [comment] 2024-02-11 22:14
Duplicate of #1018

**Closed** 2024-02-13 08:42 UTC
Labels: bug, duplicate
