### ISSUE TITLE
[Wrong song] <while the thumbnail remains identical the music is completely different>

### ISSUE THREAD

**Issue by levagency** [KRTirtho/spotube#196] opened 2022-09-06 01:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Артем Пивоваров - Дежавю (UA Version)
(If you search for that exact combination of terms inside the app you'll get a completely different song, then the corresponding correct song which can be found on YouTube, with the same thumbnail.  

### Expected Behavior

When you search for that particular song with the Cyrillic letters it's supposed to play the same song that you can find with the same Cyrillic keywords on YouTube, but it plays completely different song completely unrelated to those keywords or the artist

### Steps To Reproduce

In the app search for this exact combination of keywords, copy and paste of course...
Артем Пивоваров - Дежавю (UA Version)
If you search for the same combination of terms / keywords on YouTube you will get a completely different song, the song on YouTube is correct, well the song in the app is completely wrong and unrelated to the song title or even the artist.

### Spotube Version

V 2.3.0

### Operating System

Android

### Linux Distribution (if applicable)

N/A

### Operating System Version

Android 11

### Installation Source

F-Droid (Android)

### Additional information

If any part of my explanation is unclear you're welcome to email me

**Comment by adarsh1001** [comment] 2022-09-17 17:37
I'm able to reproduce this issue with the following song as well (both on the Android and Linux version of the app). Some 24 minute long podcast starts playing instead of the actual 4 minute long song.

![2022-09-17_23-02](https://user-images.githubusercontent.com/8820038/190869521-82203fa1-4aac-4cd1-ae5e-d4cca2775bcf.png)

**Comment by RaptaG** [comment] 2023-03-10 13:34
Possibly a duplicate of #32.

**Closed by RaptaG** 2023-03-10 13:34 UTC
Labels: bug
