### ISSUE TITLE
Save Songs As More File Types Such As Mp3

### ISSUE THREAD

**Issue by FlipMods** [KRTirtho/spotube#1286] opened 2024-03-02 09:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I Don't Like To Have To Change The File Extension/Use An Online Converter When I Want To Convert m4a Or webA To Mp3 File Type

### Suggested solution

I Think You Could Implement An Innovative Way To Save As Mp3 Such As Maybe Having A Built In File Converting System Allowing For More File Types

### Useful resources

[Dart-io File Class](https://api.flutter.dev/flutter/dart-io/File-class.html)
[Reading/Writing Files](https://docs.flutter.dev/cookbook/persistence/reading-writing-files)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-03-03 05:21
Duplicate of #815

**Closed by KRTirtho** 2024-03-03 05:21 UTC
Labels: enhancement
