### ISSUE TITLE
Song download error 

### ISSUE THREAD

**Issue by Danjo420** [KRTirtho/spotube#954] opened 2023-12-19 15:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Song download error message

### Expected Behavior

Download a Song

### Steps to reproduce

1. Opened the app
2. Try download the actually song
3. Get error

### Operating System

Android 14

### Spotube version

3.3.0-nightly build 185

### Installation source

GitHub Actions (Nightly Binary)

**Comment by KRTirtho** [comment] 2023-12-19 18:46
Duplicate of #849

**Closed by KRTirtho** 2023-12-19 18:46 UTC
Labels: bug
