### ISSUE TITLE
Spotube won't open

### ISSUE THREAD

**Issue by siliconsniffer** [KRTirtho/spotube#989] opened 2024-01-01 12:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

App shows a black or grey window when started.

### Expected Behavior

The App should open as in previous versions.

### Steps to reproduce

1. I opened the App
2. Either the app opens a black screen or a gray one.
![Bildschirmfoto von 2024-01-01 13 13 29](https://github.com/KRTirtho/spotube/assets/97843108/2d78601e-d957-45f5-acb4-b9feaf46dec0)
![Bildschirmfoto von 2024-01-01 13 14 07](https://github.com/KRTirtho/spotube/assets/97843108/e8c04e00-b1ac-4cfd-8915-882ca72d367b)

### Operating System

Linux

### Spotube version

v3.4.0

### Installation source

Flathub (Flatpak)

### Additional information

Running it via Terminal gives following output:
``` shell
(process:2): GLib-GObject-CRITICAL **: 13:12:03.336: g_object_new_is_valid_property: object class 'MyApplication' has no property named 'com.github.KRTirtho.Spotube'
Gtk-Message: 13:12:03.368: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:12:03.369: Failed to load module "canberra-gtk-module"

(spotube:2): Gdk-CRITICAL **: 13:12:03.373: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
package:media_kit_libs_linux registered.
flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: lock failed, path = '/home/user/.var/app/com.github.KRTirtho.Spotube/data/spotube/oss.krtirtho.spotube.skip_segments.v1.lock' (OS Error: Die Ressource ist zur Zeit nicht verfügbar, errno = 11)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _RandomAccessFile.lock.<anonymous closure> (dart:io/file_impl.dart:1023)
<asynchronous suspension>
#2      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:81)
<asynchronous suspension>
#3      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
<asynchronous suspension>
#4      HiveImpl.openLazyBox (package:hive/src/hive_impl.dart:160)
<asynchronous suspension>
#5      main (package:spotube/main.dart:102)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: lock failed, path = '/home/user/.var/app/com.github.KRTirtho.Spotube/data/spotube/oss.krtirtho.spotube.skip_segments.v1.lock' (OS Error: Die Ressource ist zur Zeit nicht verfügbar, errno = 11)
#0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _RandomAccessFile.lock.<anonymous closure> (dart:io/file_impl.dart:1023)
<asynchronous suspension>
#2      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:81)
<asynchronous suspension>
#3      HiveImpl._openBox (package:hive/src/hive_impl.dart:111)
<asynchronous suspension>
#4      HiveImpl.openLazyBox (package:hive/src/hive_impl.dart:160)
<asynchronous suspension>
#5      main (package:spotube/main.dart:102)
<asynchronous suspension>
``

**Comment by benwmx** [comment] 2024-01-01 15:36
I have the same issue in both flatpak version and .deb

**Comment by AkshayGade23** [comment] 2024-01-01 16:07
Ran the same version but didn't get this issue

**Comment by siliconsniffer** [comment] 2024-01-01 16:57
Downgraded the Flatpak Installation via this guide: https://itsfoss.com/downgrade-flatpak-packages/ to v.3.1.0.
Opens as usual, streams music.

**Comment by KRTirtho** [comment] 2024-01-01 17:36
Duplicate of #978

**Closed by KRTirtho** 2024-01-01 17:36 UTC
Labels: bug

**Comment by siliconsniffer** [comment] 2024-01-01 17:50
> Duplicate of #978

Error output is different, that's why I posted another issue.

**Comment by lusmo** [comment] 2024-06-03 17:04
Flatpak version not working after update :-(

** (spotube:2): CRITICAL **: 13:01:47.004: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed
