### ISSUE TITLE
Wrong Titel played

### ISSUE THREAD

**Issue by ansie3045** [KRTirtho/spotube#1279] opened 2024-02-28 10:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://open.spotify.com/track/0cx9oO5WIb3kTGUPRriPYA
This song should be played but another completely other track is played. (probably wrong Artist and wrong length)

### Expected Behavior

Play the right Song

### Steps to reproduce

1. Open the App
2. Search blured figures
3. Play "you've changed"

### Operating System

Linux Fedora 39 Worstation Edition

### Spotube version

v3.4.1 Build 28

### Installation source

Flathub (Flatpak)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-02-28 10:42
Duplicate of #883

**Closed by KRTirtho** 2024-02-28 10:42 UTC
Labels: bug
