### ISSUE TITLE
Bye bye bye song by nsync it is not playing

### ISSUE THREAD

**Issue by D024kkk** [KRTirtho/spotube#2018] opened 2024-10-21 09:55 UTC
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

Bye bye bye song by nsync is not playing - Jiosaavn 
Even any song by NSYNC is not playing 
Please fix this

### Expected Behavior

Song by Nsync should be playing 

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

Android 

### Spotube version

v3.8.3

### Installation source

Play Store (Android)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-10-25 13:10
Duplicate of #883

**Closed by KRTirtho** 2024-10-25 13:11 UTC
Labels: bug
