### ISSUE TITLE
Doesn't play any song

### ISSUE THREAD

**Issue by bronze7** [KRTirtho/spotube#1932] opened 2024-09-27 18:21 UTC
### Is there an existing issue for this? (Please read the description)

- [x] I have searched the existing issues

### Current Behavior

This app was working fine for me 2 days back. Now it stopped working. I tried reinstalling and installing an older version, didn't work. 

### Expected Behavior

It should be playing the song I click on

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

Android

### Spotube version

Latest

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by SaeedDev94** [comment] 2024-09-27 18:47
Same here

**Comment by TheTridentGuy** [comment] 2024-09-27 19:17
pretty sure there is an existing issue for this, with a homebrew fix

**Comment by SaeedDev94** [comment] 2024-09-27 19:56
> pretty sure there is an existing issue for this, with a fix you can try: #1920

OK, so we should wait for next release ... or manually building it after upgrading `youtube_explode_dart: ^2.2.2` ?  
I would appreciate if @KRTirtho releases a new build, thanks

**Comment by bordelique1** [comment] 2024-09-27 20:41
Same for me on windows and android.
Tracks doesn't want play
![Screenshot 2024-09-26 210008](https://github.com/user-attachments/assets/2e7560c6-ad25-4ec6-be4c-e3c2624912e0)

**Comment by francescocan** [comment] 2024-09-28 10:45
same for me. 

From the log files, both on windows and Android:


**Spotify API access errors:**
Error 403: “Insufficient client scope”.
Errors when trying to get the main Spotify feed.

**YouTube errors:**
403 errors when trying to get streams of various YouTube videos.

**Data processing errors:**
Errors when trying to access properties of null objects, specifically when processing the main feed

**Flutter Errors:**
Various errors related to rebuilding widgets and handling application state.


I include my latest windows logs

[spotube logs.txt](https://github.com/user-attachments/files/17174137/spotube.logs.txt)

**Comment by GovindKrishnan** [comment] 2024-09-28 14:28
Using **Piped** as Audio Source in Settings worked for me but is a temporary workaround.

**Comment by pmacedo-19** [comment] 2024-09-28 20:17
Same problem for me. Tried to use Piped as Audio Source but it plays some random Indian song instead of my playlist.

**Comment by LogaYT** [comment] 2024-09-29 09:27
same here, it plays a random indian song xDDDDDD

**Comment by GovindKrishnan** [comment] 2024-09-29 09:30
Yea, noticed the song is different in many cases when source is Piped. Gotta wait for next release I guess.

**Comment by bitterskittles** [comment] 2024-09-29 15:25
I see this error on MacOS
```
[2024-09-29 16:24:09.243696]---------------------
YoutubeExplodeException: Video p9N-9DAlbYM returned 403 (stream: 313
#0      StreamClient.getManifest.<anonymous closure> (package:youtube_explode_dart/src/videos/streams/stream_client.dart:46)
<asynchronous suspension>
#1      retry (package:youtube_explode_dart/src/retry.dart:16)
<asynchronous suspension>
#2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:949)
<asynchronous suspension>
#3      YoutubeSourcedTrack.toSiblingType (package:spotube/services/sourced_track/sources/youtube.dart:145)
<asynchronous suspension>
#4      YoutubeSourcedTrack.fetchSiblings (package:spotube/services/sourced_track/sources/youtube.dart:239)
<asynchronous suspension>
#5      YoutubeSourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sources/youtube.dart:63)
<asynchronous suspension>
#6      SourcedTrack.fetchFromTrack (package:spotube/services/sourced_track/sourced_track.dart:131)
<asynchronous suspension>
#7      sourcedTrackProvider.<anonymous closure> (package:spotube/provider/server/sourced_track.dart:25)
<asynchronous suspension>
#8      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

----------------------------------------
```

**Comment by anekobtw** [comment] 2024-09-30 15:56
same

**Comment by grishrana** [comment] 2024-10-01 06:16
I had the same issues. I had installed spotube from yay. Now I reinstalled spotube from flatpak it works fine now.

**Comment by GovindKrishnan** [comment] 2024-10-01 07:02
> I had the same issues. I had installed spotube from yay. Now I reinstalled spotube from flatpak it works fine now.

Latest update fixed it for all

**Comment by francescocan** [comment] 2024-10-01 07:13
@GovindKrishnan you rock!! thanks a million

**Comment by GrampaWildWilly** [comment] 2024-10-01 07:16
On Windows 11 Pro 64-bit version 23H2 build 22631.4249 with Spotube 3.8.2, this track will not play:

Track: I've Got a Feeling - Rooftop Performance / Take 2
Timing: 5:35
Album: Get Back (Rooftop Performance)
Artist: The Beatles
On YouTube: https://www.youtube.com/watch?v=6uNVp8k2m5U (plays fine)

[Spotube Log.txt](https://github.com/user-attachments/files/17200990/Spotube.Log.txt)

**Comment by KRTirtho** [comment] 2024-10-01 16:55
Duplicate of #1916

**Closed by KRTirtho** 2024-10-01 16:55 UTC
Labels: bug
