### ISSUE TITLE
Internet access by VPN only

### ISSUE THREAD

**Issue by Johndjk** [KRTirtho/spotube#1317] opened 2024-03-09 22:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Many users like me are looking for alternative apps like this for privacy reasons.

For those who want to keep their data secure and private, avoiding identity leaks such as IP addresses, and still access data directly from Youtube's servers (to avoid Piped's slowness and instability), this would be an incredible feature.

I know that I and many other users really want it, particularly me, since I don't use KillSwitch on the VPN.

### Suggested solution

I'm not a technical person but the https://www.qbittorrent.org/ app uses this option and it's amazing. Maybe it will help.

### Additional information

Desktop app in Linux

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-03-10 04:56
Duplicate of #88

**Closed by KRTirtho** 2024-03-10 04:56 UTC
Labels: enhancement
