### ISSUE TITLE
Lyrics not being correctly displayed when containing non-standard characters

### ISSUE THREAD

**Issue by je-sendra** [KRTirtho/spotube#1510] opened 2024-05-16 13:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![photo_5922311777637483300_y](https://github.com/KRTirtho/spotube/assets/115565209/99e82c41-10f0-4b85-b647-42a5a935968b)

Some characters are not correctly encoded.

### Expected Behavior

Words that contain non-standard characters (like Ñ) being correctly displayed.

### Steps to reproduce

1. Open the app.
2. Select a song that contains special characters in lyrics (image is Tiroteo from Marc Seguí)
3. Open lyrics page

### Operating System

Android 13

### Spotube version

v3.6.0 (comp 30)

### Installation source

F-Droid (Android)

### Additional information

Might be related to #1505 

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by yuesubi** [comment] 2024-05-21 16:11
I also get the same issue with Japanese songs : the lyrics and the home page have the issue. So I think it's fair to assume that issue #1505 is the same as this one.
Oddly enough, this issue doesn't appear in the listing of song in a playlist, but does in the description of it, for example :
![sample](https://github.com/KRTirtho/spotube/assets/95183520/ae2628b5-66dc-448f-8ecd-3489713300ce)

I'm also on Android 19, Spotube v3.6.0, installed from F-Droid.

**Comment by yuesubi** [comment] 2024-05-21 16:13
I forgot to mention, the issue appeared last update, I believe.

**Comment by KRTirtho** [comment] 2024-06-01 06:49
Duplicate of #1463

**Closed by KRTirtho** 2024-06-01 06:49 UTC
Labels: bug
