### ISSUE TITLE
Remeber Preference

### ISSUE THREAD

**Issue by EAMC478** [KRTirtho/spotube#1599] opened 2024-06-10 03:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

Choosing the preferred song version every time is very irritating.

### Suggested solution

Is it possible to make spotube remember which version of the song I prefer. Like if I choose the remastered version once, it will always play that version.

### Self grab

- [x] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-07-09 14:15
It has implemented already.

Duplicate of #1223

**Closed by KRTirtho** 2024-07-09 14:15 UTC
Labels: enhancement

**Comment by EAMC478** [comment] 2024-07-12 06:09
Thank you for this feature. It works perfectly.

Will you implement this in the stable version?
