### ISSUE TITLE
Crash when closing

### ISSUE THREAD

**Issue by Fxsch** [KRTirtho/spotube#833] opened 2023-10-22 16:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I click the "x" to close Spotube, it crashes instead.

### Expected Behavior

It should close normally.

### Steps to reproduce

1. Activate option to use native title bar (didn't test if it's the same without enabling this option)
2. Close the application using the "x" in the title bar

### Operating System

Linux

### Spotube version

3.2.0

### Installation source

Flathub (Flatpak)

### Additional information

I'm using the GNOME desktop, in case that's important

**Comment by KRTirtho** [comment] 2023-10-26 04:16
Duplicate of https://github.com/KRTirtho/spotube/issues/768

**Closed by KRTirtho** 2023-10-26 04:16 UTC
Labels: bug
