### ISSUE TITLE
Android Auto support

### ISSUE THREAD

**Issue by DestroyerBDT** [KRTirtho/spotube#1846] opened 2024-09-05 06:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

[According to reply](https://discord.com/channels/1012234096237350943/1023294925397315755/1280961748643479554), Android Auto is not supported

### Suggested solution

Support for Android Auto app

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-09-19 14:49
Duplicate of #623

**Closed by KRTirtho** 2024-09-19 14:49 UTC
Labels: enhancement, potential-duplicate
