### ISSUE TITLE
Collaborated Playlists

### ISSUE THREAD

**Issue by AarushiswinnerYo** [KRTirtho/spotube#1966] opened 2024-10-06 03:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

As if now, there is no way to add songs to playlist as a collaborator 

### Suggested solution

I would love if the devs could add this feature.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-10-10 15:54
Duplicate of #927

**Closed by KRTirtho** 2024-10-10 15:54 UTC
Labels: enhancement
