### ISSUE TITLE
Song played on phone speaker is low quality (vs other multimedia apps on the phone)

### ISSUE THREAD

**Issue by mustard007** [KRTirtho/spotube#1183] opened 2024-01-31 03:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Playing song on phone speaker is weak compared to other multimedia applications. Even the stream URL played in web browser is a way better. I'm not talking about MP4 bitrate quality here! 

But if I play it through Bluetooth the quality is same has other multimedia apps.

### Expected Behavior

The audio sound should be the same quality has the other multimedia applications when played on the phone speaker.

### Steps to reproduce

1. Start playing a song on the phone speaker and check quality.
2.  Compare with the stream URL (in info button of the song) played from the web browser of the same song and hear the difference!

Phone is Pixel 6 Pro.

### Operating System

Android 14 on Pixel 6 Pro 

### Spotube version

V3.4.1

### Installation source

GitHub Releases (Binary)

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-01-31 08:48
Duplicate of #877

**Closed by KRTirtho** 2024-01-31 08:48 UTC
Labels: bug

**Comment by mustard007** [comment] 2024-01-31 18:08
> Duplicate of #877

It's not a bitrate or YouTube vs Jiosaavn or Piped related. All engines is same "On phone speaker: audio from the phone speaker"  audio quality. I use Jiosaavn. I also tried YouTube and Piped engine. It's like Spotube use not the same API engine in the phone vs other multimedia apps.

**Comment by mustard007** [comment] 2024-02-01 19:21
> > Duplicate of #877
> > @KRTirtho
> 
> The audio quality problem is not related to the bitrate, nor to YouTube, Jiosaavn or Piped. All the engines have the same audio quality when I listen to them on the phone speaker. I use Jiosaavn, but I also tried YouTube and Piped. It seems (it's like) that Spotube does not use the same API engine as the other multimedia applications on the phone. The problem only occurs for the sound coming out of the phone speaker. As I said, Bluetooth works fine.

@KRTirtho Just to be sure ! :)
