### ISSUE TITLE
On update from 3.6 to 3.8, no playback resumes, ONLY Loads DM Dokuro. 

### ISSUE THREAD

**Issue by cyndarion01** [KRTirtho/spotube#1938] opened 2024-09-28 16:24 UTC
### Is there an existing issue for this? (Please read the description)

- [X] I have searched the existing issues

### Current Behavior

I cannot for the life of me get music to play. It was working last week, the only thing that keeps re-appearing in any logs is "youtube.exploded" among other errors, and playback will not resume. Opening and closing the app repeatedly doesn't solve the problem. Sideloading the app doesn't solve the problem. Downgrade does not solve the problem.

### Expected Behavior

App should play on selection of a song within a few moments. No song loads, app hangs, pause is displayed but no song begins, and then it auto-cycles through however many more songs there are in queue, skipping all of them.

### Steps to reproduce

I went on both PC and Mobile, to update the app in the app store on mobile and through the official page on PC where you list downloads. Now that its been about two weeks, I've tried everything. 
I've tried: - Jiosavan
- Piped (every server)
- Youtube options
- Reinstalling both, scrubbing them, clearing their caches, resetting them to an earlier version
- Force resetting in app
- Signing in with 2 different premium accounts from 2 people

I'll select a song, it skips, loads the next one, a second plays, it skips, rinse repeat till I close the app or it crashes. Then I reopen, it says theres a playlist still playing. If I queue a song or track, it remains displayed on screen over the app. Only 1 playlist is working.

### Logs

<details>
<summary>Logs</summary>

```
<Replace this line by pasting your logs here>
```
</details>

### Operating System

Android 11.2 and Win 10 22H2

### Spotube version

3.81/ most recent

### Installation source

Website (spotube.krtirtho.dev), GitHub Releases (Binary), Play Store (Android)

### Additional information

Repo links from your website are also broken, they bring up the raw HTML code when selected for older versions of the app, can't backup to 3.6 because of it.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by Ramys** [comment] 2024-09-28 16:32
reported https://github.com/KRTirtho/spotube/issues/1920

**Comment by KRTirtho** [comment] 2024-10-01 16:53
Duplicate of #1916

**Closed by KRTirtho** 2024-10-01 16:53 UTC
Labels: bug
