### ISSUE TITLE
Spotube does not work in network environments where the regular spotify web client does

### ISSUE THREAD

**Issue by callegar** [KRTirtho/spotube#749] opened 2023-09-25 10:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some firewall setups practiced on the network appear to prevent spotube from operating correctly, while the spotify web client works fine.

Specifically one may experience spotube unable to login on spotify (no user shown) with spinners that never cease spinning in place of the username.  In this situation it is impossible to search, access lyrics, etc. Funny enough the "play" button works.

Please document what spotube does differently from the regular spotify web client.

### Expected Behavior

See description

### Steps to reproduce

See description

### Operating System

Linux

### Spotube version

v3.1.2

### Installation source

Flathub (Flatpak)

**Comment by MerkomassDev** [comment] 2023-09-25 10:39
Spotube has nothing to do with your network settings.

**Comment by KRTirtho** [comment] 2023-09-26 03:08
Duplicate of #706

**Closed by KRTirtho** 2023-09-26 03:08 UTC
Labels: bug
