### ISSUE TITLE
GUI interface appears, but fails to load content.

### ISSUE THREAD

**Issue by controlunit** [KRTirtho/spotube#1065] opened 2024-01-14 16:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

GUI interface appears, but fails to load content. Even when logged into Last.fm

### Expected Behavior

Should load content.
![spotube2](https://github.com/KRTirtho/spotube/assets/63740471/b5076ede-8fbd-4783-b831-e289543a7284)
![spotube1](https://github.com/KRTirtho/spotube/assets/63740471/d917f4ff-bc42-47a8-89d4-897b8be0ac3f)

### Steps to reproduce

Run app.

### Operating System

Debian Linux

### Spotube version

3.4.0

### Installation source

Flathub (Flatpak)

**Comment by taha-ghadirian** [comment] 2024-01-15 05:10
Hello, have you tried logging in to Spotify?

**Comment by Sudheesh-07** [comment] 2024-01-15 14:52
Heyy so you basically have to login to spotify this exact problem is explained on issue #1064

**Comment by KRTirtho** [comment] 2024-01-17 14:43
Duplicate of https://github.com/KRTirtho/spotube/issues/1064

**Closed by KRTirtho** 2024-01-17 14:43 UTC
Labels: bug, duplicate
