### ISSUE TITLE
Add search option.

### ISSUE THREAD

**Issue by Yapper27** [KRTirtho/spotube#1633] opened 2024-06-14 15:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Pain

I need a whitelisted words / blacklisted words.
When I try to listen to my favourite song, it keep use the live ver of it.

### Suggested solution

at least make Spotube remember my audio source option when switching audio :( oh and do that for the download button too.

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-07-09 13:59
This has been fixed in the nightly
Also,

Duplicate of #1223

**Closed** 2024-07-09 13:59 UTC
Labels: duplicate, enhancement
