### ISSUE TITLE
Unable to download songs on Android with Jiosavaan source

### ISSUE THREAD

**Issue by AniruddhaSadhukhan** [KRTirtho/spotube#1665] opened 2024-06-25 05:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I set the source as Jiosavaan. I click on download button on the songs. The file is getting created and no error shows in the frontend. But when trying to play the songs, it is not able to decode and play. 

### Expected Behavior

Downloaded songs to be playable on either Spotube or any external player. 

### Steps to reproduce

1. I opened the app
2. I set source as Jiosavaan 
3. I played a song
4. I downloaded the song
5. I tried playing the song in Spotube and other external player, but is is not playable

### Operating System

Android

### Spotube version

3.7.1

### Installation source

Play Store (Android)

### Additional information

I tried with YouTube source, there the downloaded song is playable.

Stacktrace :
============================== CATCHER 2 LOG ==============================
------- DEVICE INFO -------
id: UKQ1.230804.001
board: marblein
bootloader: unknown
brand: POCO
device: marblein
display: UKQ1.230804.001 release-keys
fingerprint: POCO/marblein/marblein:14/UKQ1.230804.001/V816.0.8.0.UMRINXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-295061-trkc5-hzh3l-h3kb0
isPhysicalDevice: true
manufacturer: Xiaomi
model: 23049PCD8I
product: marblein
tags: release-keys
type: user
versionBaseOs: POCO/marblein/marblein:14/UKQ1.230804.001/V816.0.7.0.UMRINXM:user/release-keys
versionCodename: REL
versionIncremental: V816.0.8.0.UMRINXM
versionPreviewSdk: 0
versionRelease: 14
versionSdk: 34
versionSecurityPatch: 2024-04-01
------- APP INFO -------
environment: release
version: 3.7.1
appName: Spotube
buildNumber: 32
packageName: oss.krtirtho.spotube
---------- ERROR ----------
Converting libavcodec frame to mpv frame failed.
------- STACK TRACE -------
#0      new AudioPlayerInterface.<anonymous closure> (package:spotube/services/audio_player/audio_player.dart:60)
#1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
#2      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#3      _DelayedData.perform (dart:async/stream_impl.dart:515)
#4      _PendingEvents.handleNext (dart:async/stream_impl.dart:620)
#5      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591)
#6      _microtaskLoop (dart:async/schedule_microtask.dart:40)
#7      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
------- CUSTOM INFO -------

### Self grab

- [ ] I'm ready to work on this issue!

**Comment by KRTirtho** [comment] 2024-07-09 12:49
Duplicate of #1133

**Closed by KRTirtho** 2024-07-09 12:49 UTC
Labels: bug
