### ISSUE TITLE
problems playing music

### ISSUE THREAD

**Issue by JoanAR65** [KRTirtho/spotube#558] opened 2023-07-07 15:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I've been playing songs for a while, there comes a time when a song keeps loading and never plays. And when trying to select another song, it can't be played either. I have to restart the app for it to play a song correctly.

### Expected Behavior

It would have to play the music without it being permanently loaded and allow another song to play without getting stuck

### Steps to reproduce

1. Open the app
2. Reproduce music
3. And when a few songs pass, the next song doesn't play anymore
4. To play a song again, close and open the app 

### Operating System

Android 13

### Spotube version

v. 3.0.0

### Installation source

Website (spotube.netlify.app)

**Comment by iBavtovich** [comment] 2023-07-08 12:22
I think this one related or duplicate of: 
> https://github.com/KRTirtho/spotube/issues/537

**Comment by KRTirtho** [comment] 2023-07-08 15:29
Duplicate of #537

**Comment by KRTirtho** [comment] 2023-07-08 15:29
please follow the progress there

**Closed by KRTirtho** 2023-07-08 15:29 UTC
Labels: bug, duplicate
