### ISSUE TITLE
Memory overflow + silent app crash or OS crash

### ISSUE THREAD

**Issue by systemoperator** [KRTirtho/spotube#506] opened 2023-05-07 16:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I start Spotube, there is a tremendous, greedy memory consumption after a while, starting to consume all available GBs of memory, including swap space. I guess, this is also the reason, why it silently crashes after a while, or my OS hangs/crashes, because there is no memory left. In the system monitor, I could see, 17 GB were currently used by Spotube, still increasing rapidly. I had to kill the Spotube process, otherwise my system would have crashed. The last time, this happened even when no music was playing, Spotube was just running in the background.

### Expected Behavior

I would have expected less memory usage, even less than Spotify.

### Steps to reproduce

1. Start Spotube
2. Just wait.

### Operating System

Linux Debian 11, 64-bit, Mate desktop

### Spotube version

2.7.1

### Installation source

Flathub (Flatpak)

### Additional information

This issue could be related: https://github.com/KRTirtho/spotube/issues/442

@isle9 mentioned in https://github.com/KRTirtho/spotube/issues/442#issuecomment-1466776414

> Spotube memory consumption seems to skyrocket after a few minutes. I saw it go up to 14gGB.

Remark: Notebook has been suspended sometimes.

**Comment by KRTirtho** [comment] 2023-06-11 12:28
Duplicate of https://github.com/KRTirtho/spotube/issues/442

**Closed** 2023-07-03 06:28 UTC
Labels: bug, duplicate
